### ISSUE TITLE
Issue parsing unicode character in comment 

### ISSUE THREAD

**Issue by NathanEckert** [google/google-java-format#1004]
Hi,

The formatter fails to parse the two following files.

I am using version `1.18.1-all-deps`

```java
public class JavaFormatterExample {

	public static void specialCharacter() {
		String template = "test%sTemplate";
		System.out.println(String.format(template, "\n")); // \u000A
	}
}
```
This outputs `./project/src/test/java/JavaFormatterExample.java:12:61: error: expected token: '\'; generated } instead`

And the following one:

```java
public class JavaFormatterExample {

	public static void specialCharacter() {
		String template = "test%sTemplate";
		System.out.println(String.format(template, "\r")); // \u000D
	}

}

```

This outputs `./project/src/test/java/JavaFormatterExample.java:12:61: error: expected token: '\'; generated } instead`

To solve it, I can re-escape the character in the comment, but it is a valid java file, so IMO it is a bug.

Regards,

**Comment by cushon** [comment]
#836
