### ISSUE TITLE
Cannot format switch with `case null, default ->`

### ISSUE THREAD

**Issue by djavanci** [google/google-java-format#1008]
I created a small gradle project in IntelliJ, configured the plugin to use last toolVersion (1.18.1), gradle 8.5 and java 21. In the project I have only the Main and I added the following:
```
  public static String useSwitch(final Integer value) {
    return switch (value) {
      case 0 -> "it was 0";
      case 1 -> "it was 1";
      case 2 -> "it was 2";
      case null, default -> "unexpected value";
    };
  }

  public static void main(String[] args) {

    System.out.println("Hello world!");

    final String retStr = useSwitch(Integer.valueOf(args[1]));
    System.out.println("retStr = " + retStr);
  }
```
When I run in terminal `gradle goJF` it just says that 
```
Detected Java syntax errors in the following files (you can exclude them from this task, see "https://github.com/sherter/google-java-format-gradle-plugin" for details):

<...>/TestSwitch/src/main/java/com/switchtest/Main.java
```

If I change the switch to have null and default in different lines, like below
```
      case null -> "null value";
      default -> "unexpected value";
```
it works.
I'm attaching the project here, for easier understanding.

[TestSwitch.tgz](https://github.com/google/google-java-format/files/13638751/TestSwitch.tgz)

**Comment by natros** [comment]
There have been recent commits that should resolve the issue. Try the `HEAD-SNAPSHOT` version which works. At least it worked for me

**Comment by cushon** [comment]
Yes, this is fixed at head. I'll try to get a release out in the next week or so.
