### ISSUE TITLE
GJF deletes file-ending comment

### ISSUE THREAD

**Issue by mernst** [google/google-java-format#101]
Here is a serious issue.

Consider the following file:
```
public @interface kHz {} // No prefix defined in the annotation itself
```

Running GJF yields the file with the final comment deleted!

```
% java -jar ~/java/google-java-format/core/target/google-java-format-1.2-SNAPSHOT-all-deps.jar kHz.java
public @interface kHz {}
```

**Comment by mernst** [comment]
The issue affects `/*...*/` comments at the end of a file as well as `//` comments at the end of a file.

**Comment by sherter** [comment]
Maybe related to #47

**Comment by cushon** [comment]
I suspect 946e01cc1440cd5f6fdcad11225b62357f1ed910, thanks for the report.
