### ISSUE TITLE
No discretion in line wrapping

### ISSUE THREAD

**Issue by therealppa** [google/google-java-format#102]
According to the style guide at https://google.github.io/styleguide/javaguide.html#s4.5-line-wrapping

> Note: While the typical reason for line-wrapping is to avoid overflowing the column limit, even code that would in fact fit within the column limit may be line-wrapped at the author's discretion.

I noticed that google-java-format allows no such discretion. The following examples seem to always be formatted into a single line:

    return Objects.equals(this.id, employee.id)
        && Objects.equals(this.name, employee.name);

    return toStringHelper(this)
        .add("id", id)
        .add("name", name)
        .toString();

Is this on purpose?

**Comment by drothmaler** [comment]
Any progress on this?
The removal of this kind of line wrappings is really annoying - especially when dealing with all kinds of Fluent APIs (like ToStringBuilder or the Java 8+ Stream API).

**Comment by tbroyer** [comment]
I think the commonly adopted practice is to add a comment to force wrapping. Reusing the examples from above:

```java
return Objects.equals(this.id, employee.id) //
    && Objects.equals(this.name, employee.name);

return toStringHelper(this) //
    .add("id", id)
    .add("name", name)
    .toString();
```

**Comment by talios** [comment]
@tbroyer that smells like a dirty work-around to a "commonly experienced problem". If people are commonly doing this to workaround an issue, maybe.... it's an issue.

**Comment by cushon** [comment]
Preserving existing formatting was not a design goal, there's some related discussion here: https://github.com/google/google-java-format/issues/318#issuecomment-441764793

Using `//` isn't really a recommended practice. It can be useful a useful work-around in some cases, e.g. I've written code like this:

```java
lines(
    "class Test {", //
    "  void f() {}",
    "}");
```

**Comment by therealppa** [comment]
It has been quite q while since I opened this issue and I want to say I got used to the behaviour. So from my point this could be closed.
