### ISSUE TITLE
Is there a plan to release a new IntelliJ IDEA plugin with version 1.19.2?

### ISSUE THREAD

**Issue by hisener** [google/google-java-format#1024]
The latest version of the [IntelliJ IDEA plugin](https://plugins.jetbrains.com/plugin/8527-google-java-format) still uses v1.17.0. It is problematic since there are some changes around switch expressions in v1.18.0. Is there a plan to cut a new release for the IDEA plugin?

**Comment by hisener** [comment]
cc @cushon

**Comment by paomian** [comment]
I had the same question. But I'm not familiar with idea's plugins and I don't know if this is a complicated endeavor.

**Comment by plumpy** [comment]
I just published a 1.19.2 version of the plugin. Sorry for the delay.

**Comment by paomian** [comment]
update to the 1.19.2 get `google-java-format failed. Does xxx.java have syntax error?`
I can't find any log for plugin on [this place](https://plugins.jetbrains.com/docs/intellij/ide-development-instance.html?from=jetbrains.org#development-instance-settings-caches-logs-and-plugins).

**Comment by torholm** [comment]
@paomian I think the formatter is failing because your IntelliJ is running in an older JVM. Using another boot runtime solved the issue for me.

**Comment by paomian** [comment]
@torholm my jdk version is java21. It will be error when current file contains some syntax in java21.

**Comment by torholm** [comment]
@paomian The issue is specifically which Java version IntelliJ is running in (aka boot JDK), not the language level of your code.

Here's a guide on how to change the boot JDK in IntelliJ:
https://www.jetbrains.com/help/idea/switching-boot-jdk.html

**Comment by paomian** [comment]
@torholm My boot JDK is jdk21.

**Comment by hisener** [comment]
@plumpy Gentle bump on this since the last two releases still need to be published.

**Comment by plumpy** [comment]
Whoops, sorry, published v1.22.0.

**Comment by hisener** [comment]
No worries. Thank you 🙇
