### ISSUE TITLE
Is it possible to set the same indetation for function wraps as for all other code?

### ISSUE THREAD

**Issue by Yury-Fridlyand** [google/google-java-format#1027]
Hi

My goal is to have 4 spaces intedtation everywhere, for example:
```java
class Klass {
    // 4 spaces
    public Klass() {
        // extra 4
        this(
            // extra 4
            args
            ....
    }
}
```

My experiments so far
```
indentWithTabs(1)
indentWithSpaces(4)
```
```java
class Klass {
                // 16 spaces !!
                public Klass() {
                                // extra 16 !!
                                this(
                                                                // extra 32 !!
                                                                args
                                                                ....
                }
}
```
lolwut, 16 spaces...
```
indentWithTabs(2)
indentWithSpaces(4)
```
```java
class Klass {
        // 8 spaces !!
        public Klass() {
                // extra 8 !!
                this(
                                // extra 16 !!
                                args
                                ....
        }
}
```
```
indentWithTabs(4)
indentWithSpaces(4)
```
```java     
class Klass {
    // 4 spaces
    public Klass() {
        // extra 4
        this(
                // extra 8 !!
                args
                ....
    }
}
```
```
indentWithTabs(2)
indentWithSpaces(4)
```
```java     
class Klass {
  // 2 spaces !!
  public Klass() {
    // extra 2 !!
    this(
        // extra 4
        args
        ....
  }
}
```

The best I got is 8 or 6 (why!?) spaces after `this(` wrap. Is it possible to have 4 spaces indent there?
Thanks!

**Comment by cushon** [comment]
There isn't a supported way to get the desired indentation here, [this entry in the FAQ](https://github.com/google/google-java-format/wiki/FAQ#i-just-need-to-configure-it-a-bit-differently-how) is related.

Is `indentWithTabs` and `indentWithSpaces` configuration for https://github.com/diffplug/spotless?

I think the behavior you're seeing is that the formatter uses different indentation for [blocks](https://google.github.io/styleguide/javaguide.html#s4.2-block-indentation) and ['continuation lines'](https://google.github.io/styleguide/javaguide.html#s4.5.2-line-wrapping-indent), there isn't a supported way to use the same indentation for both.

**Comment by Yury-Fridlyand** [comment]
Hi @cushon, thank you for your reply.
Yes, I'm using https://github.com/diffplug/spotless.
