### ISSUE TITLE
Parameter annotation handling

### ISSUE THREAD

**Issue by therealppa** [google/google-java-format#103]
The style guide says:

> There are no specific rules for formatting annotations on parameters, local variables, or types.

So I guess it's fair game to pick a strategy. Is that strategy documented somewhere? In any case, it changed between 1.0 and 1.1, for example I have something like this in an Interface:

Version 1.0:

    ResponseEntity<String> getEmployeeNameById(
        @ApiParam(value = "The code of the employee (e.g. 'abc')", required = true)
        @PathVariable("id")
        String id);

Version 1.1:

    ResponseEntity<String> getEmployeeNameById(
        @ApiParam(value = "The code of the employee (e.g. 'abc')", required = true)
            @PathVariable("id")
            String id);

I strongly prefer the version 1.0 formatting.

**Comment by cushon** [comment]
The change was deliberate: da38d176e421946b10ec1d9554054c98fd081030.

Without the continuation indent, it's harder to scan for individual parameter declarations:

```java
QueryEntityPathsResponse produceQueryEntityPathsResponse(
    @Node @EntityResultPathsForStations
        ImmutableList<EntityResultPath> entityResultPathsForStations,
    @Node @EntityResultPathsForFilters
        ImmutableList<EntityResultPath> entityResultPathsForFilters) {
```

**Comment by therealppa** [comment]
Good reasoning! Thanks for the explanation.
