### ISSUE TITLE
The unused method cannot be detected 

### ISSUE THREAD

**Issue by 1996fanrui** [google/google-java-format#1038]
Here is an example, the `import static org.test.TestA.getAA;` is not used, and the `Test#getAA` will be used.

But after checkstyle, `import static org.test.TestA.getAA;` cannot be removed, and getAB can be removed.

Bug reason: when the method name is used, `google-java-format` think this method should be imported. But getAA may be a method of current class.

Note: import getAA may be needed when their parameters are not same.

```
import static org.test.TestA.getAA;
import static org.test.TestA.getAB;

public class Test {

    public static int get() {
        return getAA();
    }

    private static int getAA() {
        return 1;
    }
}
```

**Comment by cushon** [comment]
This is out of scope for google-java-format, there's some related information in this bug:

https://github.com/google/google-java-format/issues/72#issuecomment-251541210
