### ISSUE TITLE
Import Ordering configuration suppressed on README 

### ISSUE THREAD

**Issue by habutre** [google/google-java-format#1041]
From version `v.1.16.0` to `v1.17.0` the instruction below was removed without any reference in the commit message which make me think whether this instruction is still valid or not (I guess it's still valid)

> The import ordering is not handled by this plugin, unfortunately. To fix the import order, download the [IntelliJ Java Google Style file](https://raw.githubusercontent.com/google/styleguide/gh-pages/intellij-java-google-style.xml) and import it into File→Settings→Editor→Code Style.

In case such instruction is still valid would be good to bring it back

**Comment by tbroyer** [comment]
It's not, see https://github.com/google/google-java-format/commit/84b2c9a2ba382ee7a968518b46afb0d6000ada8d

**Comment by habutre** [comment]
Thanks @tbroyer I was looking for a more informative message saying the reason to not import the style file anymore
