### ISSUE TITLE
1.20.0 binaries reports incorrect version (HEAD-SNAPSHOT) when called with the -v flag

### ISSUE THREAD

**Issue by abceleung** [google/google-java-format#1068]
Hi, I downloaded the Linux and Windows version of the google-java-format binaries (added in 1.20.0). 

Both of them outputs `google-java-format: Version HEAD-SNAPSHOT` when called with the `-v` flag. Is this intended behavior?

The jar version correctly outputs `google-java-format: Version 1.20.0`.

**Comment by cushon** [comment]
Thanks, I fixed the release process to update the versions for the native image builds, the next release should include correct version numbers

**Comment by cushon** [comment]
The fix has been released in https://github.com/google/google-java-format/releases/tag/v1.21.0

```
$ ./google-java-format_darwin-arm64 -version
google-java-format: Version 1.21.0
```
