### ISSUE TITLE
Feature request - add a flag to specify the path to google-java-format-diff.py

### ISSUE THREAD

**Issue by jpd236** [google/google-java-format#108]
Context: https://android-review.googlesource.com/#/c/314751

We're having to resort to editing $PATH before calling google-java-format-diff.py because the tool doesn't support specifying the path manually. This is a bit hacky - it would be nice if the script supported taking the path to the binary directly before resorting to find_executable or the hard-coded path in /usr/bin.

**Comment by cushon** [comment]
This is a duplicate of #44.
