### ISSUE TITLE
Excess indentation with method-receiving text blocks

### ISSUE THREAD

**Issue by Stephan202** [google/google-java-format#1081]
The new `fmt-maven-plugin` release [comes with](https://github.com/spotify/fmt-maven-plugin/compare/2.22.1...2.23#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8R87-R91) an upgrade from GJF 1.19.2 to GJF 1.21.0. With this upgrade it appears that text blocks ~inside lambda expressions~ that are the receiver of a method are indented too far to the right. See [PicnicSupermarket/error-prone-support@`a2196ee` (#1069)](https://github.com/PicnicSupermarket/error-prone-support/pull/1069/commits/a2196eea69465a5809b1f299cd9a489bba600e10) for an example. This is what that code would look like if the text block contents are shifted to the right to match the new position of the text block start marker:
```java
unexpectedMatchesByLineNumber.entries().stream()
    .map(
        e ->
                """
                Rule `%s` matches on line %s, while it should match in a method named \
                `test%s`."""
                .formatted(e.getValue(), e.getKey(), e.getValue()))
```

I.e.: an amount of indentation that better matches `AOSP` rather than `GOOGLE` style. I assume that this is a side-effect of ce3cb59a8d649359a8e6e7fcc5f2f21bb79b3df1.

(Apologies for not providing a 100% stand-alone reproduction case; can do that ~this weekend if desired.)

**Comment by cushon** [comment]
Thanks for the report, I agree this is an issue. I don't think it's specific to lambda bodies, in general if text blocks show up as the receive of a method call they are getting a  surprising continuation indent:

```java
class T {
  {
    System.err.printf("hello %s\n", world);
        """
        hello %s
        """
        .formatted("world");
  }
}
```

**Comment by Stephan202** [comment]
Right, makes sense! Should have played around with the example a bit more. I'll update the ticket description :+1:
