### ISSUE TITLE
bug report: 1.21.0 IntelliJ vs jar inconsistency

### ISSUE THREAD

**Issue by ssh352** [google/google-java-format#1088]
<img width="466" alt="Screenshot 2024-03-27 at 10 46 38" src="https://github.com/google/google-java-format/assets/41779116/8999724e-960b-475f-a9ac-014575cee26c">

the top one is from
```
 java -jar /usr/local/bin/google-java-format-1.21.0-all-deps.jar --aosp --skip-sorting-imports -i A.java
```

the bottom one is from IntelliJ google java format plugin 1.21.0 version.  It adds additional 4 spaces to the second line.

Please advise

**Comment by cushon** [comment]
Does passing `--skip-reflowing-long-strings` to the CLI match the IntelliJ behaviour?

Can you share the contents of `A.java` as text, instead of a screenshot?

**Comment by ssh352** [comment]
> `--skip-reflowing-long-strings`

the inconsistency comes from  `--skip-reflowing-long-strings`. I want to use this option however. 

```
class A {
    public static void main(String[] args) {
        System.out.println(
                "abc joijefoi owejf weifj oeijfwoiejf oweijf oweijf oweijf oweijf oweijf owej feoiwjfoweijf oweijf ");
    }
}
```

**Comment by cushon** [comment]
https://github.com/google/google-java-format/issues/566
