### ISSUE TITLE
Release GJF based on javac

### ISSUE THREAD

**Issue by gk5885** [google/google-java-format#111]
Dagger users have been experiencing an issue (https://github.com/google/dagger/issues/457) with a bad interaction between ecj and a jdk bug.  Given that gjf at head doesn't use ecj anymore, a new release would help us out a lot.

**Comment by cushon** [comment]
I need to make sure the javac9-based GJF works on JDK8 without bootclasspath hacks, and then I'll do a release.

**Comment by cushon** [comment]
Version 1.2 is released.
