### ISSUE TITLE
I don't see google-java-format

### ISSUE THREAD

**Issue by zaqpiotr** [google/google-java-format#1110]
On MacOS 14.5 IntelliJ 2024.1.3

I don't see google-java-format

![image](https://github.com/google/google-java-format/assets/2997544/85517f32-bd08-4858-bf37-030cc0bcfaa5)

and plugin is enabled

![image](https://github.com/google/google-java-format/assets/2997544/4db7ad5f-ec76-4e20-81be-09c9d92f67db)

**Comment by cushon** [comment]
The google-java-format IntelliJ plugin doesn't change the IntelliJ 'Code Style', the installation instructions for the plugin are here: https://github.com/google/styleguide/blob/gh-pages/intellij-java-google-style.xml

If you want a 'Code Style' for Google Java Style, there's one available separately here: https://github.com/google/styleguide/blob/gh-pages/intellij-java-google-style.xml
