### ISSUE TITLE
Issue with text blocks formatting on java 21. Defaulting to extreme left indentation

### ISSUE THREAD

**Issue by rohan-changejar** [google/google-java-format#1113]
- [ ]  Issue description - While trying to migrate our existing string implementations of string append to the latest text block format 
in our java 21 project, we are seeing that text blocks are not being handled properly and therefore causing unexpected left indentation, which is deviant from the standard formatting pattern
    
- [ ] Gradle or Maven version -     id "com.diffplug.spotless" version "6.17.0"
- [ ] operating system and version - MacOs sonoma 14.5
- [ ] `spotless {
    java {
//        googleJavaFormat()
        // optional: you can specify a specific version (>= 1.8) and/or switch to AOSP style
        //   and/or reflow long strings
        //   and/or use custom group artifact (you probably don't need this)
        googleJavaFormat('1.22.0').aosp().reflowLongStrings().groupArtifact('com.google.googlejavaformat:google-java-format')    }
}`

<img width="940" alt="image" src="https://github.com/diffplug/spotless/assets/83759161/148c2dbe-5973-4f17-b3f1-c2823e85f4df">

**Comment by tejasraj-jar** [comment]
Facing the same issue, please help

**Comment by ksingh11** [comment]
facing the same issue, is there anyone looking into it? or any workaround?

**Comment by sid-jar** [comment]
+1 .. Facing a similar issue

**Comment by Sehag** [comment]
Ruins the point of formatting the code, please fix this

**Comment by neutrino1997** [comment]
Same here.

**Comment by yashwithalva** [comment]
Facing a similar issue, Please fix.

**Comment by Shreyank031** [comment]
Facing the same issue.

**Comment by Naresh-Srinivas** [comment]
Facing the similar issue, taking a bit more time to format it and thus reducing the efficiency of the developers. Please help us sort this soon. Thank you!

**Comment by sormuras** [comment]
Related to
- #883 ?

As a workaround sometimes it helps to use an older version of g-j-f ... what never helps is spamming an issue with "+1 comments".

**Comment by mimbrero** [comment]
+1...

**Comment by cushon** [comment]
https://github.com/google/google-java-format/issues/883
