### ISSUE TITLE
Formatter recognizes new switch syntax as syntax error

### ISSUE THREAD

**Issue by HoJoServer** [google/google-java-format#1119]
If you add the following syntax to a file:
```Java
Integer i = 0;
switch (i){
  case null, default -> {}
}
```
The Formatter will not run. It seems to pick this up as a syntax error.

OS: Ubuntu 24.4
Java: Version 21
Gradle Plugin: 7.0.0.BETA1
Google style version: 1.22.0

**Comment by bobaikato** [comment]
Experiencing the same issue.

**Comment by cushon** [comment]
It works for me:

```
$ java -version
openjdk version "22.0.1" 2024-04-16
$ java -jar google-java-format-1.22.0-all-deps.jar T.java
class T {
  {
    Integer i = 0;
    switch (i) {
      case null, default -> {}
    }
  }
}
```

Note that to format Java 21 language features, the formatter has to be running on JDK 21 or newer.
