### ISSUE TITLE
RemoveUnusedImports adds extra newline before first import on Windows.

### ISSUE THREAD

**Issue by jbduncan** [google/google-java-format#112]
As we were working on [Spotless](https://github.com/diffplug/spotless) 3.0.0, @nedtwigg and I discovered that [RemoveUnusedImports::removeUnusedImports](https://github.com/google/google-java-format/blob/13f608bbd6f3f26c3eec05807b3a37bef9bb7670/core/src/main/java/com/google/googlejavaformat/java/RemoveUnusedImports.java#L195) inserts an extra newline right before the first `import` after removing the unused imports of a given Java string. This bug only occurs when running on Windows.

This can be reproduced by running the following steps:
1. `git clone https://github.com/diffplug/spotless.git`
2. `cd spotless`
3. `git checkout b3f4e4487cb4de95e57711487d5bffea2b62cde6`
4. `gradlew.bat clean test`
5. Open `testlib\build\reports\tests\index.html` in a web browser.
6. Navigate to the failed tests and read their stack traces.

**Comment by cushon** [comment]
This will be fixed in the next release: a1c790b75e5c5e32241bf1da81f671e702122dd5.

**Comment by jbduncan** [comment]
Ah, fantastic! :+1:

Looking forward to the next release then. :)
