### ISSUE TITLE
Different formatting for `switch` comments depending on JDK version

### ISSUE THREAD

**Issue by msridhar** [google/google-java-format#1127]
Input:
```java
class TestSwitch {
  enum TestEnum {
    ONE,
    TWO
  }

  void test(TestEnum e) {
    switch (e) {
      case ONE:
        System.out.println("one");
        break;
        // test comment
      default:
        System.out.println("default");
    }
  }
}
```
If I run GJF 1.23.0 on JDK 11 for this input, the formatting is unchanged.  But, if I run it on JDK 17 or higher, the indentation of the `// test comment` line is changed to match that of `default:`.  Is this expected behavior?  Seems related to https://github.com/google/google-java-format/commit/f7543b2a7d3b9c5b8214b33e8762e9550f5ab20f.

**Comment by cushon** [comment]
Thanks, that's a bug. The JDK 17+ behaviour is the expected one after https://github.com/google/google-java-format/commit/f7543b2a7d3b9c5b8214b33e8762e9550f5ab20f
