### ISSUE TITLE
wildcard imports are not expanded

### ISSUE THREAD

**Issue by ash-owl** [google/google-java-format#113]
Running `java -jar google-java-format-1.2-all-deps.jar Test.java` where `Test.java` contains

```
import java.util.*;

class Test {
  List a;
}
```

results in the following output:

```
import java.util.*;

class Test {
  List a;
}
```

but the expected output is:

```
import java.util.List;

class Test {
  List a;
}
```

**Comment by kevinb9n** [comment]
This is out of scope for a source code *formatter*. Note it would require access to your entire compilation classpath to work correctly.

**Comment by ash-owl** [comment]
Fair enough, but are the unenforceable rules of https://google.github.io/styleguide/javaguide.html documented anywhere? For example checkstyle has this: http://checkstyle.sourceforge.net/google_style.html

**Comment by r4fterman** [comment]
Hi @kevinb9n,
your comment contradicts the project documentation.

> This is out of scope for a source code formatter. Note it would require access to your entire compilation classpath to work correctly.

Documentation says that this plugin takes care of code formatting and import optimization:

> When enabled, it will replace the normal `Reformat Code` and `Optimize Imports` actions.

So I would assume that imports are handled correctly according to the Google Code Style.

Regars, Roman

**Comment by DidierLoiseau** [comment]
> When enabled, it will replace the normal `Reformat Code` and `Optimize Imports` actions.

Oh, so this is why it breaks IntelliJ’s default import optimization, which would take care of this properly!
