### ISSUE TITLE
False positive: 'switch without "default" clause. [MissingSwitchDefault]' for sealed interface pattern matching

### ISSUE THREAD

**Issue by kenwang-coursera** [google/google-java-format#1131]
Code:

```
      switch (result) {
        case Result.Success(Response response) -> {
          // do something
        }
        case Result.Failure(Throwable e) -> {
          // do something else
        }
      }
```

Results in `switch without "default" clause. [MissingSwitchDefault]`

Even though `Result.Success` and `Result.Failure` are sealed implementations of `Result` and exhaustive.

**Comment by cushon** [comment]
That diagnostic wasn't produced by google-java-format.

Are you using MissingSwitchDefault? It has a check with that name: https://checkstyle.sourceforge.io/checks/coding/missingswitchdefault.html. If so you could report the issue here: https://github.com/checkstyle/checkstyle/issues

**Comment by kenwang-coursera** [comment]
d'oh! My mistake! Sorry about that!
