### ISSUE TITLE
Does it support mybatis xml sql formatting?

### ISSUE THREAD

**Issue by DreamPWJ** [google/google-java-format#1133]
SQL is often used in Java, and I hope this formatting will not be supported.

**Comment by cushon** [comment]
I'm not sure what the feature request is, could you share an example of a `.java` file that you would like to be formatted differently?

**Comment by DreamPWJ** [comment]
Not .java, but .xml or .sql
`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" "http://mybatis.org/dtd/mybatis-3-mapper.dtd">
<mapper namespace="com.iot.carlock.app.mapper.device.DeviceBizMapper">



    <select id="getDeviceByDeviceId" resultType="com.iot.carlock.entity.device.Device">
        select *
        from device
        where device_id = #{deviceId}
    </select>


    <select id="getDevicesByParkId" resultType="com.iot.carlock.entity.device.Device">
        select *
        from device
        where park_id = #{parkId}
    </select>


</mapper>`

**Comment by cushon** [comment]
This project only supports formatting Java code.

**Comment by DreamPWJ** [comment]
Can you provide the formatting principle and format it yourself?

**Comment by cushon** [comment]
> Can you provide the formatting principle and format it yourself?

I'm not sure what you mean, can you expand on the question? This tool only supports formatting Java code, and there isn't a way to customize it or provide configuration to format other languages.
