### ISSUE TITLE
Release new IntelliJ plugin for v1.23.0 (Latest 2 weeks ago)?

### ISSUE THREAD

**Issue by dhalperi** [google/google-java-format#1137]
IntelliJ plugin seems not to have been released to UI keeps reverting tool fixes. Is there a way to make the plugin use a different version of the tool, or otherwise can you please trigger the release process for the new 1.23.0 release?

**Comment by dhalperi** [comment]
P.S. overall the plugin is working great for me; I know a lot of other reports are having a hard time but I've been able to make everythng work on macOS with JDK11 or JDK17 and IntelliJ CE or UE.

**Comment by hisener** [comment]
cc @plumpy as you released it in https://github.com/google/google-java-format/issues/1024.

**Comment by plumpy** [comment]
There's a v1.23.0.0 version of the plugin now, sorry for the delay.

https://plugins.jetbrains.com/plugin/8527-google-java-format/versions/stable/591622
