### ISSUE TITLE
Plugin is incompatible with IntelliJ IDEA 2016.3 163.11103.6

### ISSUE THREAD

**Issue by dozortsev** [google/google-java-format#115]
Please add support for latest IntelliJ's versions. For more info check the **[SO question](http://stackoverflow.com/q/41780576/2650174)**.

**Comment by markiewb** [comment]
FYI the support of 2016.3 has been disabled in https://github.com/google/google-java-format/commit/044961c6f2cb42f67a83b333b60c6bb2a05a1f7a

See the comments in the code
>  CodeStyleManager stayed the same from 143 (IDEA 15) through 162 (2016.2). But they changed a parameter type of a method in 163 (2016.3), so it needs some work to fix.

> Mark it as unsupported in 2016.3. Which it is. (For now.)

**Comment by kevin-brotcke** [comment]
Looks like an [update](https://plugins.jetbrains.com/plugin/8527-google-java-format) was published on April 14th, 2017 that added support for 163+ builds.
