### ISSUE TITLE
Increasing minimum supported JDK (and dropping support for JDK 11)

### ISSUE THREAD

**Issue by cushon** [google/google-java-format#1159]
Following the example of https://github.com/google/error-prone/issues/3803, we're considering removing support for running google-java-format on JDK 11. The new minimum supported JDK would be JDK 17 (the next LTS release after 11).

google-java-format would still fully support formatting earlier source code versions, it would just require running the tool on JDK 17 or later.

**Comment by sormuras** [comment]
Doesn't the runtime version determine the source code version at the moment? Or does GJF support a `--source 11` option? 🤔

**Comment by tbroyer** [comment]
Afaict it determines what can be parsed but not how it'll be formatted.

**Comment by cushon** [comment]
> Afaict it determines what can be parsed but not how it'll be formatted.

Right, it'll parse at whatever the newest language level supported by the runtime is, and shouldn't affect formatting. Newer source versions are usually a superset of older ones, but there are some occasional breaking changes like new reserved identifiers, #975 is a related FR about making the source version g-j-f parses at configurable.

**Comment by cushon** [comment]
I just pushed another release, and am planning to update the minimum supported JDK to 17 for the next release after that one: https://github.com/google/google-java-format/releases/tag/v1.24.0

**Comment by cushon** [comment]
I pushed 1.24.0, which raises the minimum supported JDK to JDK 17: https://github.com/google/google-java-format/releases/tag/v1.24.0
