### ISSUE TITLE
Short Javadoc with @link tag gets formatted to single line Javadoc

### ISSUE THREAD

**Issue by tinder-mhernandez** [google/google-java-format#117]
[google_checks.xml](https://github.com/checkstyle/checkstyle/blob/checkstyle-7.4/src/main/resources/google_checks.xml) for Checkstyle 7.4 specifies the rule `SingleLineJavadoc` like so:
```
        <module name="SingleLineJavadoc">
            <property name="ignoreInlineTags" value="false"/>
        </module>
```
Please see [line 220](https://github.com/checkstyle/checkstyle/blob/checkstyle-7.4/src/main/resources/google_checks.xml#L220).

## Repro:
```
package com.example;

/**
 * Single line Javadoc that references {@link String}.
 */
public class Sample {
}
```

```
java -jar google-java-format-1.2-all-deps.jar Sample.java
```
```
package com.example;

/** Single line Javadoc that references {@link String}. */
public class Sample {}
```

```
java -jar checkstyle-7.4-all.jar -c google_checks.xml Sample.java 
```
```
Starting audit...
[WARN] /Users/marcelohernandez/Desktop/SampleProject/Sample.java:3: Single-line Javadoc comment should be multi-line. [SingleLineJavadoc]
Audit done.
```

**Comment by tinder-mhernandez** [comment]
I had originally filed an [issue](https://github.com/checkstyle/checkstyle/issues/3762) against [Checkstyle](https://github.com/checkstyle/checkstyle), however the rule is technically adhering to https://google.github.io/styleguide/javaguide.html#s7.1.1-javadoc-multi-line.

> The basic form is always acceptable. The single-line form may be substituted when there are no at-clauses present, and the entirety of the Javadoc block (including comment markers) can fit on a single line.

**Comment by lowasser** [comment]
I think the issue is the interpretation of "at-clauses": I interpret that as meaning `@param` and the other "full-line" type things rather than the inline `{@link String}`.

**Comment by tinder-mhernandez** [comment]
I agree with your interpretation as well @lowasser. However, the [guide](https://google.github.io/styleguide/javaguide.html#s7.1.1-javadoc-multi-line) does not clarify this and in failing to do so was enough justification to close https://github.com/checkstyle/checkstyle/issues/3762.

**Comment by cpovirk** [comment]
It would be nice if the Style Guide defined the term "at-clauses" before using it. But it's defined afterward instead: https://google.github.io/styleguide/javaguide.html#s7.1.3-javadoc-at-clauses There, it gives a complete list of standard "at-clauses," which includes only "'full-line'-type things," and talks about indentation of continued lines, which is also pretty clearly a feature exclusive to full-line tags.

I don't think it's ambiguous, but it's not as clear as it could be. Maybe the Style Guide should use the term "block tags," which is what the documentation for Javadoc calls them.

**Comment by tinder-mhernandez** [comment]
I believe the style guide has since been updated https://github.com/google/styleguide/commit/594d91bfbb8dfcbcac0f148af8175f2b7ec9857b
