### ISSUE TITLE
1.25.0 release is missing

### ISSUE THREAD

**Issue by ZacSweers** [google/google-java-format#1194]
This is present on maven central but there's no release notes or fat jar published

**Comment by ZacSweers** [comment]
https://github.com/google/google-java-format/releases/tag/v1.25.0

**Comment by cushon** [comment]
Sorry for the mixup, it should be fixed now. (https://github.com/google/google-java-format/issues/1159#issuecomment-2484494735 is related)

**Comment by chenrui333** [comment]
Thanks @ZacSweers @cushon!
