### ISSUE TITLE
Formatting of empty types is not idempotent

### ISSUE THREAD

**Issue by PhilippWendler** [google/google-java-format#12]
The code
```
public class Test {

}
```
is formatted by google-java-format to
```
public class Test {
}
```
and if it is run again on the result the output of the second run is
```
public class Test {}
```

I think this should be done in one step. It occurred originally for me on an annotation with no members.

**Comment by kevinb9n** [comment]
Thanks! I think (from what I understand) this might be fixed in the next update.

**Comment by PhilippWendler** [comment]
Actually, when think about it, I prefer the two-line version (with closing brace on separate line) for empty types. It makes the diff have less impact when a member gets added later.

The Google Java Style says the single-line variant is optional, so maybe google-java-format could output the two-line variant consistently for empty types, if you agree it is nicer?

**Comment by cushon** [comment]
The non-idempotent formatting bug is fixed now.

I think the verdict is to stick with the one-line form, although in general the formatter does prioritize cleaner diffs over saving vertical lines.
