### ISSUE TITLE
Early Access build fails to new JAXP limit of `100000`

### ISSUE THREAD

**Issue by sormuras** [google/google-java-format#1210]
With https://bugs.openjdk.org/browse/JDK-8343004 () the `jdk.xml.maxGeneralEntitySizeLimit` was set from unlimited to `100000` in JDK 24.

https://github.com/openjdk/jdk/commit/28c8729019292820f17002cc007305418f2d2676#diff-031529e6458daa18972454e3e220c776db020cc0657ce881e649f99148d2f4ecR166-R167

```
# Limits the maximum size of any general entities. The default value is 100000.
jdk.xml.maxGeneralEntitySizeLimit=100000
```

That leads to an error in the CI run using JDK 25-ea:
```
Error: [ERROR] Internal error: java.lang.RuntimeException: Failed to load p2 repository with ID 'mars' from location https://download.eclipse.org/releases/mars: Unable to read repository at https://download.eclipse.org/releases/mars. Unable to read repository at file:/home/runner/.m2/repository/.cache/tycho/https/download.eclipse.org/releases/mars/201506241002/content.xml.xz. JAXP00010003: The length of entity "[xml]" is "100,001" that exceeds the "100,000" limit set by "jdk.xml.maxGeneralEntitySizeLimit". -> [Help 1]
[...]
Caused by: org.xml.sax.SAXParseException: JAXP00010003: The length of entity "[xml]" is "100,001" that exceeds the "100,000" limit set by "jdk.xml.maxGeneralEntitySizeLimit".
    at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse (AbstractSAXParser.java:1252)
    at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse (SAXParserImpl.java:643)
    at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryIO$Parser.parse (MetadataRepositoryIO.java:206)
[...]
```

For example in: https://github.com/google/google-java-format/actions/runs/12289067847/job/34293938676

**Comment by cushon** [comment]
I filed https://github.com/eclipse-tycho/tycho/issues/4526 for this against the affected plugin, I hadn't got as far as trying to work around it. Possible setting the system property in the maven JVM flags would work. Another option would be to temporarily disable the Eclipse plugin in the build.

**Comment by cushon** [comment]
It looks like changing the limits in `.mvn/jvm.config` works:

```
-Djdk.xml.maxGeneralEntitySizeLimit=0
-Djdk.xml.totalEntitySizeLimit=0
```

**Comment by phit** [comment]
This is also breaking Google's own Apps Scripts, when using [XmlService](https://developers.google.com/apps-script/reference/xml-service/xml-service#parsexml)

`XmlService.parse('https://about.gitlab.com/all-releases.xml');`

throws

`JAXP00010003: The length of entity "[xml]" is "100,001" that exceeds the "100,000" limit set by "jaxp.properties".`
