### ISSUE TITLE
Discrepancy between versioning scheme in main artifacts and eclipse plugin

### ISSUE THREAD

**Issue by davido** [google/google-java-format#123]
Can we sync the version numbering? in `1.3` release: [1], all artifacts have version `1.3`, whereas the Eclipse plugin uses the numbering with sub-minor 0: `1.3.0`.

* [1] https://github.com/google/google-java-format/releases/tag/google-java-format-1.3

**Comment by cushon** [comment]
The eclipse plugin version can't be `1.3` because that isn't a valid OSGi version. I guess we could use `1.3.0` everywhere. Is this causing problems?

**Comment by davido** [comment]
We have concerns, that diverging the versions could cause confisuion and ends up with wrong code formatted files upload fo review and get merged. We don't have CI job yet tha prevent this from happening.

Yes, the only way to sync it, to move to the new version scheme for main artifacts, this would be great.

**Comment by cushon** [comment]
The last could of releases (`1.10.0`, `1.11.0`) are using the same `major.minor.patch`-style version strings everywhere.
