### ISSUE TITLE
Specification is incomplete

### ISSUE THREAD

**Issue by spy-tech** [google/google-java-format#124]
This is the description of the tool. 
```google-java-format is a program that reformats Java source code to comply with Google Java Style.```

However, when one uses IntelliJ in combination with the plugin as distributed by you, it also reformats XML code in pom files. Please modify the description of the project to specify what the tool does or remove the formatting of XML.

While one could argue that these XML files are part of Java projects (although no such concept exists), one cannot argue that these are "Java source code". 

Indeed, when one searches for "java source file" using your own search engine it says:

```
"A Java class file is a file (with the .class filename extension) containing Java bytecode that can be executed on the Java Virtual Machine (JVM). A Java class file is produced by a Java compiler from Java programming language source files (.java files) containing Java classes."
```

**Comment by cushon** [comment]
My understanding is that the IntelliJ plugin registers `google-java-format` as the formatter for Java code, and IntelliJ continues to use its built-in formatters for all other languages. GJF does not format XML.

**Comment by spy-tech** [comment]
@cushon It appears that you are now saying that it is impossible to tell to IntelliJ to have a plugin which does no work at all when a particular button is pressed; this sounds *highly* unlikely. Just closing this ticket because "your understanding" is not sufficient ground for closing this. Present some evidence as to how this actually works, because clearly the end user behaviour is that pressing the GJF button does something to XML files. 

You are also free to update the documentation saying that this plugin has this particular behaviour. Just closing this is not a solution.

**Comment by cushon** [comment]
https://github.com/google/google-java-format/blob/ec77000a1f33611fcf78e6ca8c8a3a0c90c3d968/idea_plugin/src/com/google/googlejavaformat/intellij/GoogleJavaFormatCodeStyleManager.java#L43-L44

**Comment by spy-tech** [comment]
@cushon Uhm, that's telling that I am right. The plugin doesn't just do the identity function after it has done its Google implemented work. As such the documentation on GitHub is wrong. The documentation in that file is correct.
