### ISSUE TITLE
Use eclipse style sorting order for static imports

### ISSUE THREAD

**Issue by davido** [google/google-java-format#125]
Even though, the ordinal number of capitalized letters is higher than normal letter, the soring order for natural text is usually differs. This is also te default behaviour of sort command in *nices:
   
``` 
      $ cat file
      A
      a
      $ cat file | sort
      a
      A
```

The main reason for changing the sorting behaviour here, to match that for natural language text, is to get exactly the same behaviour as in Eclipse's IDE "Organize Imports" feature.

For more context, see the discussion in: [1], [2].

* [1] https://gerrit-review.googlesource.com/96950
* [2] https://gerrit-review.googlesource.com/97054

**Comment by sormuras** [comment]
Does the natural ordering adhere to https://google.github.io/styleguide/javaguide.html#s3.3.3-import-ordering-and-spacing ?

**Comment by cushon** [comment]
The current behaviour is required by the style guide: https://google.github.io/styleguide/javaguide.html#s3.3.3-import-ordering-and-spacing. There's been some discussion about the merits of Eclipse's approach, but there are currently no plans to change the style guide.

The other difference I'm aware of is that Eclipse groups static imports by class instead of sorting the entire qualified name:

```java
import static a.Foo.FOO;
import static a.Foo.ZOO;
import static a.Foo.SubFoo.BAR;
```

vs.

```java
import static a.Foo.FOO;
import static a.Foo.SubFoo.BAR;
import static a.Foo.ZOO;
```

**Comment by davido** [comment]
> The current behaviour is required by the style guide: https://google.github.io/styleguide/javaguide.html#s3.3.3-import-ordering-and-spacing. There's been some discussion about the merits of Eclipse's approach, but there are currently no plans to change the style guide.

Quoting the spec here:

```
[...]
Within each block the imported names appear in ASCII sort order.
```

Would it be an option to deviate from the spec guarded by an extra option, say `gjf -i -natural-sort-ordering-deviate-from-thespec-i-know-what-i-am-doing Foo.java`, as non working `Ctrl-Shift-O` in Eclipse horribly sucks.

**Comment by cushon** [comment]
The [examples](http://paste.openstack.org/show/598484/) in your second context link are both caused by the different handling of static imports. As far as I can tell Eclipse also uses ASCII order.

How often are you seeing this happen? Internally it affects about one file in six thousand, and we have a pre-commit check to make sure the order is correct. It hasn't been a significant issue in practice.

**Comment by davido** [comment]
Oh, indeed. Thanks for pointing this out. I havn't fully understood the problem. Looking into it now even deeper, it seems to be static import ordering is not fully lexical in Eclipse. See this explanation in upstream issue tracker: [1] and this commit in `checkstyle`  project:[2]. This method seems to do the job: [3].

> How often are you seeing this happen?

It's just these 2 files from 2830 compilation units in gerit Code Review: [4]. Still, would you have a probem to accept a patch, that exposes non documented option: --import-order-eclipse-style short term and try to change the spec and make it the default behaviour mid/long term?

* [1] https://bugs.eclipse.org/bugs/show_bug.cgi?id=473629
* [2] https://github.com/checkstyle/checkstyle/issues/3101
* [3] https://github.com/checkstyle/checkstyle/commit/d8c2a7263ac4fb5b10c7f5959046da87c8ef8efd#diff-93297645ad5963375d99b3225417b450R516
* [4] http://paste.openstack.org/show/598484/

**Comment by davido** [comment]
I added a comment to this Eclipse issue: [1], asking to provide an option in Eclipse to sort static imports in pure ASCII sorting order without container-first-order semantic unconditionally offered by Eclipse.

* [1] https://bugs.eclipse.org/bugs/show_bug.cgi?id=473629

**Comment by davido** [comment]
I just wrote this feature request upstream: [1].

* [1] https://bugs.eclipse.org/bugs/show_bug.cgi?id=512733
