### ISSUE TITLE
Glob support  google-java-format [options] "**/*.java"

### ISSUE THREAD

**Issue by mitermayer** [google/google-java-format#129]
Would be great if we could do something like:

```
 java -jar ~/local/jar/google-java-format-1.3-all-deps.jar --replace "**/*.java"
```

Or something like:

```
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>exec-maven-plugin</artifactId>
        <version>1.5.0</version>
        <executions>
          <execution>
            <goals>
              <goal>java</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <mainClass>com.google.googlejavaformat.java.Main</mainClass>
          <arguments>
            <argument>--replace</argument>
            <argument>src/**/*.java</argument>
          </arguments>
        </configuration>
      </plugin>
```

**Comment by jbduncan** [comment]
Sounds like a good idea to me personally!

In the meantime, running `java -jar google-java-format-1.x-all-deps.jar -i $(find . -type f -name "*.java")` on Cygwin (or presumably any other Unix-like terminal) is a good workaround.

**Comment by sherter** [comment]
Sounds like a bad idea to me. It's the shell's job to do that (at least that's how it works on unix, windows is a different story).
I'd recommend to switch to a shell that supports it (e.g. `zsh` or `bash` with the `globstar` option).

**Comment by f2prateek** [comment]
FWIW that catches ALL java files (including build generated ones) which is a bit unnecessary. I've been filtering with grep for what works with my project layout https://github.com/segmentio/analytics-android/pull/506/files#diff-b67911656ef5d18c4ae36cb6741b7965R14.

**Comment by mitermayer** [comment]
Can always use `find . -type f -path target -prune -o -name '*.java'`

**Comment by natros** [comment]
I'm using this: `-i $(git ls-files|grep \.java$)`

**Comment by PhilippWendler** [comment]
Just put `shopt -s globstar` in your `.bashrc` and `**/*.java` will work just as expected. No need for complicated find commands or adding this to google-java-format

**Comment by cushon** [comment]
Supporting this in the CLI adds complexity, and doesn't seem significantly more useful than using `find` / `git ls-files` / your shell to expand the glob. I think `clang-format` also takes that approach.

**Comment by mitermayer** [comment]
Hi @cushon Thank you for your reply. I understand your concerns.

I think it would be extremely useful to have glob support since that would enable the formatter  to play nicely with maven without having to wrap it on a custom plugin or shell script.

**Comment by av1m** [comment]
I personally use this command, it works on Linux, Windows and MacOS:
`java -jar /pathToJar.jar --replace $(git ls-files *.java)`
