### ISSUE TITLE
Empty line between annotation and member is not removed

### ISSUE THREAD

**Issue by PhilippWendler** [google/google-java-format#13]
The code
```
public class Test {

  @Nullable

  public int f;  

  @Override

  public void m() {}
}
```
is output by google-java-format without changes, but I would expect it to remove the empty lines between the annotations and the members.

**Comment by cushon** [comment]
Yep, that's a bug.

For the annotation we'd prefer this, as long as the entire declaration fits on one line:

```java
@Nullable public int f;  
```
