### ISSUE TITLE
The plugin adds a google-java-format formatter implementation that can be configured in Window > Preferences > Java > Code Style > Formatter > Formatter Implementation

### ISSUE THREAD

**Issue by elharo** [google/google-java-format#134]
There is no such Formatter Implementation preference in Eclipse 4.6:

The plugin adds a google-java-format formatter implementation that can be configured in Window > Preferences > Java > Code Style > Formatter > Formatter Implementation

![image](https://cloud.githubusercontent.com/assets/1005544/23306230/90687c50-fa70-11e6-9238-93d37973999e.png)

**Comment by sormuras** [comment]
Then your Eclipse installation didn't find/load a single "Formatter plugin" on startup.

Did you drop `google-java-format-eclipse-plugin-1.3.0.jar` to your Eclipse dropins folder before launching the IDE?

**Comment by elharo** [comment]
Nope. In that case consider this a bug to expand the documentation to include that step. 

Also, if this is a true Eclipse plugin we should provide an update site and possibly upload it to the Eclipse marketplace.

**Comment by sormuras** [comment]
> Nope. In that case consider this a bug to expand the documentation to include that step.

True. Happy to update the section in README.md if you press the merge button of https://github.com/google/google-java-format/pull/106 ... deal?

Just kidding.

> Also, if this is a true Eclipse plugin we should provide an update site and possibly upload it to the Eclipse marketplace.

That'd perfect!

**Comment by markelliot** [comment]
Adding the plugin jar to dropins and restarting doesn't add the menu option for me. I'm on Eclipse Neon.3. Any suggested debugging steps? (it sounds like all that should be required is to put the jar in the dropins folder and restart Eclipse)

**Comment by sormuras** [comment]
Is there any error log statement in the log files? https://wiki.eclipse.org/FAQ_Where_can_I_find_that_elusive_.log_file%3F

**Comment by sormuras** [comment]
Btw. in fresh Neon.3 installation and a fresh workspace, the dropped-in plugin appears as expected.

Version: Neon.3 Release (4.6.3)
Build id: 20170314-1500

![eclipse-gjf-plugin-neon3](https://cloud.githubusercontent.com/assets/2319838/25120965/53b22868-2420-11e7-82b1-f43bb953af46.PNG)

**Comment by markelliot** [comment]
Thanks. Sorry for the noise: I grabbed a fresh install and things do work just fine.

My existing install, which has been updated from Eclipse Neon (1) remains broken, but I'll just continue with the fresh copy. I do see this in the workspace log:
> !MESSAGE Unable to instantiate formatter extension 'com.google.googlejavaformat.java.GoogleJavaFormatter', returning built-in formatter.

There don't appear to be additional logs or additional details. I don't see any additional details and I poked around/diffed the setups and don't see anything obvious. I also poked around the Eclipse source a bit, I don't see anywhere additional logging might show up, but it does suggest something is weird with the extension point in my upgraded version.

**Comment by revans2** [comment]
I am not able to make this work on the mac at all.  I don't even get an error message.  I did a clean install of eclipse Neon in a clean workspace and nothing.

```
$ ls -lh /Applications/Eclipse.app/Contents/Eclipse/dropins/
total 11784
-rw-r--r--@ 1 revans2  admin   5.8M May  4 10:48 google-java-format-eclipse-plugin-1.3.0.jar
```

Nothing in the logs at all

**Comment by sormuras** [comment]
Does this help? http://stackoverflow.com/a/34333669/1431016

**Comment by revans2** [comment]
@sormuras I tried that too

```
$ ls -l ~/.p2/pool/plugins/google-java-format-eclipse-plugin-1.3.0.jar
-rw-r--r--@ 1 revans2  staff  6032827 May  4 10:58 /Users/revans2/.p2/pool/plugins/google-java-format-eclipse-plugin-1.3.0.jar
```

Still no luck and still no logs

**Comment by BruceZu** [comment]
It does not work in Eclipse IDE for Java Developers
Version: Oxygen Release (4.7.0)
Build id: 20170620-1800

**Comment by sormuras** [comment]
@BruceZu See my answer in #179
