### ISSUE TITLE
IDEA Ultimate 2017.1.1 doesn't show Code menu entry

### ISSUE THREAD

**Issue by erikhuizinga** [google/google-java-format#143]
Google Java Format 1.3 doesn't show up in the Code menu.

As per the readme: after a restart of IntelliJ, you need to manually select `Reformat with google-java-format` once before the `Reformat code` function in the same menu does the correct reformatting. However, the `Reformat with google-java-format` does not show up at all.

Version info:
```
IntelliJ IDEA 2017.1.1
Build #IU-171.4073.35, built on April 6, 2017
JRE: 1.8.0_112-release-736-b16 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.4
```

I noticed some strange behaviour once, which may be unrelated so a different issue may have to be opened:
I reformatted my code and it went from Google Java Format to the default IntelliJ format (easy to see, as it indents with 4 instead of 2 spaces). So, I tried to reformat using GJF, but the option wasn't in the Code menu. Looking into the settings, the plugin (v1.3) was installed, but disabled in the plugin settings. Enabling did not add the GJF option in the Code menu, but reformatting the code did apply GJF!

Another issue, that may again be unrelated (so feel free to open a third issue):
A thread with lambda isn't indented properly, e.g.:

```
public class A { // Zero indentation: ok
  void doThreadedStuff() { // Two spaces: ok
    new Thread( // Four spaces: ok
            () -> { // Twelve spaces!!! Not ok
              // Do stuff // Fourteen spaces, which is two more than the previous line: ok
            }) // Twelve spaces again... Not ok
        .start(); // Eight spaces, four more than the 'new Thread(' level: not ok. Also, this line is on the next line, while it could perfectly fit on the previous, but that may be a different discussion
  } // Two spaces: ok
} // Zero spaces: ok
```

Is this the intended behaviour and does that have anything to do with possible issues described above?

**Comment by erikhuizinga** [comment]
Concerning the last issue (with the `new Thread(...).start();` example), I believe that the behaviour is as intended. However, it looks rather strange when the block of code in the thread's lambda is long.

If the `.start();` suffix wouldn't be placed on the next line, but instead appended to the `})` line (which really doesn't need its own line, does it?), then the entire `() -> {...}).start();` block could be indented by 4 less spaces. That saves quite a lot of whitespace while remaining understandable.

On the other hand, I do understand why the `.start();` suffix deserves to be on its own line, but in this particular example the form suffers from the desired function.

**Comment by erikhuizinga** [comment]
By the way: I have the currently latest release of the [Google Java Checkstyle](https://github.com/checkstyle/checkstyle/blob/checkstyle-7.6.1/src/main/resources/google_checks.xml) applied to my IDE and it warns in these `Thread(...).start();` blocks that the indentation level should be 4 less.

**Comment by erikhuizinga** [comment]
By splitting the `new Thread(...).start();` example into variable declaration and method call, the problem is solved. After applying GJF, the code looks like this, which is much more logical:
```
public class A { // Zero indentation: ok
  void doThreadedStuff() { // Two spaces: ok
    Thread thread = // Four spaces: ok
        new Thread( // Eight spaces: ok
            () -> { // Twelve spaces: ok
              // Do stuff // Fourteen spaces: ok
            }); // Twelve spaces: ok
    thread.start(); // Four spaces: ok
  } // Two spaces: ok
} // Zero spaces: ok
```

**Comment by erikhuizinga** [comment]
On the original issue:
After a restart of IDEA, the reformat code action does not reformat according to GJF (as expected). Howerver, I cannot force GJF to be used through the Code menu, because the GJF item is missing (as described). I managed to find out how to enable GJF: open IntelliJ Settings > Other settings > GJF settings. There, do:

1. Uncheck 'Enable GJF'
2. Apply settings
3. Check 'Enable GJF'
4. Apply settings

Now, the regular reformat code action performs the GJF reformat.

This is a workaround and should not be necessary.

**Comment by nobeh** [comment]
I confirm to do the same sequence to get GJF as the default formatter on a fresh start IJ 2017.1.

**Comment by rmcloughlin** [comment]
This sequence works but I have to do it every time I launch IntelliJ.

**Comment by hoangtungdinh** [comment]
Another way to workaround is to reinstall GJF 1.0. 

You can download it [here](https://plugins.jetbrains.com/plugin/8527-google-java-format). Then go to Preferences -> Plugins -> Install plugin from disk.

**Comment by boswelja** [comment]
Same issue here, running IntelliJ 2017.1.1 on windows 10 with plugin version 1.3. Option appears when using version 1.0

**Comment by plumpy** [comment]
Sorry about that! I uploaded version 1.3.1 which fixes the issue.

**Comment by dlime** [comment]
I can't still see "Format with google java format" entry with IDEA 2017.1

Not a big issue for me, since I can use the plugin with default IDEA Code->Reformat code, but it should be mentioned in the readme

**Comment by plumpy** [comment]
Yeah, "format with google java format" was removed in favor of a more standard panel in the settings page. I don't see it mentioned in the readme. Can you tell me where you're seeing it?
