### ISSUE TITLE
IntelliJ plugin 1.3: formatter does not stay enabled across restarts

### ISSUE THREAD

**Issue by olim7t** [google/google-java-format#144]
When the formatter is first enabled (as explained in the readme: "File→Settings...→google-java-format Settings" and check the "Enable" checkbox), it works fine.

But if you restart IntelliJ, it's not enabled anymore. The previous IntelliJ settings take over (I can see it with single-line javadocs like `/** test */ `, that my former settings put on multiple lines).

If you go back to the settings, the checkbox is still checked. You have to uncheck, apply, recheck and apply again.

With previous versions of the plugin, you had to re-enable the plugin after each restart too, but there was a "Code→Reformat with google-java-format" menu item that made it more convenient.

IntelliJ IDEA 2016.3.5
Build #IC-163.13906.18, built on March 6, 2017
JRE: 1.8.0_112-release-408-b6 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Comment by olim7t** [comment]
:man_facepalming: this is already mentioned in #143, I should have read the whole comments before filing this. Sorry.

**Comment by erikhuizinga** [comment]
Also note that it is a known incompatibility between GJF and IDEA, as stated in this repo's README. Google has opened an issue about this at JetBrains: https://intellij-support.jetbrains.com/hc/en-us/community/posts/206757245-Delegating-formatting-to-an-external-formatter
