### ISSUE TITLE
Intellij Plugin Code Style for Java No Google Formatter Option

### ISSUE THREAD

**Issue by britztopher** [google/google-java-format#151]
So I installed plugin and enabled it within intellij, however, I cannot seem to select the google formatter under Editor --> Code Style --> Java --> Java Scheme Dropdown.  Since the readme is pretty unclear whats `supposed` to happen or steps to install I am in the dark here.  I could use some light on the setup process, or this is an issue with intellij:

IntelliJ IDEA 2016.2.4
Build #IU-162.2032.8, built on September 9, 2016
JRE: 1.8.0_112-release-b343 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Comment by tinder-dthomson** [comment]
@britztopher The plugin will work without it being set as a "Code Style", but it's quite annoying to have to always override the editor warnings that you're not using the appropriate formatting because this plugin doesn't integrate properly with IntelliJ.

+1

**Comment by plumpy** [comment]
Unfortunately, IntelliJ (unlike Eclipse) doesn't offer an option for pluggable code formatters, so this is the best we can do. :(

The readme does have an "IntelliJ" section which I think is pretty clear on how to enable it. Perhaps you missed it? Let me know if you think it could be clarified more.
