### ISSUE TITLE
short enums are mistakenly given newlines

### ISSUE THREAD

**Issue by novalis** [google/google-java-format#156]
https://google.github.io/styleguide/javaguide.html#s4.8.1-enum-classes permits private enum Suit { CLUBS, HEARTS, SPADES, DIAMONDS }, but google-java-format reformats it to contain newlines.

**Comment by kevinb9n** [comment]
Of course, the style guide permits the formatter to choose either formatting.

In this case, I have a special concern, which is that many enum constants deserve explanatory javadoc - many more than actually get it. I worry that supporting the terse formatting will just discourage such javadoc even more. Of course, I am not denying that cases exist where the doc is unnecessary and the single-line format is "nice".
