### ISSUE TITLE
Incorrect formatting for long annotations

### ISSUE THREAD

**Issue by vgarg** [google/google-java-format#159]
In case of long annotations e.g.

`@Bean(with="foo", many="bar", arguments="baz", so={"that", "this", "line", "is", "long"})
`

The formatter automatically line wraps it as:

```
@Bean(
  with = "foo",
  many = "bar",
  arguments = "baz",
  so = {"that", "this", "line", "is", "long"}
)
```
The issue is that the wrapped lines are indented using 2 spaces instead of 4 as described in the Google Java Styles: 
`When line-wrapping, each line after the first (each continuation line) is indented at least +4 from the original line`

This conflicts with CheckStyle plugin that we use as part of our Maven build. CheckStyle complains: `'with' has incorrect indentation level 2, expected level should be 4. (16:0)`

**Comment by kevinb9n** [comment]
You're right, this conflict exists, and we have been needing to sort it out. In the meantime I would highly recommend relaxing the lint check to tolerate this.

**Comment by vgarg** [comment]
Thanks @kevinb9n . We will work around for now. Any projection on when it may be fixed e.g. days, weeks, months etc.?

**Comment by medvedev** [comment]
No need to have multiple parameters to reproduce this issue.
You may have only one.
```
@Parent(
  params = {
    @Child(value = "Let's put here a really long string to demonstrate the issue. Really long.")
  }
)
public class Test {}
```

**Comment by jasonzhao3** [comment]
+1 we're bitten by this as well >_<

**Comment by gitorko** [comment]
+1

**Comment by stv8** [comment]
Also being affected by this one, I'm using `google_checks.xml` how do I relax the linting?

**Comment by stv8** [comment]
@vgarg What was your solution to relaxing the lint?

**Comment by rafaeljcg** [comment]
Is this issue fixed? I'm still seeing inconsistencies in the following scenario:
```java
@Parent({
  @Child(value = "Let's put here a really long string to demonstrate the issue. Really long.")
})
public class Test {}
```
`'@' has incorrect indentation level 2, expected level should be 4.`

---

This is formatted correctly, though:
```java
@Parent(
    value = {
      @Child(value = "Let's put here a really long string to demonstrate the issue. Really long.")
    })
public class Test {}
```

**Comment by cushon** [comment]
@rafaeljcg those formattings are correct and should not result in a warning. I filed a bug against checkstyle: checkstyle/checkstyle#5951
