### ISSUE TITLE
IntelliJ - compatibility with other plugins

### ISSUE THREAD

**Issue by krasa** [google/google-java-format#160]
There are already at least 2 other plugins (https://github.com/krasa/EclipseCodeFormatter and https://github.com/bazelbuild/intellij) which override CodeStyleManager. 

com.google.googlejavaformat.intellij.GoogleJavaFormatInstaller#removeFormatter will not work unless you can guarantee that your plugin will be initialized as the last - which you can't afaik.

**Comment by plumpy** [comment]
Hm, interesting, the bazelbuild plugin is also written by my team at Google, but internally we use slightly modified versions of these plugins and they don't have any issues. I'll take a look and try to figure out what's going on with the open source versions. Thanks!

**Comment by plumpy** [comment]
(see also bazelbuild/intellij#92)

**Comment by plumpy** [comment]
We don't remove the formatter anymore, so I think this issue is obsolete.
