### ISSUE TITLE
Assertion Error "did not generate token "Object""

### ISSUE THREAD

**Issue by tomac120** [google/google-java-format#165]
> Exception in thread "main" java.lang.AssertionError: <stdin>:13:1: error: did not generate token "Object"
> 	at com.google.googlejavaformat.OpsBuilder.sync(OpsBuilder.java:188)
> 	at com.google.googlejavaformat.java.JavaInputAstVisitor.sync(JavaInputAstVisitor.java:3408)
> 	at com.google.googlejavaformat.java.JavaInputAstVisitor.visit(JavaInputAstVisitor.java:1256)
> 	at org.eclipse.jdt.core.dom.MethodDeclaration.accept0(MethodDeclaration.java:611)
> 	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2711)
> 	at com.google.googlejavaformat.java.JavaInputAstVisitor.addBodyDeclarations(JavaInputAstVisitor.java:3261)
> 	at com.google.googlejavaformat.java.JavaInputAstVisitor.visit(JavaInputAstVisitor.java:1908)
> 	at org.eclipse.jdt.core.dom.TypeDeclaration.accept0(TypeDeclaration.java:453)
> 	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2711)
> 	at com.google.googlejavaformat.java.JavaInputAstVisitor.visit(JavaInputAstVisitor.java:392)
> 	at com.google.googlejavaformat.java.Formatter.format(Formatter.java:125)
> 	at com.google.googlejavaformat.java.Formatter.formatSource(Formatter.java:157)

Source that caused this is attached. The error which they have is "abstract method can't have a body". Of course, this should be a regular FormatterException and not an assertion error, possibly formatted with proper message.

[1.txt](https://github.com/google/google-java-format/files/1066028/1.txt)

**Comment by tomac120** [comment]
The exception appears to happen on the first function in the attached AAA class. If that is removed, the output is an IllegalArgumentException.

> Exception in thread "main" java.lang.IllegalArgumentException
> 	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:108)
> 	at com.google.googlejavaformat.FormatterDiagnostic.<init>(FormatterDiagnostic.java:27)
> 	at com.google.googlejavaformat.Input.createDiagnostic(Input.java:139)
> 	at com.google.googlejavaformat.OpsBuilder.sync(OpsBuilder.java:185)
> 	at com.google.googlejavaformat.java.Formatter.format(Formatter.java:126)
> 	at com.google.googlejavaformat.java.Formatter.formatSource(Formatter.java:157)

**Comment by cushon** [comment]
From the stack trace it looks like you're using an old version of the formatter. This doesn't reproduce with never versions:

```java
package com.project;

public abstract class AAA {

  public abstract Object authenticate(R env, Object... args) {
    Object service = args[0];

    return null;
  }

  public abstract Object sign(R env, Object... args) {
    Object request = args[0];

    return null;
  }
}
```
