### ISSUE TITLE
Incompatile with Intellij IDEA 2017.2

### ISSUE THREAD

**Issue by hadix-lin** [google/google-java-format#167]
<img width="580" alt="wx20170719-083421 2x" src="https://user-images.githubusercontent.com/1037389/28345457-2e25aed2-6c5d-11e7-894e-540c0a390519.png">

**Comment by hadix-lin** [comment]
The plugin is very helpful for me. please support it ,please , please ,please .

**Comment by tbroyer** [comment]
After the upgrade to 2017.2, IntelliJ proposed me to downgrade the plugin from 1.3.1 to 1.3, and indeed 1.3.1 is only compatible with 2017.1 (build 171.*): https://plugins.jetbrains.com/plugin/8527-google-java-format

(though this is apparently done on purpose: https://github.com/google/google-java-format/commit/aca5a774085a7436b3612dc47a50922bf1ea0b7c#diff-a61b83580221dcf0d00e35f4c33c767bR18)

**Comment by ignacio83** [comment]
+1

**Comment by plumpy** [comment]
Sorry for the delay, but we're doing strange things using unsupported features of the IDE libraries, so it breaks with every new release (which I why I marked it compatible only with 2017.1). But I should be able to get a 2017.2-compatible version up next week. Thanks for your patience!

**Comment by dhalperi** [comment]
Shipping a new release that works with 2017.2 would be really swell: the fix from https://github.com/google/google-java-format/pull/153 is really crucial – the plugin isn't enabled by default!

Anything I can do to help?

**Comment by plumpy** [comment]
Okay, I uploaded a new version 1.3.2 which will work with 2017.2.

I didn't put an until-build on it. There will definitely be some issues with 2017.3, as they continue to modify the code style classes with every version, but I suppose some minor issues are better than just not being able to install it at all. Thanks for your patience.

**Comment by dhalperi** [comment]
Thanks @plumpy !

**Comment by hadix-lin** [comment]
Thannks.
