### ISSUE TITLE
Will use of `googleJavaFormat` format the code with different spaces in Linux and Windows?

### ISSUE THREAD

**Issue by Priya1803** [google/google-java-format#172]
We are using `spotlessJava` gradle plugin with googleJavaFormat() to format our Java code and use `gradlew spotlessApply` to apply the plugin. We have developers working on Linux machine and others working on Windows 10.

**ISSUE**
When applying the `spotlessApply` plugin we could see difference in files getting formatted in Linux machine and in Windows machine.

For.e.g, the space from left margin would nearly be 2 spaces in files that we formatted in Linux, but while using the same file in Windows we have that with 1 tab space.

**QUERY**
Would Linux or Windows really make difference for the above formatting issue or do we need to look into what we are missing?

**Comment by cushon** [comment]
The formatting behaviour should be the same on linux and windows, and the formatter never uses tabs, so this may be an issue with spotless (which is a separate project: https://github.com/diffplug/spotless).

Can you try downloading the CLI to see if has the same behaviour for the affected file on linux and windows? https://github.com/google/google-java-format#from-the-command-line
