### ISSUE TITLE
Array initializer whitespace

### ISSUE THREAD

**Issue by metacubed** [google/google-java-format#174]
According to the [horizontal whitespace guidelines](https://google.github.io/styleguide/javaguide.html#s4.6.2-horizontal-whitespace), spaces within array initializer braces are optional (see point 8). The plugin however always removes these spaces.

So `{ 1, 2 }` becomes `{1, 2}` even though it is not required by the guidelines.

**Comment by eaftan** [comment]
We have an internal FAQ entry on this, which maybe we should externalize.  The TL;DR is that g-j-f does not attempt to maintain existing formatting, but purposely ignores existing choices.  Its goal is not just to correct mistakes; it is to free developers from having to make formatting decisions in the first place, bringing greater consistency to your codebase.

**Comment by metacubed** [comment]
Thanks for the clarification, @eaftan.
