### ISSUE TITLE
Does the formatter normalize its input?

### ISSUE THREAD

**Issue by ekuefler** [google/google-java-format#18]
In other words, if I insert/remove arbitrary whitespace before running the formatter, will I always get the same output? Or are there some things like line wrappings that the formatter will preserve if encountered but not insert itself? I haven't decided which approach I'd prefer but I'm sure you've thought about it.

**Comment by sherter** [comment]
To answer your question: No, it does not normalize the input. One example I know of is that line breaks at the beginning of a file are kept:

```java



package foo;


class Foo {
}
```
becomes

```java



package foo;

class Foo {}
```

It _should_ be idempotent though. Running the formatter once or multiple times doesn't make a difference.

**Comment by cushon** [comment]
The standard example where the input isn't normalized is blank lines between statements, which the style guide allows to "create logical groupings of statements". The formatter is never going to be able to make that decision, so it has to preserve existing blank lines between statements.

There are some more obscure examples, like whitespace around inline block comments, and paired method arguments.

Preserving leading blank lines is not deliberate, I filed #22 for that.

**Comment by ekuefler** [comment]
Thanks. It's too bad that it can't make formatting totally objective, but I agree that's probably an impossible (or at least not a desirable) goal.
