### ISSUE TITLE
TODO style comments in 1.4

### ISSUE THREAD

**Issue by posto** [google/google-java-format#186]
TODO comments are usually handled in the IDE in a special way. IntelliJ IDEA shows them in a different color and has a [TODO Tab](https://www.jetbrains.com/help/idea/using-todo.html) where they are listed.

Release 1.4 introduces wrapping of comments and this results in TODO elements being cut and the highlighting being broken.
<img width="756" alt="screen shot 2017-09-07 at 11 52 52" src="https://user-images.githubusercontent.com/899189/30157635-1ec2846e-93c3-11e7-881e-4201f0c4de96.png">

Consider excluding comments starting with `TODO` from the wrapping logic. The extra space after `//` is helpful, though.

**Comment by jbduncan** [comment]
@posto What would happen for TODO comments that are so large that they naturally span two or more lines worth of text in an editor/environment that forces a maximum of 80 or 100 character per line? 🤔

**Comment by jbduncan** [comment]
@posto I ask as such TODO comments would IMO be significantly harder to read (spilling over the edge of the screen/editor) if they were all concatenated as single lines.

**Comment by jbduncan** [comment]
And I'd personally argue that if a full TODO comment cannot be rendered in IntelliJ's or other IDEs' TODO tabs, then it doesn't stop developers from clicking on the TODO comment and navigating to the source code to see the full TODO message.

**Comment by posto** [comment]
I guess one can adapt the style of writing when the TODO line is too long and just use it as a "subject" with the content following below.

```
// TODO: stardate logging
// Add support for logging the stardate for the future generation
// Lorem ipsum bla bla
```
