### ISSUE TITLE
Versioning in GoogleJavaFormatVersion.java does not reflect real version.

### ISSUE THREAD

**Issue by MichaelStergianis** [google/google-java-format#188]
In commit [833201c](https://github.com/google/google-java-format/commit/833201c903f90d272989198f197b106c7a14fea3) the version was changed to 1.0 and has been static since then. This seems a bit odd with version 1.4 being released afterwards. If it needs to be this way for the intellij plugin to function, that is fine. But I thought it should be brought to your attention.

Sincerely,
Michael Stergianis

**Comment by sormuras** [comment]
https://github.com/google/google-java-format/pull/183 addresses this by setting it to `1.5-SNAPSHOT` for master.

**Comment by cushon** [comment]
I merged #183. Thanks @sormuras!

I added a reminder to update it for the next release. It'd be nice to make it more automatic.

**Comment by sormuras** [comment]
You're welcome @cushon!
