### ISSUE TITLE
Eclipse plugin build failed

### ISSUE THREAD

**Issue by MaLars73** [google/google-java-format#190]
When building the eclipse formatter I get compilation errors saying...
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:0.26.0:compile (default-compile) on project google-java-format-eclipse-plugin: Compilation failure: Compilation failure:
[ERROR] C:\src\google-java-format\eclipse_plugin\src\com\google\googlejavaformat\java\GoogleJavaFormatter.java:[19]
[ERROR]         import com.google.googlejavaformat.java.SnippetFormatter.SnippetKind;
[ERROR]                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] The import com.google.googlejavaformat.java.SnippetFormatter cannot be resolved

This is after I update the plugin's pom.xml to point to parent and core version 1.5-SNAPSHOT.

I just clone, update version in pom.xml and build.
What am I missing?

/Mathias

**Comment by sormuras** [comment]
You to update https://github.com/google/google-java-format/blob/master/eclipse_plugin/build.properties as well. I couldn't find an easy way to automate this.

**Comment by MaLars73** [comment]
Thanks for a swift response.
Didn't help though. I still get the same error.

**Comment by MaLars73** [comment]
I needed to update MANIFEST.MF also.
Now it passes compile.

Instead in fails with this message.
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-packaging-plugin:0.26.0:package-plugin (default-package-plugin) on project google-java-format-eclipse-plugin: C:\src\google-java-format\eclipse_plugin\build.properties: bin.includes value(s) [lib/javac-9-dev-r3297-1-shaded.jar] do not match any files. -> [Help 1]

**Comment by sormuras** [comment]
Update to the version used in the parent pom: 9-dev-r4023-3

**Comment by sormuras** [comment]
See this branch for changes I made to make it build: https://github.com/google/google-java-format/compare/master...sormuras:update-eclipse-plugin-to-1.5

I omitted the module activation from the parent pom.xml -- this should not go into the master branch:

```
  <modules>
    <module>core</module>
    <module>eclipse_plugin</module>
    <!-- google-java-format#24
    <module>idea_plugin</module>
    -->
  </modules>
```

**Comment by MaLars73** [comment]
Thanks!

I updated build.properties and MANIFEST.MF to point to ./lib/javac-shaded-9-dev-r4023-3.jar

Now it builds. :-)
