### ISSUE TITLE
No google-java-format-eclipse-plugin-1.4.0.jar on releases page

### ISSUE THREAD

**Issue by arifogel** [google/google-java-format#192]
I want to use the new formatter version in Eclipse, but there is no release jar for the plugin.

**Comment by Systemfreakz** [comment]
Yes guys, please ensure that you also make a version for eclipse available upon a new release. Otherwise, this release is basically useless for any team that uses more IDEs than just IntelliJ. Thanks

**Comment by BruceZu** [comment]
Half of our team use Eclipse and half use IntelliJ IDEA. We need to keep a consistent code format. 
Please publish google-java-format-eclipse-plugin-1.4.0.jar

**Comment by BruceZu** [comment]
Any feedback on the reason or plan? Thank you!

**Comment by cushon** [comment]
done: https://github.com/google/google-java-format/releases/download/google-java-format-1.4/google-java-format-eclipse-plugin_1.4.0.jar
