### ISSUE TITLE
short Javadoc in basic form with block tag gets formatted to single-line form

### ISSUE THREAD

**Issue by tbcs** [google/google-java-format#193]
This behavior violates [§7.1.1](https://google.github.io/styleguide/javaguide.html#s7.1.1-javadoc-multi-line) of the style guide.

How to reproduce:
```
$ cat Customer.java
interface Customer {
  /**
   * @return the customer ID
   */
  int getId();
}
$ java -jar google-java-format-1.4-all-deps.jar Customer.java
interface Customer {
  /** @return the customer ID */
  int getId();
}
```

This issue has been brought up before in #117.

**Comment by cushon** [comment]
The summary fragment is required: https://google.github.io/styleguide/javaguide.html#s7.2-summary-fragment, so that example is already in violation of the style guide.

**Comment by tbcs** [comment]
@cushon: Indeed.  I don't understand how I managed to overlook that.  After a few days of using the Google style it's quite obvious that the above snippet does not conform.  Sorry for the confusion, this issue can be closed.
