### ISSUE TITLE
Doing nothing in latest IntelliJ IDEA

### ISSUE THREAD

**Issue by lovek323** [google/google-java-format#196]
Just installed the plugin in the latest IntelliJ IDEA, but it doesn't seem to be formatting the code properly (e.g., imports aren't split into the correct groups).

![image](https://user-images.githubusercontent.com/265084/30943181-7b214418-a42e-11e7-9bbb-cbf743e0a59c.png)

I believe that I've enabled it correctly. What should be happening?

Looks like it does the same thing when I run the JAR manually. Am I expecting it to do something it won't do?

Imports after formatting:

```java
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonNode;
// com.mycompany.etc
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
```

**Comment by lovek323** [comment]
Looks like Google's changed the way imports work in their style or they've never worked the way I think they do. Perhaps the checkstyle plugin I'm using has an old version of google's style. Anyway, I'm closing this because I think it's working as intended.

**Comment by plumpy** [comment]
Your memory is correct. They used to be grouped by domain name, but that was changed to the current simplified ordering about a year ago.
