### ISSUE TITLE
Eclipse plugin does not work with Eclipse Neon3

### ISSUE THREAD

**Issue by epk-malars** [google/google-java-format#197]
After copying the eclipse plugin jar (built from the latest commit) to the eclipse/dropins folder, and restarting.
The Formatter implementation dropdown isn't displayed.
The same jar works for eclipse oxygen.
If I put another formatter jar into the dropins folder of Neon, the Formatter implementation dropdown is displayed.

Any tips would be geately appreciated.

**Comment by cushon** [comment]
Do you still see this issue with the latest version of the plugin?
https://github.com/google/google-java-format/releases/download/google-java-format-1.4/google-java-format-eclipse-plugin_1.4.0.jar

**Comment by cushon** [comment]
Tentatively resolving.
