### ISSUE TITLE
Rectangle rule indents lambdas 8 extra columns

### ISSUE THREAD

**Issue by swankjesse** [google/google-java-format#2]
Before: code in lambda is indented +2:

```
    transacter.executeWithRetries(session -> {
      boolean authenticated = appAuthenticator.isAuthenticated(session, appAuthorization);
      if (!authenticated) {
        logger.info("signOutApp failed for [appToken=%s]", appAuthorization.appToken);
        throw CashApiException.unauthorized();
      }
      appAuthenticator.revokeSession(session, appAuthorization.appToken, false);
    });
```

After: code in lambda is indented +10:
```
    transacter.executeWithRetries(
        session
            -> {
              boolean authenticated = appAuthenticator.isAuthenticated(session, appAuthorization);
              if (!authenticated) {
                logger.info("signOutApp failed for [appToken=%s]", appAuthorization.appToken);
                throw CashApiException.unauthorized();
              }
              appAuthenticator.revokeSession(session, appAuthorization.appToken, false);
            });
```

I think it's consistent with the rule, but this case seemed particularly harsh.

**Comment by cushon** [comment]
I think that breaking before `->` is a bug. Fixing that would make it a little better:

```
    transacter.executeWithRetries(
        session -> {
          boolean authenticated = appAuthenticator.isAuthenticated(session, appAuthorization);
          if (!authenticated) {
            logger.info("signOutApp failed for [appToken=%s]", appAuthorization.appToken);
            throw CashApiException.unauthorized();
          }
          appAuthenticator.revokeSession(session, appAuthorization.appToken, false);
        });
```

**Comment by kevinb9n** [comment]
Roughly, I would say:

When a lambda is using in-line presentation, then -> is like a binary
operator.
When a lambda is using block presentation, then the `(params) -> {` part
ought to bind more tightly together than we see here.


On Fri, May 15, 2015 at 8:47 AM, Liam Miller-Cushon <
notifications@github.com> wrote:

> I think that breaking before -> is a bug. Fixing that would make it a
> little better:
>
>     transacter.executeWithRetries(
>         session -> {
>           boolean authenticated = appAuthenticator.isAuthenticated(session, appAuthorization);
>           if (!authenticated) {
>             logger.info("signOutApp failed for [appToken=%s]", appAuthorization.appToken);
>             throw CashApiException.unauthorized();
>           }
>           appAuthenticator.revokeSession(session, appAuthorization.appToken, false);
>         });
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/google-java-format/issues/2#issuecomment-102442229>
> .
>



-- 
Kevin Bourrillion | Java Librarian | Google, Inc. | kevinb@google.com
