### ISSUE TITLE
Provide an artifact that shades or omits Guava and other dependencies

### ISSUE THREAD

**Issue by cpovirk** [google/google-java-format#20]
As noted in https://github.com/google/dagger/issues/228#issuecomment-171242072 and the comment it replies to, the `google-java-format` jar contains classes from Guava and other dependencies. Those classes end up in Dagger, where they conflict with the version of Guava used by Dagger -- and, because of Maven's lack of support for `-processorpath`, with the version of Guava used by Dagger *users* like Caliper.

I don't know enough about Maven to say what the right thing here is. The easiest thing, I'd guess, is shading, but for all I know, this may be difficult with the Eclipse classes for some reason.

**Comment by cjp39** [comment]
Why does the JAR include its dependencies at all? That's not the way JARs usually work. If it is necessary, can you create a new JAR, `google-java-format-all` for instance, that can be used stand-alone?

**Comment by cjp39** [comment]
Incidentally, FreeBuilder uses google-java-format without issue, because it does its own shading; there's no reason Dagger can't do the same, beyond the effort involved. But this issue should still be fixed, because otherwise processorpath ordering can silently downgrade Guava for your users.

**Comment by ronshapiro** [comment]
It doesn't include the dependencies, but the `pom.xml` references Guava 18.0.

**Comment by ronshapiro** [comment]
@cpovirk [[maven doc]](https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Transitive_Dependencies) It's not the easiest to read (so much xml to parse...) but it seems like you can force a version to be used via the parent pom.xml's `<dependencyManagement>` section.

**Comment by tbroyer** [comment]
@ronshapiro Yes it does! (note: the maven-shade-plugin is declared in the parent POM)

```
wget -O google-java-format.jar https://search.maven.org/remotecontent?filepath=com/google/googlejavaformat/google-java-format/0.1-alpha/google-java-format-0.1-alpha.jar
jar -tf google-java-format.jar
```

**Comment by ronshapiro** [comment]
Ah, my mistake, I was looking at -sources.jar. Thanks @tbroyer for the correction

**Comment by cushon** [comment]
The fat jar was supposed to be for command line use, I agree it's a bad idea for the artifact we publish to maven.

(And I updated google-java-format to use guava 19.)

**Comment by tbroyer** [comment]
Use maven-assembly-plugin then to publish an all-deps jar as an attached artifact?

**Comment by cushon** [comment]
Any concerns with #21?

**Comment by tbroyer** [comment]
Can this be released?
