### ISSUE TITLE
GJF rewrites IntelliJ / Android Lint noinspection suppressions

### ISSUE THREAD

**Issue by msridhar** [google/google-java-format#202]
Both IntelliJ and Android Lint support doing warning suppressions on a single line with a `//noinspection` comment, e.g.:
```java
//noinspection CheckResult
methodWhoseResultShouldBeChecked();
```
We have many such suppressions in our code base.  GJF rewrites 
`//noinspection` to `// noinspection` and unfortunately Android Lint does not recognize the suppression after the rewrite.  Even with Java 8 there is no built-in suppression mechanism that can be applied to any arbitrary line of code, so I don't see a great alternative here.

The Google Java style guide seems [fairly clear](https://google.github.io/styleguide/javaguide.html#s4.8.6-comments) that there should be a space after `//` comments.  But is it possible an exception could be made here?  If not, are there any suggested workarounds?

**Comment by cushon** [comment]
> But is it possible an exception could be made here?

I think so, thanks for raising this. I don't see a good alternative either, and preserving existing style errors (especially in comments) is different than actively introducing new ones.

**Comment by cushon** [comment]
Sorry, I should have mentioned that I have a change out for internal review already. It'll show up on github in the next day or so.

**Comment by msridhar** [comment]
Ah, ok, cool!  Will close my PR then.
