### ISSUE TITLE
Formatting of single line `if` inconsistent with style guide?

### ISSUE THREAD

**Issue by msridhar** [google/google-java-format#204]
Regarding `if` statements and braces, the [Google Java Style Guide](https://google.github.io/styleguide/javaguide.html#s4.1-braces) states: "Braces are used with `if`, `else`, `for`, `do` and `while` statements, even when the body is empty or contains only a single statement."  But AFAICT, no braces get introduced by GJF for this code:
```java
if (cond) return val;
```
Is this an inconsistency?  Or am I misreading something?

**Comment by sherter** [comment]
duplicate of #51

**Comment by msridhar** [comment]
Ah ok, sorry for the dup
