### ISSUE TITLE
Unable to trigger formatting with IntelliJ Plugin (2017.2.5)

### ISSUE THREAD

**Issue by euclio** [google/google-java-format#207]
I have installed and enabled the plugin, but I am unable to actually format my code.

I tried Ctrl+Shift+A and searching "Reformat with google-java-format" but I don't have the option.

**Comment by plumpy** [comment]
Where did you find those instructions? Those are for old versions of the plugin. The README.md has the correct instructions.

**Comment by plumpy** [comment]
(But I'd appreciate it if you could tell me where you found the old instructions so I can update them.)

**Comment by euclio** [comment]
Thanks for the quick response. I found the instructions [on StackOverflow](https://stackoverflow.com/questions/42979700/how-to-configure-google-java-code-formatter-in-intellij-idea-17/42979701).

I guess I'm unclear on how to actually trigger the plugin then. Does it work on save? I think the README could benefit from a little more explanation (which is why I went searching elsewhere in the first place).

**Comment by plumpy** [comment]
It works in place of the normal "reformat code" action. So ctrl-alt-L by default or Code→Reformat Code.

I'll update the readme to mention this. Thanks for bringing it up.

**Comment by plumpy** [comment]
Okay, I submitted an update to the docs, so I'm going to close this. The commit should make its way out to Github soon. Thanks for bringing this to my attention!

I added this:
When enabled, it will replace the normal "Refomat Code" action, which can be
triggered from the "Code" menu or with the Ctrl-Alt-L (by default) keyboard
shortcut.
