### ISSUE TITLE
it's not support for Idea2017.2

### ISSUE THREAD

**Issue by yeleafly** [google/google-java-format#212]
it's not support for Idea2017.2

**Comment by sormuras** [comment]
Just tested the GJF plugin with **2017.2.5** and **2017.3-EAP**. Works like a charm.

Follow the (recently updated) instructions from the main `README.md`:

> The plugin will not be enabled by default. To enable it in the current project, go to "File→Settings...→google-java-format Settings" and check the "Enable" checkbox.
> 
> To enable it by default in new projects, use "File→Other Settings→Default Settings...".

https://github.com/google/google-java-format#intellij

**Comment by plumpy** [comment]
Yeah, it definitely should be supported. Please feel free to reopen it if you can provide more details of what's not working for you, but without any more details, there's not much I can do to help you.
