### ISSUE TITLE
Release new gjf version

### ISSUE THREAD

**Issue by davido** [google/google-java-format#214]
With [--dry-run](https://github.com/google/google-java-format/pull/106) option the major FR was implemented. For all projects that depend on the gjf fork it's time to switch using upstream. Please, release a new version ASAP.

**Comment by sormuras** [comment]
Looking forward to the 1.5 release, too. #213 might be a show-stopper for some days, though.

Just for the record -- if you want to test-drive your project using latest SNAPSHOT version of gjf, you can depend on these [jitpack ](https://jitpack.io) coordinates:

- group: `com.github.google.google-java-format`
- artifact: `google-java-format`
- version: `master-SNAPSHOT`

### Gradle

`compile('com.github.google.google-java-format:google-java-format:master-SNAPSHOT')`

### JitPack Build Log
https://jitpack.io/com/github/google/google-java-format/master-SNAPSHOT/build.log

### All-Deps JAR
[google-java-format-master-SNAPSHOT-all-deps.jar](https://jitpack.io/com/github/google/google-java-format/google-java-format/master-SNAPSHOT/google-java-format-master-SNAPSHOT-all-deps.jar)

**Comment by cushon** [comment]
I'll take care of #213 and then push a release next week.

**Comment by novalis** [comment]
#211 is a showstopper for us.

**Comment by cushon** [comment]
#213 was resolved in 352aac773940c27d14fb06069dcb367b376b28be.

**Comment by dpursehouse** [comment]
@cushon are you planning to include a fix for #211 before releasing?

**Comment by cushon** [comment]
@dpursehouse I'm not sure yet. We don't want to anyone to be stuck on the previous release, but disabling that feature would be regression for internal users. If you have an opinion either way, can you add it to #211?

**Comment by dpursehouse** [comment]
@cushon I'd need to test how it would impact the Gerrit project.  My question was more about finding out when to expect a new release :)

**Comment by cushon** [comment]
I released it: https://github.com/google/google-java-format/releases/tag/google-java-format-1.5

**Comment by talios** [comment]
On 19 Oct 2017, at 11:39, Liam Miller-Cushon wrote:


I released it: https://github.com/google/google-java-format/releases/tag/google-java-format-1.5



Excellent - pushed a new release of my googleformatter-maven-plugin-1.5.1 using this as well - should be in central soon.

Mark



"The ease with which a change can be implemented has no relevance at all to whether it is the right change for the (Java) Platform for all time." — Mark Reinhold.

Mark Derricutt
http://www.theoryinpractice.net
http://www.chaliceofblood.net
http://plus.google.com/+MarkDerricutt
http://twitter.com/talios
http://facebook.com/mderricutt

**Comment by dpursehouse** [comment]
PR to upgrade homebrew is here: https://github.com/Homebrew/homebrew-core/pull/19627
