### ISSUE TITLE
Enforcing a space in one-line comment breaks //$NON-NLS-x$ notation

### ISSUE THREAD

**Issue by romp13** [google/google-java-format#221]
Hi,
Since version 1.4 a new rule formats "//comment" into "// comment". Unfortunately Eclipse uses "//$NON-NLS-x$" comments to avoid internationalization warnings. If you add the space it does not work anymore. We have these all over the place in our codebase which prevents us of using versions of google-java-format later than 1.3.
Would it be possible to handle this case? (maybe a solution is to check if the first character is alpha-numeric)
Alternatively would there be a workaround for us with a setting.
Thanks!

**Comment by briandealwis** [comment]
By way of background, the Eclipse Compiler for Java (ecj) can be configured to warn about non-externalized strings for internationalization.  The warnings can be suppressed by annotating strings with comments like `//$NON-NLS-x$` to indicate that the `x`th string on the line is not meant to be externalized (such as an identifier).

An alternative approach to #222 would be to special case `$NON-NLS-x$` similar to the `noinspection` that's already supported:
```
private static final Pattern LINE_COMMENT_MISSING_SPACE_PREFIX =
      Pattern.compile("^(//+)(?!noinspection|\\$NON-NLS-\\d+\\$)[^\\s/]");
```

However there's one additional difference in that the `//$NON-NLS-x$` should be kept with the string, and it shouldn't wrap even if it extends beyond the line-length.  But perhaps that should just be punted to the developers to manage (e.g., split long strings).

**Comment by cushon** [comment]
I understand that reformatting e.g. `//$NON-NLS-1$` to `// $NON-NLS-1$` (with a space after the `//`) is an issue for eclipse, and I think special-casing these comments similar to `//noinspection` is probably OK.

I'm not sure I understand the line wrapping issue, though: google-java-format doesn't currently reflow long string literals, or move line comments off very long lines.

e.g. this is not currently wrapped:

```java
class T {
  private String s =
      "long looooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooong string"; // $NON-NLS-1$
}

```

Do you have an example of a `//$NON-NLS-x$` comment where line wrapping is an issue?

**Comment by cushon** [comment]
Thanks, is it an option to write that code like this instead?

```java
    } catch (CoreException ex) {
      logger.log(
          Level.WARNING,
          "Unable to obtain jst.web facet version from selected project", //$NON-NLS-1$
          ex);
    }
```

**Comment by cushon** [comment]
Thanks for clarifying. I agree it would be nice if the formatter could do that automatically, but I'd prefer to avoid adding a lot of logic to the formatter to handle this specific case.

It sounds like not adding the space to `//$NON-NLS-1$` comments (like we already do for `//noinspection`) is a step in the right direction, even if it doesn't completely solve the problem and occasionally you have to manually move a tag?

**Comment by briandealwis** [comment]
Yup, that would be great.  Eclipse can be configured to flag strings missing a `//$NON-NLS-x$` so the misattributed tag will be immediately apparent to the developer.

**Comment by briandealwis** [comment]
Unfortunately this fix is insufficient.  Consider the following sample class:
```java
public class ExampleClass {
  public Object resolveClasspathContainer() {
    System.out.printf(
        "This is an expression %s\n", //$NON-NLS-1$
        "value"); //$NON-NLS-2$
    System.out.println("statement"); //$NON-NLS-3$
    Job resolveJob = new Job("Resolving libraries for " + webFacetVersion) { //$NON-NLS-4$
          @Override
          protected IStatus run(IProgressMonitor monitor) {}
        };
    return null;
  }
}
```
The formatting of `//$NON-NLS-3$` and `-4` are not preserved:
```diff
@@ -3,8 +3,8 @@
     System.out.printf(
         "This is an expression %s\n", //$NON-NLS-1$
         "value"); //$NON-NLS-2$
-    System.out.println("statement"); //$NON-NLS-3$
-    Job resolveJob = new Job("Resolving libraries for " + webFacetVersion) { //$NON-NLS-4$
+    System.out.println("statement"); // $NON-NLS-3$
+    Job resolveJob = new Job("Resolving libraries for " + webFacetVersion) { // $NON-NLS-4$
           @Override
           protected IStatus run(IProgressMonitor monitor) {}
         };
```

**Comment by romp13** [comment]
I am a bit puzzled by your example because the number in the non-nls comment should correspond to the literal's number on the line. If you copy this code in Eclipse you will get warnings for invalid non-nls comments. I believe the code get split into multiple lines first and if you read this thread entirely you will understand that this is not covered by the fix. But there is maybe something else.

**Comment by briandealwis** [comment]
Sorry I should have made that clear: the numbers are purely for referencing purposes.
