### ISSUE TITLE
Documentation about thread safety of formatter is missing

### ISSUE THREAD

**Issue by sherter** [google/google-java-format#23]
I couldn't find any information about the thread safety of the formatter in the documentation, so I'm asking here and suggest to improve the documentation in this regard.

Is it safe to use the same `com.google.googlejavaformat.java.Formatter` instance concurrently from multiple threads, assuming that I'm reading/writing different files?

**Comment by cushon** [comment]
`Formatter` doesn't have any per-instance state, so it's thread-safe but sharing instances doesn't have much benefit. We may be adding some fields for internal configuration soon, but instances will still be immutable.

I'll documentation that.
