### ISSUE TITLE
Errors building intellij plugin

### ISSUE THREAD

**Issue by amc6** [google/google-java-format#24]
I've encountered a number of issues while attempting to build the intellij plugin. Let me know if you would like me to file all of these as separate issues.

1. The install-idea-jars.sh script does not work on osx. It expects a path like /opt/jetbrains/idea-IU-141.178.9 but on osx the path is something like /Applications/IntelliJ\ IDEA\ 15\ CE.app/Contents/ Even a zip download is by default in this format ideaIU-14.1.6.zip
2. The for loop in install-idea-jars.sh fails when the ideaHomeDir path contains spaces, like it will on osx.
3. Building the plugin requires exactly 141.178.9 which corresponds to release 14.1.4, so you have to have exactly this version installed. install-idea-jars.sh will install the jars from any version of intellij, so this requirement is not clear up front. As far as I can tell, this release is not available from jetbrains anymore. The closest I could find is 14.1.6. I also tried checking out the source for 141.178.9, but that doesn't seem to include all of the necessary libraries. And compiling intellij from source is a project by itself.
4. I tried installing the 14.1.6 libraries as 14.1.4 libraries, but I get this error when compiling:
`/Users/adamcook/code/google-java-format/idea_plugin/src/main/java/com/google/googlejavaformat/intellij/GoogleJavaFormatCodeStyleManager.java:47: error: GoogleJavaFormatCodeStyleManager is not abstract and does not override abstract method reformatTextWithContext(PsiFile,Collection<TextRange>) in CodeStyleManager
public class GoogleJavaFormatCodeStyleManager extends CodeStyleManagerDecorator {`
This could just be because I am not actually using the right library version.

Thanks!

**Comment by amc6** [comment]
Alternatively, is a prebuilt version of the plugin available? My team is considering adopting the formatter, but ideally we would also have auto formatting in Android Studio. So I was curious to see how the plugin currently worked.

**Comment by sherter** [comment]
If the Intellij plugin is not working for you, you could use this [Gradle plugin](https://github.com/sherter/google-java-format-gradle-plugin) for now...

**Comment by amc6** [comment]
Thanks I'll check that out.

**Comment by cushon** [comment]
I fixed up the plugin and uploaded a copy to the plugin repository: https://github.com/google/google-java-format#intellij
