### ISSUE TITLE
Plugin does not organize import in Android Studio

### ISSUE THREAD

**Issue by redwarp** [google/google-java-format#245]
When calling the "Reformat code" from Android Studio, the imports are not optimized/organized, but the code is.
When running "Optimize imports", then Android Studio's settings for imports order are used instead of the plugin.
When calling "Reformat code" with "Optimize import" enabled, code is reformated properly, but imports are optimized using Android Studio's settings.

I think that the plugin should override the Optimize import as well to make it consistent

Android Studio 3.0.1
Mac OS 10.13.2

**Comment by wangpung12** [comment]
Hi

**Comment by plumpy** [comment]
Dup of #94
