### ISSUE TITLE
Provide programmatic access to fields in FormatterDiagnostic

### ISSUE THREAD

**Issue by sherter** [google/google-java-format#25]
I know this project is in an early stage and you are probably working on the public API internally. However, I just stumbled upon this issue and wanted to leave a note.

One can retrieve the [diagnostics](https://github.com/google/google-java-format/blob/master/core/src/main/java/com/google/googlejavaformat/java/FormatterException.java#L37) from a FormatterException, but a [FormatterDiagnostic](https://github.com/google/google-java-format/blob/master/core/src/main/java/com/google/googlejavaformat/FormatterDiagnostic.java) doesn't provide programmatic access to the error information. This forces the programmer to parse the String returned by [toString()](https://github.com/google/google-java-format/blob/master/core/src/main/java/com/google/googlejavaformat/FormatterDiagnostic.java#L39) (Effective Java Item 10).

**Comment by cushon** [comment]
That sounds fine to me. Any interest in creating a pull request to add getters to `FormatterDiagnostic`?
