### ISSUE TITLE
Add support for IntelliJ 2018.1

### ISSUE THREAD

**Issue by staslev** [google/google-java-format#252]
As stated by the [plugin site](https://plugins.jetbrains.com/plugin/8527-google-java-format) the latest version (`1.5.0.173`) supports IntelliJ versions `173—173.*` and is therefore incompatible with the the latest version of IntelliJ - `2018.1 (EAP)`:

```
IntelliJ IDEA 2018.1 EAP (Community Edition)
Build #IC-181.3494.3, built on February 6, 2018
JRE: 1.8.0_152-release-1136-b5 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.12.6
```

The incompatibility is confirmed by an error message upon attempting to install `1.5.0.173` on IntelliJ `2018.1 (EAP)`.

This is a really great plugin, looking forward to the fix!

**Comment by thibaut-sticky** [comment]
What can be done to add the compatibility?

**Comment by wangxufire** [comment]
any update?

**Comment by sharomank** [comment]
IntelliJ IDEA 2018.1 RC2 is here, any news?

**Comment by iemejia** [comment]
Mmm actually 2018.1 is out. Maybe time to tackle this one.

**Comment by plumpy** [comment]
1.5.1 is now in the plugin repo and supports IDEs from 2017.1 to 2018.1.
