### ISSUE TITLE
Interest in GUI?

### ISSUE THREAD

**Issue by captainabedabes** [google/google-java-format#27]
Obviously this tool is meant for developers, who should know how to use the terminal. Still, I think it would add a lot to the project if there were an option to use a GUI to select the code to format. If this is in line with project goals, I would definitely work to add one in.

**Comment by sherter** [comment]
IMHO a separate GUI tool isn't very useful. The project would benefit much more from plugins for IDEs/Editors. Plugins for [IntelliJ IDEA](https://github.com/google/google-java-format/tree/master/idea_plugin) and [Emacs](https://github.com/google/google-java-format/blob/f3acef6984982bb6bca7d600e2420b7406d839e4/core/src/main/scripts/google-java-format.el) are already there. Eclipse users would sure be thankful, if there was a plugin for their favorite IDE :wink: 

I'm currently working on a [Gradle plugin](https://github.com/sherter/google-java-format-gradle-plugin). That's not as interactive and good as a plugin that is tailored to a specific IDE, but it might come in handy, for example, to verify correct style in continuous integration environments. And Gradle is already integrated into IDEs, so formatting your sources is often only one click away. You might consider doing something similar for maven users.

**Comment by cushon** [comment]
What sort of GUI did you have in mind? I agree with @sherter that better IDE integration would be more useful than a standalone tool.

**Comment by GuiSim** [comment]
I've created a Maven plugin which might meet some of your requirements

https://github.com/coveo/fmt-maven-plugin

**Comment by cushon** [comment]
The README now mentions some of the plugins that have been created (including coveo/fmt-maven-plugin, thanks @GuiSim!). We don't have plans to add a GUI tool at this time.
