### ISSUE TITLE
Released google-java-format-eclipse-plugin_1.5.0.jar shows version 1.4

### ISSUE THREAD

**Issue by zolv** [google/google-java-format#271]
After attaching google-java-format-eclipse-plugin_1.5.0.jar into Eclipse it says it uses version 1.4

![google-formatter-1 4](https://user-images.githubusercontent.com/10470118/38410934-2fd53742-3986-11e8-93f9-e96617b074ba.png)

```
<?xml version="1.0" encoding="UTF-8"?>
<?eclipse version="3.4"?>
<plugin>
   <extension point="org.eclipse.jdt.core.javaFormatter">
   <javaFormatter
         class="com.google.googlejavaformat.java.GoogleJavaFormatter"
         id="com.google.googlejavaformat.java.GoogleJavaFormatter"
         name="google-java-format 1.4">
   </javaFormatter>
   </extension>
</plugin>
```

Internally it looks like it contains correctly 1.5 version of the plugin.
But **it still doesn't fit to 1.5 guidline** e.g. it removes an empty line between import static part and other imports (as mentioned in [released bug fixes for 1.5.0 version](https://github.com/google/google-java-format/releases/tag/google-java-format-1.5)

**Comment by sormuras** [comment]
Due to https://github.com/google/google-java-format/blob/master/eclipse_plugin/plugin.xml#L8

**Comment by kingthorin** [comment]
Also mentioned over here > https://github.com/google/google-java-format/issues/260

**Comment by kingthorin** [comment]
Fixed in https://github.com/google/google-java-format/commit/2eb554d124ee2972aef6a9f28cf2adbbfbccf534#diff-34d57fa96d7379a662a7967134837ff2 ?
