### ISSUE TITLE
Incompatibility with Google Checks

### ISSUE THREAD

**Issue by gui-** [google/google-java-format#272]
Using the format on the following annotation: 
`@Annotation(param1 = "assume a long sentence here")`
It will wrap the annotation as expected.
`@Annotation(`
`....param1 = "assume a long sentence here"`
`) `
However, when I run Google Checks over this code I get the following error:
> 'param1' has incorrect indentation level 4, expected level should be 6.  [IndentationCheck]

**Comment by cushon** [comment]
See #159.
