### ISSUE TITLE
Why Formatter Comment???

### ISSUE THREAD

**Issue by liangjingkanji** [google/google-java-format#276]
?????

**Comment by liangjingkanji** [comment]
![image](https://user-images.githubusercontent.com/21078112/39182375-4ce86eea-47ef-11e8-9136-8be8e3adf651.png)

show error when command + shift + j generate comment code

**Comment by liangjingkanji** [comment]
influence my beautiful of comment

**Comment by Stephan202** [comment]
Hi @liangjingkanji, what seems to be the problem? :)

**Comment by liangjingkanji** [comment]
i use "fix doc comment" shortcut key for AndroidStudio

**Comment by cushon** [comment]
Hi, can you provide a complete, self-contained example of a Java file that demonstrates the problem you're seeing?

**Comment by liangjingkanji** [comment]
i hope do not format to comment 

my android studio reversion to 3.0.1, because last version has bad bug, 3.0.1 is do't install of this plugins

**Comment by cushon** [comment]
Can you provide a complete example of a program that demonstrates the issue you're seeing? For example:

Input:

```java
$ cat T.java
class T {
  /**
   * @param context
   */
  void f() {}
}
```

Output:

```java
$ google-java-format T.java
class T {
  /** @param context */
  void f() {}
}
```

**Comment by liangjingkanji** [comment]
Input:
![image](https://user-images.githubusercontent.com/21078112/39439197-56da1252-4cd9-11e8-8f27-87c823fc3302.png)



Output
![image](https://user-images.githubusercontent.com/21078112/39439208-5db953f8-4cd9-11e8-8368-5cb72122d83a.png)


in my intelij idea

**Comment by cushon** [comment]
Please share the inputs as text instead of an image. Does this problem reproduce using the command line `google-java-format` tool?

**Comment by liangjingkanji** [comment]
input

```java
/**
 *  百度 是 个 垃圾公司
 *  大家都这么认为
 *
 */
class Main {
    public static void main(String[] args) {
        Observable.range(1, 100)
                .subscribe(System.out::println);

    }
}
```


output

```java
/** 百度 是 个 垃圾公司 大家都这么认为 */
class Main {
    public static void main(String[] args) {
        Observable.range(1, 100).subscribe(System.out::println);
    }
}
```

**Comment by lowasser** [comment]
What is wrong with that?

**Comment by cushon** [comment]
If you don't want the lines to be joined, can you use html markup in your javadoc? Adding a `<p>` tag before the second line will prevent the reformatting.

**Comment by cushon** [comment]
If the concern is that html javadoc markup is not beautiful then I tend to agree, but it is required by the style guide for javadoc comments: https://google.github.io/styleguide/javaguide.html#s7.1.2-javadoc-paragraphs. I'm not sure there's much we can do here.

**Comment by liangjingkanji** [comment]
..... is sadness
