### ISSUE TITLE
Inconistent spacing with type annotations, varargs, and arrays

### ISSUE THREAD

**Issue by mernst** [google/google-java-format#282]
Consider the following code, which has been formatted with google-java-format version 1.5:

```
public class ArrayVsVarargs {

  void anArrayParam1(String[] arg) {}

  void varargsParam1(String... arg) {}

  void anArrayParam2(String @Nullable [] arg) {}

  void varargsParam2(String @Nullable... arg) {}
}
```

In the first two methods, when there are no type annotations, google-java-format is consistent about putting no space between the element type and the array indicator `[]` or `...`.

When there is a type annotation, google-java-format is inconsistent about the following space:  it puts space before `[]` but no space bofore `...`.

I think that google-java-format should be consistent, and should always put spaces on both sides of a type annotation.
This is how it worked in version 1.3, so it would be nice to revert to that behavior.

**Comment by cushon** [comment]
Thanks for pointing this out. Do you have opinions about which formatting should be preferred? The examples in JLS 9.7.4 include spaces before `[]`. I don't see examples of type annotated varargs in the spec. Would you expect to see e.g. `String @Nullable ... arg`?

**Comment by mernst** [comment]
Yes, my personal style preference is to put spaces around a type annotation on an array or varargs, so `String @Nullable ... arg`.

**Comment by cushon** [comment]
Thanks for confirming, that SGTM. I think we need to update section [4.6.2](https://engdoc.corp.google.com/eng/doc/devguide/java/style/index.md?cl=head#s4.6.2-horizontal-whitespace) of the style guide, and then I'll update google-java-format to match.

**Comment by cushon** [comment]
The style guide has been updated to allow horizontal whitespace

> Between a type annotation and `[]` or `....`

a change to `google-java-format` will follow soon.
