### ISSUE TITLE
Hope to make a wiki page for this project

### ISSUE THREAD

**Issue by Penny1128** [google/google-java-format#283]
My code ability is not very powerful, it is a bit harder for me to fix a bug in current stage, I hope I can provide some improvement on documentation and make some contribution on it. I am considering to build a wiki page to organise more information about this project, which will be clear for other people get whole solution of issues and avoid duplicate issues.

**Comment by cushon** [comment]
The documentation has recently been improved (thanks to @eaftan!):

* https://github.com/google/google-java-format/wiki/FAQ
* https://github.com/google/google-java-format/wiki/The-Rectangle-Rule

Is there something in particular you're interesting in contributing documentation for?
