### ISSUE TITLE
IntelliJ plugin 1.6 changed plugin defaults (no mention in release notes)

### ISSUE THREAD

**Issue by mkillianey** [google/google-java-format#290]
Commit 4c29598b4f8ec06755dd781944aa4ac8ff1025d0 changed the default enabled-ness of the google-java-format plugin and it was not mentioned in the release notes.

This is a disruptive regression, as prior to version 1.6, we had been using the plugin by committing the `.idea/google-java-format.xml` preferences file into specific repos (thus opting into the plugin's formatting behavior) *solely* for teams that had agreed to opt into one of the styles supported by the plugin.  For the large majority of projects that *didn't* opt into that formatting, this allowed us to encourage users to have the plugin installed locally (without causing harm) until they modified a project that *had* opted in.

Please consider this a request to revert that commit/change, ideally in a 1.6.1 patch release.  I'll suggest that the default option for most well-behaved code-modifying plugins in the IntelliJ ecosystem is to avoid modifying the user's code until/unless the user explicitly takes an action to opt-in, either on a global or per-project basis.  (See the checkstyle plugin, as an example.)  This allows companies to install the plugin by default on everyone's machines as a no-op, and lets individual teams enable it as they see fit.

If you're opposed to a patch release, it would be much appreciated if you could at least (1) amend the release notes to mention this change explicitly and (2) commit to not changing the defaults again, so that we only experience this disruption once.

**Comment by plumpy** [comment]
You're right; I certainly should have made mention of that in the release notes. Would you have expected to see it in the plugin's release notes or did you mean in the main GJF release notes on GitHub. The latter is unlikely to happen for a few institutional reasons, but I certainly could try to keep the plugin's release notes up to date.

I'm trying to think of a good balance between users like you who want to force-install the plugin and configure it in the source repository, and more casual users who just want to download the plugin from the plugin repository and have it just start working.

How about if I change it back to default to 'off', but present a notification if no google-java-format.xml is present in the project (just the first time you open the project). Something like "The google-java-format plugin is not enabled for this project. Click here to enable it. Click here to enable it by default in all new projects. Click here to never see these messages again."

Does that seem like a reasonable compromise?

**Comment by cushon** [comment]
Sorry for the trouble. I updated the github relnotes to mention this, and we'll document the solution in the relnotes for the next release.

Michael, your suggestion sounds good to me.

**Comment by mkillianey** [comment]
I like the compromise of off-by-default, but offering to enable it when opening a project.  A request:  several other IntelliJ dialogs also have the option "Remember, Don't Ask Again" or "Do not show this dialog in the future" for people who don't want to be nagged.  If you ask the user, could you use the same approach?

https://github.com/JetBrains/intellij-community/blob/941e25e5995bcf3d1d584b5aefcaeaf48cdd3870/platform/platform-resources-en/src/messages/CommonBundle.properties#L3-L4

Example:

![screen shot 2018-06-21 at 2 30 39 pm](https://user-images.githubusercontent.com/180863/41746597-bbda80ca-755f-11e8-8a05-5484068e7eee.png)

**Comment by plumpy** [comment]
Using a dialog feels to heavyweight, so I was just going to use a notification balloon. I'm not sure if I can put a checkbox in there, but I'll investigate. Thanks for the idea.

**Comment by mkillianey** [comment]
Ooh, yeah, a notification sounds perfect, since it's unobtrusive and any user sufficiently motivated to complain can be taught to set their notification level to hide it.

Thanks very much for the plugin, btw...it saves us an enormous amount of bikeshedding.

**Comment by plumpy** [comment]
Okay, that should be pretty simple. I should be able to get a new 1.6.1 version up early next week. Thanks for the report.

**Comment by plumpy** [comment]
Okay, I just uploaded a 1.6.1 with the changes we discussed. Let me know if you have any issues with it!
