### ISSUE TITLE
Is there a way to convert line endings with this ? 

### ISSUE THREAD

**Issue by mithuns** [google/google-java-format#291]
I am using [fmt-maven-plugin](https://github.com/coveo/fmt-maven-plugin), which basically just uses this to format everything. 
I am curious if there is a line ending formatter functionality, that I can use. 
So, right now this does not change or complain about line endings.

**Comment by cushon** [comment]
The formatter uses this logic to infer the newlines used by the input and preserve them:

https://github.com/google/google-java-format/blob/fbe7a3d199d416ad1681bd19307c434df28bd250/core/src/main/java/com/google/googlejavaformat/Newlines.java#L24

Are you interested in configuration to make the formatter use a specific line ending, regardless of what the input used? Or something else?

**Comment by mithuns** [comment]
Yeah, I was hoping it was possible to basically say, update all line endings to unix-style only/windows-style only/no-change. 
Could be just a simple flag.

**Comment by cushon** [comment]
There's some discussion of the approach to configuration here: https://github.com/google/google-java-format/wiki/FAQ#i-just-need-to-configure-it-a-bit-differently-how.

For converting line endings I'd recommend using something like `dos2unix` or `unix2dos`, or seeing if your VCS can normalize them for you (e.g. for git https://help.github.com/en/articles/dealing-with-line-endings).

**Comment by tracyhenry** [comment]
Right now, if a windows developer commits some changes to a codebase that has UNIX line endings, google-java-format will format everything to windows endings and generate huge diffs. 

Of course you can ask that windows developer to change his per-repository git settings, or we add another line-ending formatter prior to goolge-java-format in pre-commit. But it just feels like Google-java-format is not promoting cross-platform collaborations.
