### ISSUE TITLE
Avoid plus sign in maven artifact version numbers.

### ISSUE THREAD

**Issue by btpka3** [google/google-java-format#292]
The version of artifact `com.google.errorprone:javac-shaded:jar:9+181-r4173-1` contains a `+` sign. Some tools I using will error, they read file name as  URL, then `+` became ` `(space), result in FileNotFoundException.

Plus sign should be avoid.

**Comment by cushon** [comment]
Which tools are you having trouble with?

**Comment by Richard-Mathie** [comment]
Having the same issue here. issue being we have to get packages from mvnrepository through a proxy and the proxy has a version policy which states. Version number must consist of Numbers Letters periods (.) and underscores (_) only. i.e. `[a-zA-Z0-9][\w.]{0,99}`

I know... :/

**Comment by cushon** [comment]
The formatter no longer depends on that shaded javac artifact: https://github.com/google/google-java-format/commit/3c191c1326b77aabbf2a48c3edc19b628f4327d6
