### ISSUE TITLE
Support google-java-format for android developers?

### ISSUE THREAD

**Issue by MisterGitHubber** [google/google-java-format#296]
I try use google-java-format for my android java IDE and i got error

   ` java.lang.NoSuchMethodError: No static method stream([Ljava/lang/Object;)Ljava/util/stream/Stream; in class Ljava/util/Arrays; or its super classes (declaration of 'java.util.Arrays' appears in /system/framework/core-libart.jar)`

I know that android not supported java 8 but may be source code possible to change for compatibility?

**Comment by jbduncan** [comment]
Hi @MisterGitHubber, which variant of google-java-format are you trying to use: the command-line application, the IntelliJ plugin, the Eclipse plugin, or one of the third-party integrations?

**Comment by MisterGitHubber** [comment]
@jbduncan Hello! I trying use google-java-format for my IDE

**Comment by jbduncan** [comment]
Just to clarify, is this Android Studio or something else?

**Comment by MisterGitHubber** [comment]
@jbduncan I'm writing an android application - my IDE in which you can program the program. I now add the function to the format of the code and found the google-java-format utility. I use Android Studio to write IDE

**Comment by MisterGitHubber** [comment]
@jbduncan if you do not understand - that's what I do https://github.com/MisterGitHubber/VeneraIDE

**Comment by MisterGitHubber** [comment]
My IDE use linux system and use proot for access to jdk. Version of jdk is 8. Users can compile java 8 code  directly on android device without PC. I run google-java-format from linux but it ugly: run java 8 code from java code....... Please help me run formatter from java 7

**Comment by jbduncan** [comment]
Oh cool! So if I've understood you correctly, you're trying to build your own IDE for Android development - VeneralIDE - and you're now trying to integrate google-java-format into it. Is that right?

Also, I'm curious as to why you're using Android Studio to program VeneralIDE. Is VeneralIDE itself going to be an Android app?

**Comment by MisterGitHubber** [comment]
@jbduncan Yes. You right :) Yes, I use Android Studio because.... VeneraIDE will be the android app

**Comment by jbduncan** [comment]
Oops, sorry, I posted my last comment just before seeing that you posted [this one](https://github.com/google/google-java-format/issues/296#issuecomment-406873462). :)

> I run google-java-format from linux but it ugly: run java 8 code from java code....... Please help me run formatter from java 7

Hmm, I'm struggling to understand so far what you're saying. Are you trying to call `java -jar google-java-format.1.x.jar` on this Linux system which has a JDK 8 (by my understanding, this should work perfectly fine)? Or are you trying to do something else? :thinking:

**Comment by MisterGitHubber** [comment]
@jbduncan android does not support Java 8. so I decided that the application would use Linux (like the Linux Deploy app). Compilation of Java 8 code is excellent.

I can not run Google-Java format directly in my java code because it is written in Java 8 which is supported only starting with Android 8. I copied the google-java-format.jar into the folder of the assemblies of my application. when installed, it is copied to the private application folder. I run him with Linux

**Comment by MisterGitHubber** [comment]
@jbduncan 

https://github.com/MisterGitHubber/VeneraIDE/blob/ca9104ec37f3b398b2d730adc8417befdb4a003f/app/src/main/java/com/d330/veneraide/ui/activity/IDE.kt#L71

**Comment by MisterGitHubber** [comment]
@jbduncan But you will agree that `Java>Linux>Java` is too cumbersome. Therefore, I would like the google-java-format to be written in Java 7 (there was support for android developers)

**Comment by MisterGitHubber** [comment]
when he does something unusual nobody understands what you are doing 😭

**Comment by jbduncan** [comment]
Ah okay, I think I understand what you're trying to do now.

Currently, VeneraIDE effectively loads up an "internal" Linux OS, which in turn runs `java -jar google-java-format-1.x.jar`, where `java` is from Java 8. However, you ideally want VeneraIDE to be able to call google-java-format directly as a library, which is currently impossible because VeneraIDE is an Android app and it supports Android version(s) which are not compatible with Java 8.

Is my understanding correct?

Indeed, this sounds like a legitimate need to me for google-java-format to either support Java 7+ or to have a separate Android variant (similar to how Guava has both `-jre` and `-android` variants).

Now I'm not on the google-java-format team, so what does everyone on the google-java-format team think about this? @cushon?

**Comment by MisterGitHubber** [comment]
@jbduncan, yes, absolutely correct understanding.

**Comment by cushon** [comment]
`google-java-format` uses javac's parser, and version N of javac isn't compatible with JDKs earlier than version N-1. We don't have a good way to support running the latest version of the formatter on older JDKs, or the bandwidth to maintain branches of it targeting different versions.
