### ISSUE TITLE
Provide IntelliJ Code Styles XML

### ISSUE THREAD

**Issue by swankjesse** [google/google-java-format#3]
Square has a GitHub project that configures IntelliJ just the way we like it:
https://github.com/square/java-code-styles

Since a lot of users of this project will also be IntelliJ users, it would be quite excellent if the two tools would not conflict with each other on mechanical reformatting. The Square styles above are _almost_ exactly perfect, though there are some tiny differences.

Like these:
  `new String[] { "a" }`
  `new String[]{ "a" }`

A definitive single source of truth for IntelliJ would be handy.

**Comment by cgdecker** [comment]
Isn't the whole reason this formatter exists that configurable formatters like Eclipse's and IntelliJ's are incapable of of formatting just as we want? I'd think what we really need would a plugin to completely replace IntelliJ's formatter with this one, though I have no idea if that's possible with IntelliJ's plugin architecture.

**Comment by kevinb9n** [comment]
There is this, which I think maybe Eddie is trying to get updated:

https://code.google.com/p/google-styleguide/source/browse/trunk/intellij-java-google-style.xml

but it is impossible for the tools to not conflict since google-java-format
is way better



On Fri, May 15, 2015 at 8:39 AM, Jesse Wilson <notifications@github.com>
wrote:

> Square has a GitHub project that configures IntelliJ just the way we like
> it:
> https://github.com/square/java-code-styles
>
> Since a lot of users of this project will also be IntelliJ users, it would
> be quite excellent if the two tools would not conflict with each other on
> mechanical reformatting. The Square styles above are *almost* exactly
> perfect, though there are some tiny differences. (Like new String[] { "a"
> } vs new String[]{ "a" }).
>
> A definitive single source of truth for IntelliJ would be handy.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/google-java-format/issues/3>.
>



-- 
Kevin Bourrillion | Java Librarian | Google, Inc. | kevinb@google.com

**Comment by kevinb9n** [comment]
Right, we have a volunteer who claims he will figure out how to hook it
into IntelliJ, though I think there's probably still value in setting the
IntelliJ settings as close as we can, for the benefit of its type-as-you-go
indenting, which won't be running our formatter all the time.

On Fri, May 15, 2015 at 8:46 AM, Colin Decker <notifications@github.com>
wrote:

> Isn't the whole reason this formatter exists that configurable formatters
> like Eclipse's and IntelliJ's are incapable of of formatting just as we
> want? I'd think what we really need would a plugin to completely replace
> IntelliJ's formatter with this one, though I have no idea if that's
> possible with IntelliJ's plugin architecture.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/google-java-format/issues/3#issuecomment-102441863>
> .
>



-- 
Kevin Bourrillion | Java Librarian | Google, Inc. | kevinb@google.com

**Comment by jgiles** [comment]
@kevinb9n I work on Android Studio with Blaze|Bazel and am also interested in solving this problem - who is working on it currently?
I agree with the assessment that a plugin will be necessary for on-demand formatting, and that we would still need to maintain a code style settings for as-you-go stuff.

**Comment by cushon** [comment]
Here's the initial intellij integration: bbcce560828016f9146b41050c1cfe50fbf953ff

**Comment by kevinb9n** [comment]
relevant: https://devnet.jetbrains.com/thread/464297

**Comment by cushon** [comment]
The google-java-format IntelliJ plugin should be useable now, for what it's worth: https://github.com/google/google-java-format#intellij

I'm not sure whether there's been any progress on getting the code style settings updated.

**Comment by cushon** [comment]
The code style settings have been updated: google/styleguide@75c289f1d33836d1ff4bd94e6c9033673e320b58
