### ISSUE TITLE
CLI v1.6 default formatting sorts import static statements differently than JetBrains plugin v1.6.1

### ISSUE THREAD

**Issue by matthewadams** [google/google-java-format#300]
In [version 1.6 of the executable jar](https://github.com/google/google-java-format/releases/download/google-java-format-1.6/google-java-format-1.6-all-deps.jar), `import static` statements precede nonstatic `import` statements.  However, in version 1.6.1 of [the JetBrains plugin](https://github.com/google/google-java-format/tree/master/idea_plugin), `import static` statements follow nonstatic `import` statements.

The command to use the formatter in our `.git/hooks/pre-commit` hook is the following:
```
git ls-files | \
    grep \.java$ | \
    xargs java -jar \
        $(dirname $0)/../../formatter/google-java-format-current.jar \
        -n \
        --set-exit-if-changed
```
It's returning `1` after formatting code in IntelliJ using the google-java-format plugin because the plugin is ordering `import static` statements differently than the cli.

This breaks our `pre-commit` hook, as we require properly formatted code in all commits.

When formatting via the command line, this is the command:
```
git ls-files | \
    grep \.java$ | \
    xargs java -jar \
        $(dirname $0)/../../formatter/google-java-format-current.jar -i
```

**Comment by matthewadams** [comment]
Here are the options presented by the plugin when formatting in IntelliJ IDEA:
![image](https://user-images.githubusercontent.com/449952/43612299-868ad9dc-9671-11e8-91fe-9069ecd605eb.png)

**Comment by matthewadams** [comment]
Here are the selected options when using the formatter in IntelliJ IDEA:
![image](https://user-images.githubusercontent.com/449952/43612335-ab2c12e2-9671-11e8-9393-7c256d8cdc92.png)

**Comment by tbroyer** [comment]
From https://github.com/google/google-java-format/blob/master/README.md#intellij:
> The import ordering is not handled by this plugin, unfortunately.

You have to configure it separately.
