### ISSUE TITLE
Wrong indentation when line wrapping

### ISSUE THREAD

**Issue by dnsbtchr** [google/google-java-format#302]
Hi,

when I use the plugin in IntelliJ it formats using 2 spaces before the imported Config classes:
```
@Import({
  OtherConfig.class,
  MyConfig.class
})
public class Application {
```

But according to the Google Java format it should be 4 spaces see 'lineWrappingIndentation' in https://github.com/search?q=path%3Asrc%2Fmain%2Fresources+filename%3Agoogle_checks.xml+repo%3Acheckstyle%2Fcheckstyle+Indentation

So after formatting it should actually contain 4 spaces before the imported Config classes:
```
@Import({
    OtherConfig.class,
    MyConfig.class
})
public class Application {
```

Best regards
Dennis

**Comment by cushon** [comment]
The output of `google-java-format` is correct, the checkstyle code you linked to is incorrect: https://github.com/checkstyle/checkstyle/issues/5951
