### ISSUE TITLE
Potentially invalid indentation.

### ISSUE THREAD

**Issue by nathanburrell** [google/google-java-format#305]
Hi,

I recently formatted some code using this project, however I am getting check style violations.

I have raised a [bug](https://github.com/checkstyle/checkstyle/issues/6106) with checkstyle for two violations I believe are incorrect.

The first issue (WhitespaceAround violation), occurs with empty lambdas and I believe is incorrect and have proposed a fix to the checkstyle rules.

However the second issue (Indent violation), I cant seem to reason about why its a violation.

The class in question is: [IndentCheck](https://bitbucket.org/nburrell/google-style/src/master/src/main/java/com/atlassian/IndentCheck.java)

```java
package com.atlassian;

import java.util.function.Supplier;
import java.util.stream.Stream;

/** IndentCheck violation. */
public final class IndentCheck {
  /**
   * Entrypoint.
   *
   * @param args the arguments passed via the command line
   */
  public static void main(final String[] args) {
    IndentCheck.from(
            () -> {
              return new String[] {"one", "two", "three", "four", "five"};
            })
        .forEach(
            (string) -> {
              System.out.println(string);
            });
  }

  public static <T> Stream<T> from(final Supplier<T> supplier) {
    return Stream.of(supplier.get());
  }
}
```
This class has been formatted by the latest version of the google-java-format library via the coveo maven plugin. 

The lambda arguments to the methods are too large to fit onto one line so the formatter has moved them onto the next line, however it has indented them by +12 whitespace, whereas the checkstyle rules expect +6 or +8.

The style guide has two rules for indentation.

[4.2](https://google.github.io/styleguide/javaguide.html#s4.2-block-indentation) which state that each time a new block or block like statement is opened it should be indented by +2 (which the body of the lambda is correctly).

[4.5.2](https://google.github.io/styleguide/javaguide.html#s4.5.2-line-wrapping-indent) which state for continuation lines should be indented by +4. 

Which could maybe explain why it expects +6 or +8 (new block and also a continuation line?).

Why is the formatter than indenting by +12?

**Comment by cushon** [comment]
4.5.2 requires *at least* +4, and adds:

> In general, two continuation lines use the same indentation level if and only if they begin with syntactically parallel elements.

The formatter is indenting `() -> {` and `.forEach(` differently because they are not 'syntactically parallel'; the lambda is nested more deeply in its enclosing expression.

**Comment by nathanburrell** [comment]
Cool, I got the forEach bit I wasnt sure about the lambda args, so they are +4 as they are continuation lines for the methods.

And it did +8 as to keep them inline with the continutation line for the forEach aswell.

Cool Ill close this issue :)
