### ISSUE TITLE
Why we need IDEA plugin as we already can import the xml file?

### ISSUE THREAD

**Issue by mjason3** [google/google-java-format#308]
As titled, I have no idea what's the difference betweeing imporing the xml file and install the plugin. Could you elaborate more on the purpose of plugin? 
Thanks in advance!

**Comment by sormuras** [comment]
You can't configure an IDE-supplied (includes Eclipse) or other generic formatter to support [all formatting rules](https://google.github.io/styleguide/javaguide.html) implemented by g-j-f. That was the reason for creating this project.

**Comment by mjason3** [comment]
Answered my question. Thanks @sormuras
