### ISSUE TITLE
Documentation does not reflect API

### ISSUE THREAD

**Issue by GuiSim** [google/google-java-format#31]
The documentation states:

> You can then use the formatter quite simply using the various formatSource methods. E.g.
> 
> `String formattedSource = Formatter.formatSource(sourceString);`

However `formatSource` is not a static method on `Formatter`.

I am unsure of the correct solution. Either the documentation should recommend using a `Formatter` instance and call the non-static method `formatSource` or the documentation should recommend using the static method `format`.

**Comment by cushon** [comment]
Thanks, I'll fix the docs. It should be `Formatter.formatSource(...). Instances are `Formatter` are immutable, so they're fine to re-use.
