### ISSUE TITLE
Advice requested: Respect existing line breaks

### ISSUE THREAD

**Issue by robfig** [google/google-java-format#318]
I'm trying to get google-java-format to respect existing line breaks, as gofmt does. I want to make it  not insert or remove newlines in the middle of a statement, even if it adjusts indentation or other things about it.

I've spent some time going over the code, but I'm having trouble figuring out how to make such a change. Can you provide any pointers on how to accomplish this? 

Thank you!
-Rob

**Comment by robfig** [comment]
Sorry, I didn't mean to propose to change this tool itself -- I wanted to make a fork of it that was more palatable to those used to gofmt. I believe without this change, I can't get the necessary buy-in to bring some relief to our Java developers that our Go developers have been enjoying. Gofmt has a similar approach and similar raves about it, so I don't think that my tweak is incompatible with what you pasted.

I had been hoping since it maintains interior blank lines within a function, that it might be feasible to accomplish if only I could be pointed in the right direction, but maybe that's not the case.

Thanks for responding!

**Comment by kevinb9n** [comment]
Oh, I see. @cushon might have insights to help you, maybe. But it could also be that it's just too deeply baked in.
