### ISSUE TITLE
Unable to import Code "IntelliJ Java Google Style"

### ISSUE THREAD

**Issue by chandragaajula** [google/google-java-format#325]
Running into error following the below step ->

"The import ordering is not handled by this plugin, unfortunately. To fix the import order, download the [IntelliJ Java Google Style file](https://github.com/google/styleguide/blob/gh-pages/intellij-java-google-style.xml) and import it into File→Settings→Editor→Code Style."

Error Message -> IntelliJ IDEA code style XML import failed with error message: null

IntelliJ Version:
IntelliJ IDEA 2018.2.4 (Ultimate Edition)
Build #IU-182.4504.22
![errormessage](https://user-images.githubusercontent.com/2474552/49240177-77404480-f3b9-11e8-8508-943f4583d77b.png)

**Comment by plumpy** [comment]
This almost certainly means the file was downloaded incorrectly. When you open the XML file in an editor, does it look identical to the one on the github page?

Try downloading it from this link instead:
https://raw.githubusercontent.com/google/styleguide/gh-pages/intellij-java-google-style.xml

**Comment by plumpy** [comment]
I added the better link to README.md in 69e2efccf9938cfb08b1d5315ad61ca4484bbd0a, so I'm going to mark this closed. Thanks for bringing it up.

**Comment by tal26** [comment]
Had the same issue with the correct XML. Restarting the IntelliJ worked magic. Don't thanks ;-)
