### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by cushon** [google/google-java-format#33]
The formatter makes some assumptions that don't work on Windows.

- [x] `File.renameTo()` is not portable (see #32)
- [x] The output always uses `\n` as a line terminator, we should probably use the platform terminator

**Comment by sormuras** [comment]
Two tests in `DiagnosticTest` fail on Windows due to hard-coded line separators in combination with `java.io.PrintWriter` dynamic behaviour:
```java
    /**
     * Line separator string.  This is the value of the line.separator
     * property at the moment that the stream was created.
     */
    private final String lineSeparator;
```
How do you want it to be fixed?
 * remove `\n` from end of expected string and use `contains` instead of `isEqualTo`

`assertThat(err.toString()).contains("<stdin>:2:4: error: Invalid character constant");` 

 * replace `\n` with `System.lineSeparator()`

`assertThat(err.toString()).isEqualTo("<stdin>:2:4: error: Invalid character constant" + System.lineSeparator());`?

**Comment by jbduncan** [comment]
I recently suggested in junit-team/junit5#398 the use of AppVeyor to prevent these sorts of Windows-related errors from cropping up in the future.

What does the google-java-format team think about using AppVeyor here?

**Comment by sormuras** [comment]
AppVeyor would report: `Tests run: 509, Failures: 270, Errors: 0, Skipped: 1` ... all `CRLF` related.

**Comment by jbduncan** [comment]
Haha, well then! Looks like a pretty convincing case for using AppVeyor to me.

**Comment by sormuras** [comment]
After converting all `.[in|out]put` files to `\n` line separators, the test reports: `Tests run: 507, Failures: 15, Errors: 0, Skipped: 1`

Maybe a `.gitattributes` with:
```
*.input -text
*.output -text
```
The remaining 15 failures are extra `\n` characters where none are expected. Like in `MainTest.importRemovalLines`, there's an empty line rendered between the `import` and `class` block.

**Comment by sormuras** [comment]
#79 proposes a dynamic way for the line separator issue, which does not override the user choice of which line separator to use.

May be, another command line option can be introduced using an enum named `LineSeparator`:
- AUTO_DETECT // use the separator used in input
- DEFAULT // use the system-dependend default separator via System.lineSeparator()
- UNIX // "\n"
- MAC // "\r"
- WINDOWS / "\r\n"

**Comment by sormuras** [comment]
Now, [travis](https://travis-ci.org/google/google-java-format/jobs/165445018) and local Windows machine agree: `Tests run: 517, Failures: 0, Errors: 0, Skipped: 1`

**Comment by sormuras** [comment]
If only Travis starts a [build](https://travis-ci.org/google/google-java-format/builds/169067102) and there was a AppVeyor build ... this issue was solved. (-:

**Comment by cushon** [comment]
https://ci.appveyor.com/project/eaftan/google-java-format/build/1.0.2

**Comment by jbduncan** [comment]
Ooh, great to see an AppVeyor build up and running! Thank you @eaftan and @cushon.

**Comment by eaftan** [comment]
Thank you guys for letting us know about AppVeyor.  We've been looking for a Windows CI solution for several of our projects.

**Comment by jbduncan** [comment]
You're very welcome @eaftan. :+1:

I look forward to seeing it being adopted across more Google OSS projects.
