### ISSUE TITLE
Incorrect formatting of empty lambdas in multi-block statements

### ISSUE THREAD

**Issue by ehiggs** [google/google-java-format#334]
The following code is formatted like so:

```java
class T {
  void fun(Foo foo) {
    Flowable.fromPublisher(foo)
        .subscribe(
            foo::doWork,
            err -> {},
            () -> {
                System.out.println("onComplete called");
            });
}
```

This code should have a space in the braces like `{ }` when part of a multi-block statement (according to google check style rules).

e.g.

```java
class T {
  void fun(Foo foo) {
    Flowable.fromPublisher(foo)
        .subscribe(
            foo::doWork,
            err -> { }, //<-- space in braces
            () -> {
                System.out.println("onComplete called");
            });
}
```

**Comment by cushon** [comment]
> according to google check style rules

Are you using checkstyle with `google_checks.xml`? The source of truth is the [Style Guide](https://google.github.io/styleguide/javaguide.html). This looks like a bug in checkstyle: https://github.com/checkstyle/checkstyle/issues/6381.

**Comment by ehiggs** [comment]
>Are you using checkstyle with google_checks.xml

yes.
