### ISSUE TITLE
source archive for 1.7 has the version 1.7-SNAPSHOT

### ISSUE THREAD

**Issue by dpursehouse** [google/google-java-format#338]
Building version 1.7 from the [source archive](https://github.com/google/google-java-format/archive/google-java-format-1.7.tar.gz) results in it building version `1.7-SNAPSHOT` because that's the version specified in the contained `pom.xml` file.  Compare to previous releases where the `pom.xml` is the exact version (`1.6`, `1.5` etc).

Due to this, google-java-format cannot be built for homebrew because it expects the exact version, not a snapshot.

**Comment by dpursehouse** [comment]
@cushon is it possible to fix this?

**Comment by cushon** [comment]
Sorry about that. I'll try to fix it in the next release.
