### ISSUE TITLE
Background for "Treat expressions ending in `.stream()` as a syntactic unit" change

### ISSUE THREAD

**Issue by JamesGuthrie** [google/google-java-format#341]
We're trying out 1.7 on our codebase and have found that the "Treat expressions ending in `.stream()` as a syntactic unit" change tends to make the code more difficult to read.

I assume that the intended use-case is so that something like:

```java
fooCollection
    .stream()
    .map(...)
    .collect(...)
```

formats to:

```java
fooCollection.stream()
    .map(...)
    .collect(...)
```

We have a few instances of relatively long method chains which have become much less readable with the new change, for instance:

Before 1.7
```java
return fooBar
    .baz()
    .and(SOME_PARAM.VALUE.eq(type.name()))
    .fetch()
    .stream()
    .map(Converter::convert)
```

After 1.7
```java
return fooBar.baz().and(SOME_PARAM.VALUE.eq(type.name())).fetch().stream()
    .map(Converter::convert)
```

Was this type of formatting change actually intentional? It doesn't seem as though the [Google Java Style Guide](https://google.github.io/styleguide/javaguide.html) says anything about how `.stream()` should be treated, so where did this decision come from? Are we "stuck" with the change, or would there be the potential to discern between `.stream()` being applied directly to a collection and it being applied to a chain of methods?

**Comment by sgrimm-sg** [comment]
This is biting us hard in our calls to fluent APIs, mostly jOOQ. Here's a concrete example to supplement the one in the issue.

1.6:

```java
    return dslContext
        .select()
        .from(AUTOINGEST_MONITOR)
        .join(AUTOINGEST_FORMS)
        .using(AUTOINGEST_FORMS.FORM_NAME)
        .where(AUTOINGEST_FORMS.ENABLED.isTrue())
        .orderBy(AUTOINGEST_MONITOR.FORM_NAME)
        .fetchInto(AutoingestMonitorRecord.class)
        .stream()
        .map(PerFormAutoIngestionDetails::autoIngestionRecordToObject)
        .collect(Collectors.toList());
```

1.7:

```java
    return dslContext.select().from(AUTOINGEST_MONITOR).join(AUTOINGEST_FORMS)
        .using(AUTOINGEST_FORMS.FORM_NAME).where(AUTOINGEST_FORMS.ENABLED.isTrue())
        .orderBy(AUTOINGEST_MONITOR.FORM_NAME).fetchInto(AutoingestMonitorRecord.class).stream()
        .map(PerFormAutoIngestionDetails::autoIngestionRecordToObject)
        .collect(Collectors.toList());
```

That's a relatively simple query, of course. For more complex ones, the result turns into a real mess, to the point where in some cases we're considering introducing temporary variables purely to keep the query formatting readable.

Perhaps the `stream()` rule could be tweaked so it only applies up to a maximum number of chained calls on the left-hand side?

**Comment by cushon** [comment]
> Perhaps the stream() rule could be tweaked so it only applies up to a maximum number of chained calls on the left-hand side?

The logic now only applies if the receiver of the call to `.stream()` fits on one line, otherwise it goes back to one method call per line: https://github.com/google/google-java-format/commit/9b0f0326cde0d751f8b8db12cd73b149f8bb9cea.

e.g.:

```java
    return dslContext
        .select()
        .from(AUTOINGEST_MONITOR)
        .join(AUTOINGEST_FORMS)
        .using(AUTOINGEST_FORMS.FORM_NAME)
        .where(AUTOINGEST_FORMS.ENABLED.isTrue())
        .orderBy(AUTOINGEST_MONITOR.FORM_NAME)
        .fetchInto(AutoingestMonitorRecord.class)
        .stream()
        .map(PerFormAutoIngestionDetails::autoIngestionRecordToObject)
        .collect(Collectors.toList());
```
