### ISSUE TITLE
Increase tab size setting

### ISSUE THREAD

**Issue by SenreySong** [google/google-java-format#349]
Currently, the plugin uses 2 tabs by default. Can you add an option to use 4 tabs?
From Google Java Style requirements format

**Comment by sormuras** [comment]
No tabs, just spaces: https://google.github.io/styleguide/javaguide.html#s4.2-block-indentation

Only available configurable option: [`AOSP`](https://github.com/google/google-java-format/blob/master/core/src/main/java/com/google/googlejavaformat/java/JavaFormatterOptions.java#L41), which doubles space amounts.

**Comment by tbroyer** [comment]
> Only available configurable option: [`AOSP`](https://github.com/google/google-java-format/blob/master/core/src/main/java/com/google/googlejavaformat/java/JavaFormatterOptions.java#L41), which doubles space amounts.

Reference: https://source.android.com/setup/contribute/code-style#use-spaces-for-indentation

**Comment by SenreySong** [comment]
ohhhhh,thk
