### ISSUE TITLE
Sort imports

### ISSUE THREAD

**Issue by jamox** [google/google-java-format#37]
Are there any plans to add feature to sort and group imports as described on the style guide?

**Comment by sherter** [comment]
Look what I found :wink: : https://github.com/google/google-java-format/commit/eb0030039434766814d3f5ff059b404af751c085

**Comment by jamox** [comment]
Whow, nice. 
Thou with quick tests it puts the com.google on top of the imports, when, I guess the "special imports" should really be based on the package of the file... But I'll dig in and see if I can get it working for me...

**Comment by cushon** [comment]
We're planning to stop special-casing `com.google` and simplify the [style guide rule about imports](https://google.github.io/styleguide/javaguide.html#s3.3.3-import-ordering-and-spacing). The implementation in the formatter should already be doing that.

**Comment by cushon** [comment]
The CLI now sorts imports according to the new rules (google/styleguide#160), and also removes unused imports. There's also a `--fix-imports-only` flag. I'll plan on making a new release soon.

The API doesn't change imports because it's unclear how that should work with partial formatting. I'm open to ideas there, and using `ImportOrderer` and `RemoveUnusedImports` directly would also work.

**Comment by sherter** [comment]
I'm not against having an `ImportOrderer` and an `UnusedImportRemover` in addition to the `(Whitespace)Formatter` (which actually is two different formatters: a code formatter and a javadoc formatter). In fact, it seems to be a good way to separate concerns.

When going down this multi-pass road, the only thing that bothers me with the current implementation is that we repeatedly do the same work and emit a new string in each pass. Maybe we can parse the source only once into some representation that every CodeFormatter/JavadocFormatter/Orderer/Remover/whatever can work with efficiently. After parsing the source into the intermediate representation, the user chooses which formatters to apply and afterwards generates a string from or writes the representation to a Writer/CharSink.

Then again, I don't know exactly how formatting is implemented right now and if implementing this idea would be worth the effort.

**Comment by cushon** [comment]
I agree it would be better to parse everything once. It would complicate the implementation, though, and the current approach seems to perform well enough in practice. 

SortImports doesn't parse anything, it just tokenizes imports at the beginning of the file. And the javadoc formatter processes individual comments. So the duplicated effort is mainly between the unused import pass and the actual formatting logic.

**Comment by cushon** [comment]
The latest release enables import sorting by default in the CLI.

Using `ImportOrderer` and `RemoveUnusedImports` directly is still the only way to do it programatically, but we may revisit that.

**Comment by nmarkandeya** [comment]
Apologies for commenting on a older thread.

When I used the latest 1.7 version. I found  out individual unused import classes are removed. however the wildcard import statements are not. Is that an expected behaviour?

**Comment by cushon** [comment]
@nmarkandeya that is expected behaviour, there's some related discussion here: https://github.com/google/google-java-format/issues/113#issuecomment-272639684.
