### ISSUE TITLE
Plugin formats code back to 2-space indents after manually changing to 4-space indents.

### ISSUE THREAD

**Issue by mithuns** [google/google-java-format#373]
I have enterprise code base that is a mix of some java packages that have 2-space indents, and some have 4-space indents.
I am trying to make all of the code to use 4-space indents.
I am using IntelliJ to edit code.
IntelliJ detects the space indents , and shows at the right bottom corner, from where I select all the code and switch it to 4-space indents. 

![image](https://user-images.githubusercontent.com/3937267/57891260-65841980-7800-11e9-8fd7-83193df95a1a.png)

Code changes before my eyes, I can see IntelliJ marking lines that got modified.

I go to terminal , run the [fmt-maven-plugin|https://github.com/coveo/fmt-maven-plugin] which in turn uses this code.

`mvn fmt:format
`
That then formats the file back to 2-space indents.
Why ? I have no idea.

**Comment by talios** [comment]
On 17 May 2019, at 10:36, Mithun wrote:

> `mvn fmt:format `
> That then formats the file back to 2-space indents.
> Why ? I have no idea.

Surely that's just because google-format IS 2sp indented. So the maven plugin formats to 2 spaces, your intelliJ file formats to 4...  and you're going in circles...

Mark

---
"The ease with which a change can be implemented has no relevance at all to whether it is the right change for the (Java) Platform for all time." &mdash; Mark Reinhold.

Mark Derricutt
http://www.theoryinpractice.net
http://www.chaliceofblood.net
http://plus.google.com/+MarkDerricutt
http://twitter.com/talios
http://facebook.com/mderricutt

**Comment by mithuns** [comment]
Oh shoot, had no idea about that being the default behaviour.
So, I think I should not run this after modifying the space indents to 4-space indents.
Thank you , is there a formal place where this is listed ?

**Comment by talios** [comment]
@mithuns https://google.github.io/styleguide/javaguide.html#s4.2-block-indentation

Google Style is 2sp indent.  The formatter is also strict - so it's not a "default" behaviour, it is THE behaviour.

**Comment by eaftan** [comment]
@talios is correct. Google Style requires 2-space indents, and google-java-format implements Google Style.

**Comment by mithuns** [comment]
Then the question is, why is this plugin not changing all of code which has 4-space indent to 2-space indents ?

**Comment by eaftan** [comment]
I'm not sure.  You'd have to ask the developer of the Maven plugin.

**Comment by sormuras** [comment]
> Then the question is, why is this plugin not changing all of code which has 4-space indent to 2-space indents ?

Perhaps those lines are _indent continuation lines_? If yes, see https://google.github.io/styleguide/javaguide.html#s4.5.2-line-wrapping-indent for details.

**Comment by talios** [comment]
@eaftan @mithuns Unfortunately that doesn't seem to be my maven plugin used in this instance so I can't comment on that one. Mine ( https://github.com/talios/googleformatter-maven-plugin ) has an option of only touching modified files, so I'm not sure if the one you're using is also doing something similar?

**Comment by Alice52** [comment]
> Google Sty

Can I config this rule in idea? I want the indent is 4 space. Thanks.
