### ISSUE TITLE
Add support for IntelliJ 2019.2

### ISSUE THREAD

**Issue by sormuras** [google/google-java-format#375]
IntelliJ 2019.2 is currently in EAP, would be nice to update the plugin to support it.

**Comment by nicholasq** [comment]
second this.

**Comment by mcalic** [comment]
Same here. Please update plugin. Thanks!

**Comment by plumpy** [comment]
Uploaded a version that will work with 2019.2.

**Comment by sormuras** [comment]
![image](https://user-images.githubusercontent.com/2319838/60979910-ca0cb200-a333-11e9-9bec-fa0ff57203ef.png)

_Updating..._

**Comment by PhilippWendler** [comment]
@plumpy Could we please also get an updated Eclipse plugin? There doesn't even exist a version for google-java-format 1.7 yet. (#331)

**Comment by plumpy** [comment]
Sorry, I don't know anything about Eclipse.
