### ISSUE TITLE
Longer string line not formatted to multiple lines

### ISSUE THREAD

**Issue by jitendratheta** [google/google-java-format#376]
For example:
String foo =  "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna";

Does not get formatted with line break as

String foo =
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor"
        + " incididunt ut labore et dolore magna";

Shouldn't this be a feature given by the library? 
This kind of formatting is supported by IDEs for example Idea IntelliJ

**Comment by PhilippWendler** [comment]
Related to #122

**Comment by cushon** [comment]
The latest version wraps string literals:

```
google-java-format T.java
class T {
  String foo =
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt"
          + " ut labore et dolore magna";
}
```
