### ISSUE TITLE
Indentation

### ISSUE THREAD

**Issue by sudiptasish** [google/google-java-format#378]
I observed that google formatter sets the indentation to 2 white spaces (instead of 4 white spaces). Note that, with 2 spaces, it clutters the codebase. It becomes really hard to read. We need to understand that "Coding is an art". A good developer certainly does not want his/her code to look untidy. Even the conventional IDE (JetBrains, Netbeans, Eclipse, Jdeveloper) comes with the default indentation as 4. So why google formatter is changing the indentation to 2 ? What is the rationale ??

**Comment by nglorioso** [comment]
`google-java-format` enforces the rules of the Google Java Style Guide, which explicitly specifies a 2-space block indentation: https://google.github.io/styleguide/javaguide.html#s4.2-block-indentation

**Comment by kevinb9n** [comment]
@sudiptasish, the argument you're providing is really just a personal preference, not an objective claim about what leads to readability or tidiness. And that preference is not generally shared by Googlers.

Increased indentation leads to more artificial line-wraps, and Google's decision early on was that this does more harm than good. That decision has been stable for almost 20 years.

**Comment by sudiptasish** [comment]
@kevinb9n, reviving this old thread again (sorry I didn't notice your reply earlier)....

As mentioned above, All the modern IDEs (since their inception) are using the default indentation as 4. The JAVA code formatting guide, which was initially published by SUN (way back in late 90s), clearly mentions about the indentation, line wrapping, breaking method calls, etc, and all the IDEs (Eclipse, Netbeans, Intelli J) more or less follows the same. Because the conventions are enforced via IDE, hence there is NOO need for a separate formatting tool (like google formatter or whatever).

Much before these IDEs were introduced, people used to code in MS DOS env, or later in notepad, editplus, etc, where they followed 1 or 2 indentation for their own convenience. We need to understand, those days the screen resolution was less and the screen size was merely 80 characters. Sometimes, by mistake, people would add extra indentation, or mess up with the format. In such cases a formatting tool is needed, and NOT for code written in modern IDE.

**Comment by cushon** [comment]
You suggested re-opening this in #444, but I think @kevinb9n covered our thinking here. We do not have plans to revisit the use of 2-space indentation in the style guide.

Can you clarify what the outcome you're hoping to see here is?

The goal of this project is to provide a formatter that complies with the Google Java style guide. Before we created `google-java-format`, we put a lot of effort into configuring the Eclipse and IntelliJ formatters to follow our style rules, and eventually found that the only way to get the results we wanted was to create a new formatter.

If you use a different style guide (like the Sun Java one), or prefer a different formatter (like the default Eclipse or IntelliJ formatters) though, that's OK! We're not saying everyone should use this formatter, or use 2-space indentation.
