### ISSUE TITLE
Support alternative file encoding

### ISSUE THREAD

**Issue by davido** [google/google-java-format#379]
The file encoding was hard coded in: https://github.com/google/google-java-format/commit/2a6c5f4ba94fe57dd804229fe33f51849d93314d to `UTF-8`. Running the gjf over files with encoding different from `UTF-8` would corrupt them.

**Comment by sormuras** [comment]
`UTF-8` is mandated

https://google.github.io/styleguide/javaguide.html#s2.2-file-encoding

**Comment by davido** [comment]
> UTF-8 is mandated

In Western Europe other encodings than UTF-8 are very common.

Note, that in the same style guide document, you linked to encoding section, 2-space indentation level is mandated: [1]. "Block indentation: +2 spaces". Nevertheless, this gjf tool supports 4-space indentation level as well:

```
  $ java -jar W:\junk\google-java-format-1.7-all-deps.jar
  [...]
  --aosp, -aosp, -a
  Use AOSP style instead of Google Style (4-space indentation).
  [...]
```

Conclusion: the style guide document and gjf tool are two different things.

[1] https://google.github.io/styleguide/javaguide.html#s4.2-block-indentation

**Comment by tbroyer** [comment]
AOSP style is https://source.android.com/setup/contribute/code-style
Google style is https://google.github.io/styleguide/javaguide.html
Google Java Format supports both.

**Comment by cushon** [comment]
https://github.com/google/google-java-format/wiki/FAQ#i-just-need-to-configure-it-a-bit-differently-how is also related.

There are no plans to add configuration to support other encodings at this time.
