### ISSUE TITLE
In place format does not preserve file attributes

### ISSUE THREAD

**Issue by basil** [google/google-java-format#38]
## Steps to reproduce

1. Create a Java file whose permissions do not match the default permissions for new files on your system. For example, if your Linux system's default permissions for new files are to not have the execute bit set, create a file with the execute bit set; or if your Windows system's default permissions for new files are to have the execute bit set, create a file with the execute bit not set.
2. Run `google-java-format` with the `-i` option to format the file in place.

## Expected result

The file is formatted in place and retains its non-default permissions.

## Actual result

The file is formatted in place, but its permissions revert to the default permissions.

**Comment by cushon** [comment]
Thanks for the report and the patch. Copying temp files around wasn't really necessary, and I cleaned things up to avoid doing that in ec35358d9443afd1cef4ef615ed63e21f01f40bf. That change should also solve this problem.

**Comment by basil** [comment]
Thanks for taking a look. Commit ec35358 does indeed solve this problem for me.
