### ISSUE TITLE
Support Text Blocks (JEP 368)

### ISSUE THREAD

**Issue by sormuras** [google/google-java-format#382]
> A text block is a multi-line string literal that avoids the need for most escape sequences, automatically formats the string in a predictable way, and gives the developer control over format when desired. This is a preview language feature in JDK 13.

Syntax and more details at ~https://openjdk.java.net/jeps/355~ https://openjdk.java.net/jeps/368

Formatting a Java source file...
`java -jar google-java-format-1.7-all-deps.jar TextBlock.java`

...that contains Text Blocks...
```java
public class TextBlock {
  public static void main(String... args) {
    var block = """

    java --enable-preview --s\\o/urce 14 TextBlock.java
    openjdk                   |              -|-
    14-ea                     /\\  o           /\\
    2020-03-17
    """.indent(6);

    System.out.print(block);
  }
}
```

...fails with:
```
TextBlock.java:3:20: error: unclosed string literal
TextBlock.java:5:13: error: ';' expected
TextBlock.java:5:19: error: not a statement
TextBlock.java:5:30: error: ';' expected
TextBlock.java:5:31: error: illegal character: '\'
TextBlock.java:5:32: error: illegal character: '\'
TextBlock.java:5:34: error: not a statement
TextBlock.java:5:39: error: ';' expected
TextBlock.java:6:13: error: ';' expected
TextBlock.java:7:33: error: illegal character: '\'
TextBlock.java:7:32: error: not a statement
TextBlock.java:7:34: error: illegal character: '\'
TextBlock.java:7:50: error: illegal character: '\'
TextBlock.java:7:49: error: not a statement
TextBlock.java:7:51: error: illegal character: '\'
TextBlock.java:9:8: error: unclosed string literal
```

**Comment by sormuras** [comment]
Some errors are reported when calling `java` with `--enable-preview`. Seems like that option isn't passed to the internal `javac` instance, methinks.

**Comment by sormuras** [comment]
Or is error-prone not there, yet?

https://github.com/google/google-java-format/blob/0a449a547ca5c3d89bf6c459cc74f706467ecca6/pom.xml#L99

**Comment by sormuras** [comment]
How about omit Text Blocks entirely from formatting?

**Comment by talios** [comment]
@sormuras if existing formatting changes the indent position of the start of the block, GJF should reindent the text block to preserve the gray-space eliding by the compiler. Reformatting shouldn't break tests, which that may.

**Comment by sormuras** [comment]
> if existing formatting changes [...]

Lines contributing to a `"""`-`String` literal shouldn't be touched at all - as an initial work-around.

**Comment by sormuras** [comment]
> if existing formatting changes the indent position of the start of the block, [...]

IIRC, the position of the start `"""` does not influence the white-space trim. The terminating `"""` does.

See https://blog.codefx.org/java/text-blocks/ (as jdk.java.net doesn't work at the moment)

**Comment by sormuras** [comment]
Second Preview of Text Blocks issued: https://openjdk.java.net/jeps/368

> **New escape sequences**
> To allow finer control of the processing of newlines and white space, text blocks support two additional escape sequences not available in ordinary string literals.
> First, the `\<line-terminator>` escape sequence explicitly suppresses the insertion of a newline character.
> ...
> Second, the `\s` escape sequence simply translates to a single space (`\u0020`).
> ...

Updated issue title accordingly.

**Comment by cushon** [comment]
#436
