### ISSUE TITLE
Checksums for releases

### ISSUE THREAD

**Issue by a1exsh** [google/google-java-format#383]
I've created a light-weight git pre-commit hook script that downloads and caches the all-deps jar to re-format all changed .java files: https://github.com/a1exsh/google-java-format-git-pre-commit-hook

Before running the .jar I'd like to verify its integrity.  It would help me greatly if you could provide checksums (such as SHA-256) for the released files.

Failing that, I guess one could download the .jar using maven, but that is an extra dependency, which I would like to avoid.

And thanks for working on this great tool! :)

**Comment by Stephan202** [comment]
All artifacts deployed to Maven Central are stored alongside their MD5 and SHA1 hash ([example](http://repo1.maven.org/maven2/com/google/googlejavaformat/google-java-format/1.7/)). Is this what you're looking for?

**Comment by a1exsh** [comment]
Exactly, thanks for pointing this out!

Given that there is a GPG signature provided, I would like to use that instead of SHA.  Do you know by chance where do I get the public key for verification?  I'm getting "Can't check signature: No public key" from gpg on the .asc file.

**Comment by Stephan202** [comment]
@a1exsh while I haven't tested this myself, IIUC you need to download the public key from MIT's key server:
- [This documentation](https://blog.sonatype.com/2010/01/how-to-generate-pgp-signatures-with-maven/) describes the steps which people _uploading_ artifacts must follow.
- [This blog post](http://branchandbound.net/blog/security/2012/08/verify-dependencies-using-pgp/) describes how end users (you ;) ) can verify the signature.

**Comment by a1exsh** [comment]
Thanks again. :)
