### ISSUE TITLE
Wildcard import should return failure for dry run

### ISSUE THREAD

**Issue by santhoshTpixler** [google/google-java-format#392]
WRT #113 It is not possible to expand the wildcards in the import statements. But the dry run should report that there are changes to needed to comply with the Google java code style.

We use ` java -jar google-java-format-1.7-all-deps.jar --set-exit-if-changed -n $(find . -type f -name "*.java")` in the CI to verify the code formatting. But wildcards in the import statement does not affect the exit code. This leads to code being accepted even if it is not in Google java code style(Only wild card imports).

**Comment by awturner** [comment]
There are lots of things that violate the style guide which aren't detected by GJF. For example, the rule that [overloads should appear together](https://google.github.io/styleguide/javaguide.html#s3.4.2-ordering-class-contents).

GJF fixes whitespace/wrapping issues only.

**Comment by awturner** [comment]
To be fair, I think that the description is misleading:

"""
google-java-format is a program that reformats Java source code to comply
with Google Java Style.
"""

Saying "reformats **whitespace in** Java source code" would make the scope
of GJF clearer.
