### ISSUE TITLE
Inline array line wrapping is surprising

### ISSUE THREAD

**Issue by swankjesse** [google/google-java-format#4]
Array elements are +6 where I'd expect +8. (IntelliJ does +8).

```
        csvWriter.writeNext(
            new String[] {
              Rest.formatIso8601UtcDate(row.date),
              row.movementType.summary(),
              "",
              "",
              "",
              row.amount.currency().name(),
              Long.toString(row.amount.cents())
            });
```

**Comment by kevinb9n** [comment]
This come straight out of the Google Style Guide
<https://google-styleguide.googlecode.com/svn/trunk/javaguide.html>. For
array literals you have the choice between

(a) in-line style -- which says you just start with this

  csvWriter.writeNext(new String[] {
Rest.formatIso8601UtcDate(row.date), row.movementType.summary(), "",
"", "", row.amount.currency().name(),
Long.toString(row.amount.cents()) });

... and then follow the standard "prefer to break at a higher
syntactic depth" guidelines.  Or

(b) formatting the array literal *as if it is a block* ... which gives
you exactly what you see.

The formatter prefers (b) when it can't get it all on one line.




On Fri, May 15, 2015 at 8:53 AM, Jesse Wilson <notifications@github.com>
wrote:

> Array elements are +6 where I'd expect +8. (IntelliJ does +8).
>
>         csvWriter.writeNext(
>             new String[] {
>               Rest.formatIso8601UtcDate(row.date),
>               row.movementType.summary(),
>               "",
>               "",
>               "",
>               row.amount.currency().name(),
>               Long.toString(row.amount.cents())
>             });
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/google-java-format/issues/4>.
>



-- 
Kevin Bourrillion | Java Librarian | Google, Inc. | kevinb@google.com

**Comment by kevinb9n** [comment]
(Appropriate section is
https://google-styleguide.googlecode.com/svn/trunk/javaguide.html#s4.8.3.1-array-initializers
)

On Fri, May 15, 2015 at 9:09 AM, Kevin Bourrillion <kevinb@google.com>
wrote:

> This come straight out of the Google Style Guide
> <https://google-styleguide.googlecode.com/svn/trunk/javaguide.html>. For
> array literals you have the choice between
>
> (a) in-line style -- which says you just start with this
>
>   csvWriter.writeNext(new String[] { Rest.formatIso8601UtcDate(row.date), row.movementType.summary(), "", "", "", row.amount.currency().name(), Long.toString(row.amount.cents()) });
>
> ... and then follow the standard "prefer to break at a higher syntactic depth" guidelines.  Or
>
> (b) formatting the array literal *as if it is a block* ... which gives you exactly what you see.
>
> The formatter prefers (b) when it can't get it all on one line.
>
>
>
>
> On Fri, May 15, 2015 at 8:53 AM, Jesse Wilson <notifications@github.com>
> wrote:
>
>> Array elements are +6 where I'd expect +8. (IntelliJ does +8).
>>
>>         csvWriter.writeNext(
>>             new String[] {
>>               Rest.formatIso8601UtcDate(row.date),
>>               row.movementType.summary(),
>>               "",
>>               "",
>>               "",
>>               row.amount.currency().name(),
>>               Long.toString(row.amount.cents())
>>             });
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/google/google-java-format/issues/4>.
>>
>
>
>
> --
> Kevin Bourrillion | Java Librarian | Google, Inc. | kevinb@google.com
>



-- 
Kevin Bourrillion | Java Librarian | Google, Inc. | kevinb@google.com
