### ISSUE TITLE
Posibility to enable plugin for project 

### ISSUE THREAD

**Issue by siplo** [google/google-java-format#401]
Hi, 
when I by mistake did not enable plugin for project during first start I don't see any possibilities to do it in future. Am I right ? It will be nice to have this option to re-enable/disable plugin not only during first start. 

This is definitely not a bug but much more nice to have feature. If there is some workaround please let me know.

**Comment by tbroyer** [comment]
If you're talking about IntelliJ IDEA (or Android Studio), you'll find it in the settings.

**Comment by sormuras** [comment]
![image](https://user-images.githubusercontent.com/2319838/66456266-75312280-ea6d-11e9-967e-9ecbf92c6410.png)

_Thomas was faster, but I already created a screenshot..._

**Comment by siplo** [comment]
Sorry, I forgot to say thnaks
