### ISSUE TITLE
Can we specify the style, or modfiy gjf to use a slightly customized style? 

### ISSUE THREAD

**Issue by nipunarora** [google/google-java-format#407]
We have a somewhat customized format, which differs slightly from google code style. Can we modify gjf to use that? If so, what's the recommended way to do so?

**Comment by eaftan** [comment]
Sorry, but we don't support configuration.  See https://github.com/google/google-java-format/wiki/FAQ#i-just-need-to-configure-it-a-bit-differently-how for an explanation.
