### ISSUE TITLE
core/pom.xml uses outdated Javadoc links

### ISSUE THREAD

**Issue by anthonyvdotbe** [google/google-java-format#408]
These [outdated links](https://github.com/google/google-java-format/blob/master/core/pom.xml#L89) cause build warnings

**Comment by cushon** [comment]
The PR was merged in https://github.com/google/google-java-format/commit/81aaab96cdde86e52863827b6bb09f5583707d89#diff-357e4854869b2e21c38b1b437f11095a, thanks!
