### ISSUE TITLE
SortImports option is ignored

### ISSUE THREAD

**Issue by sherter** [google/google-java-format#42]
No matter which `SortImports` option I set (`ONLY`, `ALSO` or `NO`), the imports are never sorted and it always returns the same result. Am I missing something here? 
```
public static void main(String[] args) throws FormatterException {
  JavaFormatterOptions options = new JavaFormatterOptions(JavadocFormatter.NONE, Style.GOOGLE, SortImports.ONLY);
  Formatter formatter = new Formatter(options);
  String result = formatter.formatSource("package com.google.example;\n" +
                "\n" +
                "import com.google.common.base.Preconditions;\n" +
                "\n" +
                "import org.junit.runner.RunWith;\n" +
                "import org.junit.runners.JUnit4;\n" +
                "\n" +
                "import java.util.List;\n" +
                "\n" +
                "import javax.annotations.Nullable;\n" +
                "\n" +
                "import static org.junit.Assert.fail;\n" +
                "import static com.google.truth.Truth.assertThat;\n" +
                "\n" +
                "@RunWith( JUnit4.class ) public class SomeTest  {}");
  System.out.println(result);
}
```

**Comment by sherter** [comment]
Seems like the `Formatter` can't do imports sorting at all. This is all done in `FormatFileCallable` with a different `SortImports` enum, which is not part of the public API. The principle of **most** astonishment definitely applies here :wink:
(to be honest, the whole API doesn't feel like a `1.0` version, more like a `0.1`.... typo? :smile:)

**Comment by cushon** [comment]
Yep, currently import ordering only works with the cli. It's work in progress.

Adding it to the methods in the api that return strings would be easy, but some details need to be sorted out for the methods that do partial formatting or return replacement ranges.

**Comment by talios** [comment]
Look forward to seeing this in a release, so I can also plug it into my https://github.com/talios/googleformatter-maven-plugin Maven plugin.

**Comment by sherter** [comment]
The same goes for the `JavadocFormatter` option. JavaDoc is _always_ formatted, even if the formatter is set to `JavadocFormatter.NONE`. I'm wondering why you make an API public although it's not providing any functionality.

**Comment by cushon** [comment]
>  JavaDoc is always formatted, even if the formatter is set to JavadocFormatter.NONE.

Do you have a repro?

**Comment by sherter** [comment]
I wouldn't expect the text to change in any way in the example below. Or is this not how it works?

```
public static void main(String[] args) throws FormatterException {
    JavaFormatterOptions options = new JavaFormatterOptions(
            JavaFormatterOptions.JavadocFormatter.NONE,
            JavaFormatterOptions.Style.GOOGLE,
            JavaFormatterOptions.SortImports.ALSO);
    Formatter formatter = new Formatter(options);
    String result = formatter.formatSource(
            "/**\n" +
                    "  * This is (was) malformed javadoc.\n" +
                    "  * <pre>\n" +
                    "  System.err.println\n" +
                    "  * </pre>\n" +
                    "  */\n");
    System.out.println(result);
}
```

**Comment by cushon** [comment]
The implementation makes a distinction between normalizing leading `*` and other javadoc formatting, like wrapping lines.

Part of the reason that the configuration is rough around the edges is that non-configurability is a stated goal of the formatter. Javadoc formatting and import sorting are off by default because they're work in progress. Once they're done, they'll be on by default.

**Comment by sherter** [comment]
Ah okay, I didn't know that. And I was wrong about the configuration API not providing any functionality: The style option _does_ work as expected ;)
Does "on by default" mean that the configuration option will be removed from the API eventually?

**Comment by cushon** [comment]
There's an update on import sorting in #37. I'm still not sure how it should look in the API, let me know if you have ideas.

And the javadoc formatting is now more polished, and has been enabled by default.
