### ISSUE TITLE
Publish current snapshot

### ISSUE THREAD

**Issue by sormuras** [google/google-java-format#43]
**0.1-SNAPSHOT** is here:
https://oss.sonatype.org/content/repositories/snapshots/com/google/googlejavaformat/

**1.1-SNAPSHOT** is missing.

**Comment by cushon** [comment]
Fixed: https://oss.sonatype.org/content/repositories/snapshots/com/google/googlejavaformat/google-java-format/1.1-SNAPSHOT/

**Comment by sormuras** [comment]
Thanks!

**Comment by sormuras** [comment]
Snapshot packages are out of date: https://oss.sonatype.org/content/repositories/snapshots/com/google/googlejavaformat/google-java-format/1.1-SNAPSHOT

Some rights issue, right?

> util/publish-snapshot-on-commit.sh
/home/travis/build.sh: line 45: util/publish-snapshot-on-commit.sh: Permission denied

**Comment by cushon** [comment]
Thanks for noticing that, looks like it was accidentally made non-executable.
