### ISSUE TITLE
8 instead of 4 whitespaces indented in expect block

### ISSUE THREAD

**Issue by stephaniewang526** [google/google-java-format#430]
Hi,
I've been using `mvn com.coveo:fmt-maven-plugin:format` command to format my code every time before a commit. I just realized lately that the plugin has been formatting expect block code with 8 whitespaces instead of 4. Here's an example: https://github.com/googleapis/java-bigquery/blob/aabf02ac76ac050154422eee79569a81b7d00038/google-cloud-bigquery/src/test/java/com/google/cloud/bigquery/TableDataWriteChannelTest.java#L108

Is this an expected behavior? Is this the Google style? Or is this an issue to be fixed? Thanks!

**Comment by lowasser** [comment]
Possibly relevant: https://github.com/google/google-java-format/wiki/FAQ#google-java-format-always-follows-the-rectangle-rule-right-no-exceptions

**Comment by stephaniewang526** [comment]
Got it -- so this is expected. Thanks for your response.
