### ISSUE TITLE
FormatterException

### ISSUE THREAD

**Issue by RatanRSur** [google/google-java-format#438]
google-java-format 1.7

All other info in this issue:
https://github.com/diffplug/spotless/issues/526

**Comment by cushon** [comment]
Do you have a repro, e.g. a self-contained file that causes the `google-java-format` CLI or API to crash? It's not clear from the other bug whether this is an issue in the formatter, or in spotbugs, or something else.

**Comment by RatanRSur** [comment]
I think this should do it:

`google-java-format ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/fastsync/FastSyncDownloaderTest.java`

from here:

https://github.com/hyperledger/besu/blob/9b33cd2695c4c9d480898bfdb4d2d2fb71acd4b2/ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/fastsync/FastSyncDownloaderTest.java

**Comment by cushon** [comment]
I can't reproduce, it looks like the file has a syntax error which `google-java-format` is correctly reporting:

```
curl https://raw.githubusercontent.com/hyperledger/besu/9b33cd2695c4c9d480898bfdb4d2d2fb71acd4b2/ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/fastsync/FastSyncDownloaderTest.java | google-java-format -
...
<stdin>:486:54: error: '(' expected
```

I see a similar error from javac for that file:

```
X.java:486: error: '(' expected
  private <T> CompletableFuture<T> CompletableFuture.failedFuture(final Throwable error) {
                                                    ^
X.java:486: error: invalid method declaration; return type required
  private <T> CompletableFuture<T> CompletableFuture.failedFuture(final Throwable error) {
                                                     ^
2 errors
```
