### ISSUE TITLE
Does formatter check the naming of the local variables?

### ISSUE THREAD

**Issue by tonyyang-svail** [google/google-java-format#440]
Hi there.

I am wondering if `google-java-format` supports checking the naming of the local variables, which should be camelCase according to the [style guide](https://google.github.io/styleguide/javaguide.html#s5.2.7-local-variable-names).

A quick experiment shows it doesn't though. So I am double checking if I am using the library correctly.

**To Reproduce**
```bash
$ java -jar /usr/local/bin/google-java-format-1.6-all-deps.jar --replace /tmp/HelloWorld.java
$ cat /tmp/HelloWorld.java
class HelloWorld {
  // Your program begins with a call to main().
  // Prints "Hello, World" to the terminal window.
  public static void main(String args[]) {
    String hello_world = "Hello World"; // this line should be changed
    System.out.println(hello_world);
  }
}
```

**Comment by eaftan** [comment]
No, it doesn't check naming.  I recommend using Checkstyle for that.  They provide a Google Style configuration: https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/google_checks.xml

Note that AFAIK Google is not involved in that Checkstyle configuration, so please report any bugs to them and not to us.
