### ISSUE TITLE
Indentation - See issue#378

### ISSUE THREAD

**Issue by sudiptasish** [google/google-java-format#444]
@kevinb9n, reviving this old thread again (sorry I didn't notice your reply earlier)....

As mentioned above, All the modern IDEs (since their inception) are using the default indentation as 4. The JAVA code formatting guide, which was initially published by SUN (way back in late 90s), clearly mentions about the indentation, line wrapping, breaking method calls, etc, and all the IDEs (Eclipse, Netbeans, Intelli J) more or less follows the same. Because the conventions are enforced via IDE, hence there is NO need for a separate formatting tool (like google formatter or whatever).

Much before these IDEs were introduced, people used to code in MS DOS env, or later in notepad, editplus, etc, where they followed 1 or 2 indentation for their own convenience. We need to understand, those days the screen resolution was less and the screen size was merely 80 characters. Sometimes, by mistake, people would add extra indentation, or mess up with the format. In such cases a formatting tool is needed, and NOT for code written in modern IDE.

**Comment by cushon** [comment]
(Let's keep the discussion in #378, it looks like you also commented there.)

**Comment by sudiptasish** [comment]
Sure @cushon , I don't mind.
But can somebody please open #378 ?
