### ISSUE TITLE
Hidden Sort Imports Option

### ISSUE THREAD

**Issue by amc6** [google/google-java-format#46]
I was wondering what the status of `--sort-imports` is. I'd like to use it, but I wasn't sure if it is fully supported since its current status is hidden. https://github.com/google/google-java-format/blob/ded387ee1a83d5c3d3952e84c1f7d8690e618e99/core/src/main/java/com/google/googlejavaformat/java/Main.java#L95

**Comment by cushon** [comment]
It should work through the cli, if you see issues please report them.

The status internally is that the style guide needs to be updated before we start using it (see [this comment](https://github.com/google/google-java-format/issues/37#issuecomment-205914994)). It also isn't wired up to the api yet: #42.

**Comment by amc6** [comment]
Thanks
