### ISSUE TITLE
Publish GJF 1.8 to Maven, so `ktfmt` can use it

### ISSUE THREAD

**Issue by cgrushko** [google/google-java-format#466]
* [`ktfmt`](https://github.com/facebookincubator/ktfmt) is currently built by submoduling google-java-format's master branch.
* This makes it impossible to use `ktfmt` by pointing at its Maven coordinates. (https://github.com/facebookincubator/ktfmt/issues/30)

Is it possible to publish the latest changes to Maven?

cc @cushon @strulovich

**Comment by cushon** [comment]
Done: https://github.com/google/google-java-format/releases/tag/google-java-format-1.8
