### ISSUE TITLE
First comment is removed (partially)

### ISSUE THREAD

**Issue by sherter** [google/google-java-format#47]
```
Formatter formatter = new Formatter();
String result = formatter.formatSource(
  "/*\n" +
  " * my comment */");
System.out.println(result); // prints only "/*" (is the same for javadoc comments)
```
Seems like there is a problem if there is no `\n` after the first comment. If there is one (or any other valid source code) it works fine. It also seems to only effect the very first comment (or set of comments, if there is nothing else in between) in the file. Any further comment is printed as expected, even if there is no newline after it.

**Comment by cushon** [comment]
Thanks for reporting this. I think it only affects files that end in a multi-line comment, and have no terminal newline. I'm working on a fix.
