### ISSUE TITLE
Adding section VScode in the Readme file

### ISSUE THREAD

**Issue by bavly** [google/google-java-format#488]
Hello,

This enhancement, when I have opened the project I searched on the Readme how to use the project in VScode but I did not find.

**Comment by yanisdb** [comment]
I've been searching for the same thing. There is no section for VSCode. But is it even possible to use in vscode ?

**Comment by xbeta** [comment]
There are lots of other non-official google-java-format code style linter, but none of them actually matched 100% with this official style. I have been forced to use Intellij where my favorite editor of choice (VScode) do not have official support.

**Comment by natros** [comment]
I’ve never used vcode but I’m not using this plugin with intellij, instead, I’m running the standalone jar compiled to native executable with graallvm. Intellij includes a file watcher plugin that calls the executable whenever the file is saved. For bigger files, it’s faster than the plugin. I expect the vscode has some kind of file watcher that can do the same.

**Comment by bavly** [comment]
The idea is that the project releated to code format & VScode now one of largest editor people in tech using it, when i see the project i was need to try it on VScode but couldn't find official document.

**Comment by xbeta** [comment]
Actually I tried Seth's change on VScode and it works well

https://www.sethvargo.com/using-google-java-format-with-vs-code/

**Comment by bavly** [comment]
@xbeta I will try these steps.

**Comment by nedtwigg** [comment]
If you use [spotless](https://github.com/diffplug/spotless/tree/main/plugin-gradle), then you can also use its [VS Code plugin](https://marketplace.visualstudio.com/items?itemName=richardwillis.vscode-spotless-gradle).
