### ISSUE TITLE
Eclipse 4.5+ plug-in

### ISSUE THREAD

**Issue by sormuras** [google/google-java-format#49]
> JDT now provides an extension point (org.eclipse.jdt.core.javaFormatter) to allow third-party source code formatters as extensions.
> Copied from https://www.eclipse.org/eclipse/news/4.5/jdt.php#JavaFormatter

Would be great to use this formatter there.

**Comment by sormuras** [comment]
#52 uses `org.eclipse.jdt.core.javaFormatter` https://bugs.eclipse.org/bugs/show_bug.cgi?id=449262

**Comment by cushon** [comment]
I released a build of the plugin: https://github.com/google/google-java-format#eclipse

If anyone has suggestions for improving the way it's being built / packaged I'm happy to take PRs, but I think we can declare victory on this bug for now.
