### ISSUE TITLE
goJF throws a matching constructor not found issue

### ISSUE THREAD

**Issue by ralph-perera** [google/google-java-format#490]
I have upgraded google-java-format 1.8, it throws the following error.

`Could not find matching constructor for: com.google.googlejavaformat.java.JavaFormatterOptions(com.google.googlejavaformat.java.JavaFormatterOptions$Style)`

Note - I am using spring boot 2.3.0 gradle 6.3

When I use google-java-format 1.7 it complains most of files have syntax errors even though they don't.

And if I downgrade to google-java-format 1.6, it works fine.

**Comment by JamesGuthrie** [comment]
@ralph-perera which gradle plugin are you using? If you're using [sherter/google-java-format-gradle-plugin](https://github.com/sherter/google-java-format-gradle-plugin) then you're getting this error because that plugin has not been patched to work with gJF 1.8, see https://github.com/sherter/google-java-format-gradle-plugin/issues/46

**Comment by cushon** [comment]
The signature of the `JavaFormatterOptions` constructor changed in https://github.com/google/google-java-format/commit/bd176704e73771d1dd582d2cd0ae2f8859ae9ca6, but the constructor is also `private`.

**Comment by ralph-perera** [comment]
@JamesGuthrie yes I am using sherter/google-java-format-gradle-plugin Didn't realize it was the problem. Guess I have to go with a work around. Thanks for the quick reply.

**Comment by JamesGuthrie** [comment]
@ralph-perera Currently there isn't a "real" workaround. We solved the problem by switching to the [spotless](https://github.com/diffplug/spotless) plugin.

**Comment by sherter** [comment]
> The signature of the `JavaFormatterOptions` constructor changed in [bd17670](https://github.com/google/google-java-format/commit/bd176704e73771d1dd582d2cd0ae2f8859ae9ca6), but the constructor is also `private`.

Actually, the constructor was public in [v1.0](https://github.com/google/google-java-format/blob/google-java-format-1.0/core/src/main/java/com/google/googlejavaformat/java/JavaFormatterOptions.java#L90). Only in [v1.1](https://github.com/google/google-java-format/blob/google-java-format-1.1/core/src/main/java/com/google/googlejavaformat/java/JavaFormatterOptions.java#L65) it was made private.

I added support for google-java-format v1.8 in [this commit](https://github.com/sherter/google-java-format-gradle-plugin/commit/975a0591f808b05171626022cd3c36424520bbec). A new release of the plugin will follow soon.

**Comment by sherter** [comment]
Plugin version 0.9 with support for google-java-format v1.8 was released. This can be closed I guess.
