### ISSUE TITLE
Idea comment style and line breaks

### ISSUE THREAD

**Issue by jiqimaogou** [google/google-java-format#496]
I use google java format in intelj,

Line comment at first column is enabled.

Keep when formatting: Line breaks is enabled.

can you provide an option to disable them?

**Comment by plumpy** [comment]
All formatting options in IntelliJ are ignored when the `google-java-format` plugin is used.

See [the FAQ entry about this](https://github.com/google/google-java-format/wiki/FAQ#i-just-need-to-configure-it-a-bit-differently-how).

Feel free to reopen this if you think that didn't address your question, thanks!
