### ISSUE TITLE
Long line with string concatenation gets suspiciously short when formatted

### ISSUE THREAD

**Issue by oliviercailloux** [google/google-java-format#504]
Using the formatter transforms the following line:
```
LOGGER.info("Found {} piece" + (informationalValue >= 2 ? "s" : "")
    + " of login information in file.", informationalValue);
```
into:
```
LOGGER.info(
    "Found {} piece"
        + (informationalValue >= 2 ? "s" : "")
        + " of login information in file.",
    informationalValue);

```
which is, I suppose, not intended by the style guide. The first version is more readable and does not go beyond the 100 characters limit; and the eclipse file provided by google-java-format formats this snippet as in the first version.

**Comment by tbroyer** [comment]
See https://github.com/google/google-java-format/wiki/The-Rectangle-Rule

Also https://github.com/google/google-java-format/wiki/FAQ#why-didnt-it-leave-my-perfectly-valid-code-alone

Your snippet does not fit the "rectangle rule", so it *had* to be reformatted.

This, to me, is the intended behavior.

**Comment by oliviercailloux** [comment]
Thanks. Then, I guess the problem is with the Eclipse formater, which did leave my “perfectly valid code” alone. Should I file a bug somewhere else?

**Comment by nick-someone** [comment]
To clarify:

* Is this is the Eclipse google-java-format plugin? (https://github.com/google/google-java-format#eclipse)
* If so, was the eclipse format run reformatting the whole file, or just changed lines (and was the line in question modified)?
* In your other formatter run, were you reformatting the whole file?

**Comment by oliviercailloux** [comment]
. Yes, this is the one I refer to, imported as `GoogleStyle` in the Eclipse Formatter preferences.
. The Eclipse format did reformat the sample code: it formatted the whole file; and if I change manually the line referred to, and re-run the Eclipse formatter, it reformats the line again as shown, consistently.
. I don’t understand. Which other formatter run?

**Comment by nick-someone** [comment]
I see you've edited the comment a bit, so to make sure I understand the situation you describe to see if there's a bug or unintended behavior:

* Your original code had:
```
LOGGER.info("Found {} piece" + (informationalValue >= 2 ? "s" : "")
    + " of login information in file.", informationalValue);
```
(which, according to g-j-f Rectangle Rule, *should be* reformatted)

* Now, using the eclipse integration of google-java-format, reformatting the file or modified line *successfully* reformats the code according to the rectangle rule.

* However, in your comment, it sounds like there might be an issue with the Eclipse formatter:
   > I guess the problem is with the Eclipse formater (I mean, the one provided by google-java-format), which did leave my “perfectly valid code” alone.

which seems to imply that you would have expected the Eclipse formatter to format the code, but did not format the code.

If the Eclipse formatter is running correctly and reformatting the code (which your most recent comment suggests that it is doing), then I don't see there being a problem.

**Comment by oliviercailloux** [comment]
I am sorry for being very unclear. From the beginning, I meant that the eclipse integration of google-java-format erroneously reformats the code as is read in the first sample above, or leave it untouched if it is already as in the first sample above.

**Comment by nick-someone** [comment]
Ah, OK. I think I understand now:

* When running formatting in Eclipse, regardless of the original code, you get the `first sample` behavior
* When running formatting via `google-java-format` via the `fmt-maven-plugin`, you get the `second sample` behavior.

From the information you gave me, I suspect that your Eclipse formatting setup may not be an integration of the `google-java-format` binary, but instead a specific configuration of the Eclipse built-in formatter using the customizations found on [this github page](https://github.com/google/styleguide/blob/gh-pages/eclipse-java-google-style.xml), which will have a different behavior to the `google-java-format` binary.

Can you please confirm that your Eclipse integration is actually of the kind described on https://github.com/google/google-java-format#eclipse, and not just a customization of the Eclipse formatter?

**Comment by oliviercailloux** [comment]
You are right, I used the Eclipse built-in formatter using the customizations found on the google/styleguide page, where I was sent from coveooss/fmt-maven-plugin’s [README](https://github.com/coveooss/fmt-maven-plugin/blob/master/README.md). Thus, I suppose this bug report can be closed as invalid.

Incidentally, I am quite confused by the existence of two GitHub repositories, google/google-java-format and google/styleguide, seemingly talking about the same thing, but recommending different approaches for configuring Eclipse for Java formatting, with, apparently, important differences. Would it be adequate to mention the reason for existence of these two repositories and their recommended uses, perhaps, in the README of these two repositories? This would help prevent users from following the instructions of google/styleguide whereas they should rather follow google/google-java-format.

**Comment by oliviercailloux** [comment]
Perhaps it is as simple as deleting the `eclipse-java-google-style.xml` file from the google/styleguide repository, as it seems quite outdated (being three years old).

**Comment by tbroyer** [comment]
google-java-format will make sure your code respects the Google Style, but there's also "perfectly valid code" per that styleguide that GJF will reformat anyway.
So one could follow the Google Style without enforcing the "stricter" GJF subset. The Google Style leaves room for choices to developers, whereas GJF "imposes" a formatting (but therefore also eliminates any bikeshedding).
This is the difference between "finding violations and fixing them" (as most IDE formatters, IIUC), and ignoring any (most) original formatting (as does GJF, as described in https://github.com/google/google-java-format/wiki/FAQ#why-didnt-it-leave-my-perfectly-valid-code-alone)

**Comment by oliviercailloux** [comment]
Thanks. I still think that this deserves to be explained prominently in the README of one of the projects, or both. 

In any case, I suppose this bug report can be closed and I thank you again for your time and effort.
