### ISSUE TITLE
Error formatting switch blocks with arrow labels

### ISSUE THREAD

**Issue by skirkpatrick** [google/google-java-format#507]
GJF gives the following error when formatting a file containing a switch statement using Java 14 arrow labels (`case ... ->`):

```
error: expected token: 'case'; generated ; instead
```

For example:

```java
public class App {

  public void test(String subject) {
    switch (subject) {
      case "A" -> System.out.println("A");
      case "B" -> System.out.println("B");
    }
  }
}
```

GJF version: `google-java-format-1.8-all-deps.jar`
Java version:
```
openjdk version "14.0.1" 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 14.0.1+7)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 14.0.1+7, mixed mode, sharing)
```

**Comment by tbroyer** [comment]
Duplicate of #477 ?

**Comment by skirkpatrick** [comment]
#477 refers to switch _expressions_, and has been fixed in GJF 1.8.

This issue specifically affects switch _statements_ (non-value returning) using the arrow label syntax (traditional `case ...:` labels work fine)

**Comment by skirkpatrick** [comment]
@tbroyer you're correct, looks like this has already been fixed on master. Closing!

**Comment by tbroyer** [comment]
A test was added when adding support for `yield` in #489 (not sure which commit actually fixed it though):
https://github.com/google/google-java-format/blob/45fb41a7bac3dfe0726601ceb87d1c17bbf494ec/core/src/test/resources/com/google/googlejavaformat/java/testdata/ExpressionSwitch.input#L23-L26
