### ISSUE TITLE
Unable to choose Google style option for empty blocks

### ISSUE THREAD

**Issue by javydreamercsw** [google/google-java-format#515]
1. Have code like:
`  void doNothing() {}`
2. Plugin formats to:
```
  void doNothingElse() {
  }
```
As per [Google-style ]( https://google.github.io/styleguide/javaguide.html#s4.1.3-braces-empty-blocks)both are acceptable but plugin enforces one. Some teams might like to enforce one vs. the other.

**Comment by tbroyer** [comment]
> Some teams might like to enforce one vs. the other.

See https://github.com/google/google-java-format/wiki/FAQ#i-just-need-to-configure-it-a-bit-differently-how
