### ISSUE TITLE
Weird Line-wrapping on Anonymous Classes

### ISSUE THREAD

**Issue by popahqiu** [google/google-java-format#522]
Consider this piece of code with an anonymous class in it.
```
  private void tryAnonymousClass() {
    Thread thread = new Thread(new Runnable() {
      @Override
      public void run() {
      }
    });
  }
```
It seems just fine.
However after formatting, it becomes like this:
```
  private void tryAnonymousClass() {
    Thread thread =
        new Thread(
            new Runnable() {
              @Override
              public void run() {}
            });
  }
```
The line-wrappings are somehow unnecessary to me. Especially when we have some quite complex things going on inside `run()`, you can imagine the "mess" here. 

Besides, applying https://github.com/google/styleguide/blob/gh-pages/intellij-java-google-style.xml won't cause such problem.

Do you have suggestions or plans addressing that?

Thanks in advance.

**Comment by tbroyer** [comment]
This is due to [the rectangle rule](https://github.com/google/google-java-format/wiki/The-Rectangle-Rule), so I don't think it's going to be changed (see also https://github.com/google/google-java-format/issues/504)
