### ISSUE TITLE
How to set indent from 2(default) to 4 by spotless?

### ISSUE THREAD

**Issue by ChenJiaJian96** [google/google-java-format#525]
Hello, I met a problem when I use `googleJavaFormat()` in spotless maven, it worked successfully, but I want intent 4 spaces instead 2 spaces.
How can I do? Thanks sincerely.

```groovy
splotless {
    java {
        googleJavaFormat()
    }
}

**Comment by tbroyer** [comment]
See https://github.com/google/google-java-format/wiki/FAQ#i-just-need-to-configure-it-a-bit-differently-how and https://google.github.io/styleguide/javaguide.html#s4.2-block-indentation

If you want the [AOSP style guide](https://source.android.com/setup/contribute/code-style), which uses 4 spaces, then use
```
spotless {
    java {
        googleJavaFormat.aosp()
    }
}
```
(see https://github.com/diffplug/spotless/tree/main/plugin-gradle#google-java-format)

**Comment by ChenJiaJian96** [comment]
thanks a lot! I'll try it later!

**Comment by ChenJiaJian96** [comment]
I successfully solved problem in my Android project. Thanks @tbroyer

**Comment by varjoranta** [comment]
As this issue pops up in searches when trying to solve this for Java and Maven, I will paste the solution here as well. This is unless you want to stick to Google style and not go with AOSP. Similarly as said here for Gradle build:

```
indentWithTabs(2)
indentWithSpaces(4)
```

you can do the same with Maven:

```
    <java>
        <googleJavaFormat>
            <version>1.8</version>
            <style>GOOGLE</style>
        </googleJavaFormat>
        <indent>
            <tabs>true</tabs>
            <spacesPerTab>2</spacesPerTab>
        </indent>
        <indent>
            <spaces>true</spaces>
            <spacesPerTab>4</spacesPerTab>
        </indent>
    </java>
```

**Comment by DreamL** [comment]
> As this issue pops up in searches when trying to solve this for Java and Maven, I will paste the solution here as well. This is unless you want to stick to Google style and not go with AOSP. Similarly as said here for Gradle build:
> 
> ```
> indentWithTabs(2)
> indentWithSpaces(4)
> ```
> 
> you can do the same with Maven:
> 
> ```
>     <java>
>         <googleJavaFormat>
>             <version>1.8</version>
>             <style>GOOGLE</style>
>         </googleJavaFormat>
>         <indent>
>             <tabs>true</tabs>
>             <spacesPerTab>2</spacesPerTab>
>         </indent>
>         <indent>
>             <spaces>true</spaces>
>             <spacesPerTab>4</spacesPerTab>
>         </indent>
>     </java>
> ```

could you please tell that where should I put this code in the pom? thanks

**Comment by bruno-oliveira** [comment]
Hello @varjoranta @DreamL ,

Where to add the above configuration in the POM file of the Maven Spotify plugin to use the Google style instead of the aosp but with 4 spaces instead of 2? 

A complete example would really help! Thanks in advance
