### ISSUE TITLE
Can I avoid some un-expected changed in comment?

### ISSUE THREAD

**Issue by ChenJiaJian96** [google/google-java-format#526]
![image](https://user-images.githubusercontent.com/33413360/94526424-15c4b780-0268-11eb-92ff-a7de441cf270.png)

As shown in the picture, I described a code path in code comments, but `google-java-format` might destroy its structure unexpectedly, how can I avoid it? Thanks sincerely~

BTW, `google-java-format` is a good project!

**Comment by tbroyer** [comment]
Use `<pre>`? Javadoc is (based on) HTML, so whitespace is not significant outside `<pre>` elements.

```java
/**
 * Gets a float array of two lengths representing a rectangle's width and height.
 *
 * <p>The order of the corners in the input float array is:</pr>
 * <pre>
 * 0------->1
 * ^        |
 * |        |
 * |        v
 * 3<-------2
 * </pre>
 */
```

**Comment by tbroyer** [comment]
Oh, or was it a comment, and not javadoc? :thinking:

**Comment by ChenJiaJian96** [comment]
yes it's just a comment~~
