### ISSUE TITLE
Create separate artifacts for the library and cli

### ISSUE THREAD

**Issue by cushon** [google/google-java-format#54]
Other projects that use gjf shouldn't have to pull in jcommander, and any other CLI-only dependencies that are added in the future.

**Comment by sherter** [comment]
Maybe not only make separate artifacts, but also give the API boundaries a second thought. For example, you have added a public constructor to [`com.google.googlejavaformat.java.Formatter`](https://github.com/google/google-java-format/blob/master/core/src/main/java/com/google/googlejavaformat/java/Formatter.java) that takes a file name as a parameter (used for error reporting). As the API only allows to format `String`s or `CharSource`s, I don't think the API should make the assumption that we are formatting files. In my opinion the API consumer (the CLI) should add such information to it's logging output (also makes the `<stdin>` hack obsolete).

**Comment by cushon** [comment]
@sherter - thanks, I followed the suggestion to move file name handling out of `Formatter` in 56bcb0b49310fb0c9f58b755a0e7f5628e048fae.

We've also migrated off jcommander, so this bug is maybe less urgent.

**Comment by cushon** [comment]
We still don't have any CLI-only deps, so I'm going to drop this.
