### ISSUE TITLE
Introduce GitHub Actions based CI workflow

### ISSUE THREAD

**Issue by sormuras** [google/google-java-format#543]
...and drop Travis CI support. See also https://travis-ci.community/t/download-of-jdk-11-and-jdk-14-times-out-intermittently/10647 and linked issues.

Happy to provide a PR.

**Comment by cushon** [comment]
@sormuras if you'd be willing to provide a PR or pointers to a recommended workflow that'd be great!

I think we've been running in to the same issues with Error Prone, e.g.:

```
Downloading JDK from https://download.java.net/java/GA/jdk10/10.0.2/19aef61b38124481863b1413dce1855f/13/openjdk-10.0.2_linux-x64_bin.tar.gz...
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
```

https://travis-ci.org/github/google/error-prone/jobs/745526806

**Comment by sormuras** [comment]
_in progress..._

https://github.com/sormuras/google-java-format/actions

**Comment by cushon** [comment]
It looks like snapshots are working now: https://github.com/google/google-java-format/runs/1477047221

I'm working on a change to turn down the appveyor and travis configs.
