### ISSUE TITLE
Groovy code style missing in the intellij-java-google-style.xml

### ISSUE THREAD

**Issue by BahramMoradi** [google/google-java-format#545]
I tried to use intellij-java-google-style.xml in inteliji. It worked for java formatting but i realized that it can not format Groovy code.
The Groovy code style is missing in the xml file.
Is it possible to add Groovy code style support to xml file.

**Comment by plumpy** [comment]
That file is in a [different repository](https://github.com/google/styleguide), so the issue should be filed there. (That said, we don't really use Groovy at Google, so I don't think we have any particular style guidance for it.)

**Comment by BahramMoradi** [comment]
Thanks for the answer.
