### ISSUE TITLE
AssertionError for type annotations on arrays

### ISSUE THREAD

**Issue by mernst** [google/google-java-format#55]
google-java-format should handle type annotations on arrays, which are legal Java 8 syntax.

The following program compiles cleanly with javac (from JDK 8):

```
import java.lang.annotation.*;

@Target(ElementType.TYPE_USE)
@interface Interned {}

public class GjfTypeAnnotationOnArrayTest {

  public static void test() {
    String @Interned [] iarray1 = new String @Interned [2];
  }

}
```

However, when I run google-java-format on it, using this command:

```java -jar google-java-format-1.0-all-deps.jar GjfTypeAnnotationOnArrayTest.java```

google-java-format issues this message:

```java.lang.AssertionError: GjfTypeAnnotationOnArrayTest.java:9:57: error: did not generate token "@"```

**Comment by cushon** [comment]
Thanks for the report, I have a fix in progress.

**Comment by mernst** [comment]
Any word on the fix?
Thanks!

**Comment by cushon** [comment]
It should be fixed now. Please let us know if you see other issues with type annotations, we haven't done a huge amount of testing against them yet. Thanks!

**Comment by mernst** [comment]
Thanks!  I appreciate it.

I'm seeing a number of other issues.  I minimized a couple of them and submitted issues; I can do more testing when you have fixed them.

**Comment by cushon** [comment]
Thanks, keep the bugs coming! I fixed those crashes, it'd also be interesting to see any examples you notice of complex annotated types where the formatting is subjectively bad.
