### ISSUE TITLE
Is it possible to set Option's formatJavadoc to false?

### ISSUE THREAD

**Issue by myConsciousness** [google/google-java-format#554]
First of all, I would like to pay tribute to this wonderful open source code and great developers.

Now, I'm trying to use this formatter, but I can't find any option to prevent Javadoc from being formatted. I've analyzed the source code and there is a method named `formatJavadoc` defined on `JavaFormatterOptions.java`, but I can't touch it.

Why is this option fixed at true?
Or is there any other way to specify these options?

```java
/** A builder for {@link JavaFormatterOptions}. */
  public static class Builder {
    private Style style = Style.GOOGLE;
    private boolean formatJavadoc = true;

    private Builder() {}

    public Builder style(Style style) {
      this.style = style;
      return this;
    }

    Builder formatJavadoc(boolean formatJavadoc) {
      this.formatJavadoc = formatJavadoc;
      return this;
    }

    public JavaFormatterOptions build() {
      return new JavaFormatterOptions(style, formatJavadoc);
    }
  }
```

**Comment by Akaame** [comment]
If you are using CLI(jar) you can pass in `--skip-javadoc-formatting` option.

### Example:
`java -jar google-java-format-1.9-all-deps.jar --skip-javadoc-formatting src/main/java/Main.java `

**Comment by myConsciousness** [comment]
@Akaame 

Thanks for the kind replies above!

I didn't know about this option until I read your reply... 
However, the application I'm developing won't run with the option you mentioned from the CLI.
And I don't plan to implement a function for it, so I'm giving up on this option for now.

Thanks anyway :)
