### ISSUE TITLE
google-java-format 1.7.0.6 bugfix release

### ISSUE THREAD

**Issue by XComp** [google/google-java-format#560]
Hi, at Apache Flink, we started to use the Google Java Format 1.7 and rely on the google-java-format plugin 1.7.0.5 for that. We're still stuck with Java 8 for now which prevents us from upgrading to a newer version (see [FLINK-20803](https://issues.apache.org/jira/browse/FLINK-20803)). We're experiencing some issues with that version when applying the code template for new Java classes in Intellij. The error is caused by a bug that got fixed in [45fb41a7](https://github.com/google/google-java-format/commit/45fb41a7bac3dfe0726601ceb87d1c17bbf494ec).

We were wondering whether it would be possible to create a bugfix release `1.7.0.6` containing the fix mentioned above considering that others might have a similar setup.

**Comment by Airblader** [comment]
@plumpy @cushon Sorry to ping you so directly, but I was hoping you could give this issue a look? Having such a bugfix release would be a tremendous help.

**Comment by plumpy** [comment]
I actually hadn't published any versions of the plugin with that fix. So I just did, one for each version of google-java-format:
* 1.7.0.6
* 1.8.0.2
* 1.9.0.1
* 1.10.0.0
