### ISSUE TITLE
Implement ToolProvider SPI

### ISSUE THREAD

**Issue by sormuras** [google/google-java-format#561]
Implement [java.util.spi.ToolProvider](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/spi/ToolProvider.html) and deploy it via a `META-INF/services` entry and via a module descriptor.

The main class for the Java formatter CLI looks like it is already well-prepared to offer a `ToolProvider` implementation:

https://github.com/google/google-java-format/blob/24ec96c942a04b89c181df24d80b27c44128b2bf/core/src/main/java/com/google/googlejavaformat/java/Main.java#L52

**Comment by sormuras** [comment]
Happy to provide a PR for this feature.

**Comment by cushon** [comment]
naive question: what use-cases would this cover that depending on g-j-f as a library and using `com.google.googlejavaformat.java.Formatter` doesn't handle?

**Comment by sormuras** [comment]
My use-cases are (build) tools that want to provide access to other tools (provided) re-using their CLI (option parsing).

Having a programmatic entry point, like `com.google.googlejavaformat.java.Formatter` or [`jdk.security.jarsigner.JarSigner`](https://docs.oracle.com/en/java/javase/15/docs/api/jdk.jartool/jdk/security/jarsigner/JarSigner.html) does not give the same user experience out of the box -- I'd have to rewrite and maintain the option parsing logic inside a custom `ToolProvider` implementation.

My current work around is to start an external process for non-`ToolProvider`-implementing tools:

- [forax/pro ... FormatterPlugin](https://github.com/forax/pro/blob/337ee92633f56804a074e9420694563529f4c32c/plugins/formatter/src/main/java/com.github.forax.pro.plugin.formatter/com/github/forax/pro/plugin/formatter/FormatterPlugin.java#L60-L91)
- [sormuras/bartholdy ... GoogleJavaFormat](https://github.com/sormuras/bartholdy/blob/master/src/main/java/de/sormuras/bartholdy/tool/GoogleJavaFormat.java)

Hence `java.util.spi.ToolProvider`, 

> An interface for command-line tools to provide a way to be invoked without necessarily starting a new VM.

comes in handy for my (build) tools.

**Comment by sormuras** [comment]
Done via #656 (i.e. https://github.com/google/google-java-format/commit/2c5d5fd85bebbcb7e3b146d983e3027930aee8ef).
