### ISSUE TITLE
is there any solution to allow multiple lines on field annotation ?

### ISSUE THREAD

**Issue by bigc2000** [google/google-java-format#568]
```
<   @Autowired
<   private Test test
---
>   @Autowired private Test test;
```

is there any solution to allow multiple lines on field annotation ?  It is not consistent with most java code style.

**Comment by kevinb9n** [comment]
Thanks for the request!

Just to reframe the discussion a bit, we think of this not as "allow or not", but as "the formatter's job is to _choose_ a formatting for your code, but in _special cases_ it follows your choices instead".

Here are our criteria for when to do the latter:
https://github.com/google/google-java-format/wiki/FAQ#but-in-this-case-shouldnt-it-preserve-my-existing-choice

My summary judgment is that this isn't going to meet those criteria, but please reopen if you want to make that case.
