### ISSUE TITLE
where is the configuration files?

### ISSUE THREAD

**Issue by vanniuner** [google/google-java-format#575]
Does this project provide any configuration files? like ..

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<profiles version="12">
    <profile kind="CodeFormatterProfile" name="P3C-CodeStyle" version="13">
        <!--可变参数的... Idea没有对应的配置项，强制insert-->
        <setting id="org.eclipse.jdt.core.formatter.insert_space_after_ellipsis" value="insert"/>

```

**Comment by cushon** [comment]
There's a Google Style configuration for the Eclipse formatter here: https://github.com/google/styleguide/blob/gh-pages/eclipse-java-google-style.xml

There's also an Eclipse plugin for `google-java-format`: https://github.com/google/styleguide/blob/gh-pages/eclipse-java-google-style.xml
