### ISSUE TITLE
A missing change in the changelog for 1.10.0

### ISSUE THREAD

**Issue by KengoTODA** [google/google-java-format#583]
[The changelog for 1.10.0](https://github.com/google/google-java-format/releases/tag/v1.10.0) introduces two changes, however, we also have one more bug fix b9fd8d2242869ea7c9efd10cbbe7278c4b6611b1 in this release.

This change may bring many reformats in codebases, like [a case in our repo](https://github.com/spotbugs/spotbugs/pull/1466/commits/28304ba2b54328f2bfe3945496884ea720e1c881).
So I suggest including this change in the changelog, which will help users to avoid confusion and explain why reformats are necessary to their team.

**Comment by cushon** [comment]
Thanks for the reminder, I updated the release notes
