### ISSUE TITLE
Fix some errors

### ISSUE THREAD

**Issue by ferbarbar1** [google/google-java-format#586]
Correct compilation errors in order to run the test units

**Comment by jbduncan** [comment]
Hi @ferbarbar1, welcome to google-java-format!

It's not clear to me from your issue what problem with google-java-format you're experiencing.

The best way of allowing us to help you is to give us something called a [minimal, verifiable, correct example](https://stackoverflow.com/help/minimal-reproducible-example) (or MVCE) that shows us what went wrong, and to explain to us what you expect to happen instead.

That way, not only does it give us the info we need to help you, more often than not it allows you to see the problem and solve it yourself. :)

(I'm a fellow user of google-java-format, not an actual developer working on it, so perhaps the devs would have something more to say here, but please do try making an MVCE and sharing it here first.)
