### ISSUE TITLE
Write a better documentation

### ISSUE THREAD

**Issue by ferbarbar1** [google/google-java-format#587]
Write better intuitive documentation, to make it easier to execute the program.

**Comment by jbduncan** [comment]
@ferbarbar1 I just contacted you on the [other issue](https://github.com/google/google-java-format/issues/586) you raised about creating an "MVCE" of what went wrong and what you expect to happen instead. However it looks like you're just confused about how to use google-java-format, is that right?

What things have you tried already? Perhaps we can help you understand where you're going wrong.
