### ISSUE TITLE
Deprecation warnings prevent using GJF with Gradle 7 in projects that can't upgrade to Java 11

### ISSUE THREAD

**Issue by jimshowalter** [google/google-java-format#593]
Once you made the minimum Java runtime version be 11, a huge number of legacy Java projects (which probably means about 95% of all Java code every written) were unable to use newer versions of GJF.
Unfortunately, older versions of GJF have deprecation warnings in Gradle 6.x that are now forbidden in Gradle 7.x.
So it's a Catch-22. Projects either need to 1) stop using GJF, or 2) not upgrade Gradle.
Both of those are horrible options.
Please please please cut a release of GJF that removes the deprecations.

`> Task :verifyGoogleJavaFormat
Property 'ignoreFailures' has redundant getters: 'getIgnoreFailures()' and 'isIgnoreFailures()'. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0. See https://docs.gradle.org/6.7.1/userguide/more_about_tasks.html#sec:up_to_date_checks for more details.`

Is there some way projects stuck in this situation can override the ignoreFailures property to not have redundant getters?

**Comment by cushon** [comment]
> `Task :verifyGoogleJavaFormat`

Please report an issue against the gradle plugin you're using, which I think is https://github.com/sherter/google-java-format-gradle-plugin?

**Comment by jimshowalter** [comment]
Doh! Sorry about that.
