### ISSUE TITLE
IntelliJ version numbers may be wrong

### ISSUE THREAD

**Issue by dhalperi** [google/google-java-format#597]
I have been completely unable to find any documentation on how JetBrains/IntelliJ compare versions. However, the IDE does not currently suggest an upgrade to 1.10 nor does it list 1.10 as the newest on the site: https://plugins.jetbrains.com/plugin/8527-google-java-format

It might be the case that the code compares versions in string form rather than numerical form. If so, 1.10 would be less than 1.7, 1.8, 1.9, etc.

I note that the Bazel plugins are versioned `2021.04.07.0.2`, with `0` padding.

**Comment by tbroyer** [comment]
On https://plugins.jetbrains.com/plugin/8527-google-java-format/versions, 1.10.0.0 is indeed listed **after** 1.7.0.6!

**Comment by cushon** [comment]
cc @plumpy

**Comment by plumpy** [comment]
Yikes, thanks for noticing! I'll try to figure out how to fix this. Hopefully some way that doesn't involve reuploading all the old versions as `1.07.0.6`, etc. :confused:

**Comment by agavrilov76** [comment]
It doesn't seem to be possible to install the newer plugin version. I tried to download and install it manually but ended up with a NoClassDefFound exception for google formatter.

**Comment by dhalperi** [comment]
@agavrilov76 - manual plugin install on intellij 2020.3.4 worked just fine for me.

<img width="1109" alt="Screen Shot 2021-05-05 at 9 41 27 AM" src="https://user-images.githubusercontent.com/526415/117177624-184f3880-ad86-11eb-9c49-195d42fb4d73.png">

**Comment by agavrilov76** [comment]
I'm getting error on 2021.1.1: 
`java.lang.RuntimeException: java.lang.NoClassDefFoundError: com/google/googlejavaformat/java/JavaFormatterOptions$Style`

<img width="1258" alt="Screenshot 2021-05-05 at 19 10 46" src="https://user-images.githubusercontent.com/3617195/117181639-be765f00-add5-11eb-97bf-8267749d3799.png">

**Comment by dhalperi** [comment]
Gotcha. That's likely a different issue.

**Comment by agavrilov76** [comment]
Turned out that I was installing plugin incorrectly from unpacked archive. I have installed it now but it doesn't seem to reformat JDK 16 Records.

**Comment by plumpy** [comment]
@ffdybuster figured this out in #634.
