### ISSUE TITLE
Crash on annotated fully-qualified class names

### ISSUE THREAD

**Issue by mernst** [google/google-java-format#60]
The tool crashes on annotated fully-qualified class names.
Consider this test case:

```
import org.checkerframework.checker.nullness.qual.*;

public class FullyQualified {

    public void format1(java.lang.String a1, java.lang. @Nullable Object... a2) {
        // body
    }

}
```

**Comment by cushon** [comment]
#64 should fix the crash, but some of the formatting decisions around type annotations may not be final yet. Is there a convention for spaces between type annotations in qualified names and the `.`?

**Comment by mernst** [comment]
JLS section 9.7.4 writes `java.lang.@TA Object` without the space.
