### ISSUE TITLE
[usage consult] IDEA indent

### ISSUE THREAD

**Issue by Alice52** [google/google-java-format#601]
## env

1. the version of my idea is `2020.3`
2. the plugin of `google-java-format` is `1.9.0.1`

## expectation

- `I just want to config the indent to 4 space in  idea, but I'm in troubling.`
-  Please @cushon, please help me, thanks

**Comment by cushon** [comment]
> I just want to config the indent to 4 space in idea

google-java-format  supports Google Java Style, which uses [2-space](https://google.github.io/styleguide/javaguide.html#s4.2-block-indentation) indents for blocks and [4-space](https://google.github.io/styleguide/javaguide.html#s4.5.2-line-wrapping-indent) indents for expressions, and AOSP Style, which uses [4-space and 8-space](https://source.android.com/setup/contribute/code-style#use-spaces-for-indentation) indents.

The google-java-format IntelliJ plugin can be configured to use either of those two styles:

<img width="1024" alt="Screen Shot 2021-05-02 at 1 53 08 PM" src="https://user-images.githubusercontent.com/478458/116827450-d9cf3900-ab4d-11eb-935c-7de19172184e.png">
