### ISSUE TITLE
Should not remove HTML closing tags in Javadoc

### ISSUE THREAD

**Issue by mernst** [google/google-java-format#61]
I have written my Javadoc to contain HTML closing tags.  For example, each time there is a `<li>` tag, my Javadoc contains a matching `</li>` tag.  This is required by HTML/XML standards.  I do recognize that many browsers can handle lack of these tags, but having the matching tags makes browsers run faster, enables use of other tools, and can help to find errors.  Parts of my toolchain expect the closing tags.

google-java-format gratuitously removes these matching tags.

It would be preferable for google-java-format to insert the matching tags when they are missing.  If this is not done, then when a closing tag is present, it should be maintained rather than deleted.

Here is a test case:
```
/**
 * The command-line options are as follows:
 *
 * <ul>
 * <li id="option:date">--date=string. first date to summarize [default today]</li>
 * <li id="option:days">--days=int. number of calendar days to summarize [default 8]</li>
 * </ul>
 */
public final class ClosingTag {}
```

**Comment by cushon** [comment]
The convention internally is to use minimal HTML markup, not necessarily valid XHTML, and to omit `</li>`. The examples in the [Oracle guide](http://www.oracle.com/technetwork/articles/java/index-137868.html) also omit the close tag. I think it's [still valid HTML](https://www.w3.org/TR/2014/REC-html5-20141028/syntax.html#optional-tags).

**Comment by mernst** [comment]
It's true that the closing tag is optional in HTML, but it's not optional in XHTML and I use some XHTML tools.
