### ISSUE TITLE
C-style array declaration should be forbidden

### ISSUE THREAD

**Issue by dsmiley** [google/google-java-format#615]
https://google.github.io/styleguide/javaguide.html#s4.8.3-arrays

> 4.8.3.2 No C-style array declarations
> The square brackets form a part of the type, not the variable: String[] args, not String args[].

Shouldn't this project be correcting that behavior?  I saw a test that tests that c-style is accepted -- by my code inspection; "c-style" is not in any comment here.

**Comment by kevinb9n** [comment]
So far, GJF has been focused on being a _formatter_, which is a somewhat narrower purpose than "style correcter". It does nothing but insert and remove whitespace characters, and sometimes reorder things. The more general tool would be useful, but I don't think we plan for this to become that. If cushon replies, take his word over mine. :-)

**Comment by tbroyer** [comment]
See https://github.com/google/google-java-format/issues/51#issuecomment-860122850

If you're using ErrorProne, there's a check for that: https://errorprone.info/bugpattern/MixedArrayDimensions that you can use for patching to fix the code: https://errorprone.info/docs/patching

**Comment by kevinb9n** [comment]
Thanks @tbroyer, very helpful!
Closing as out of scope.
