### ISSUE TITLE
Google java format doesn't complain about star import

### ISSUE THREAD

**Issue by abbccdda** [google/google-java-format#616]
I have tried all versions of linters ranging from 1.7 to 1.10, but no one complains about star import case in my source file, is this expected or there any chance we could enforce the star import rule?

**Comment by tbroyer** [comment]
See https://github.com/google/google-java-format/issues/51#issuecomment-860122850

If you're using ErrorProne, there's a check for that: https://errorprone.info/bugpattern/WildcardImport that you can use for patching to fix the code: https://errorprone.info/docs/patching

**Comment by kevinb9n** [comment]
Thanks @tbroyer. Yes, this is out of scope.

**Comment by tbroyer** [comment]
@kevinb9n You may want to add the `non-whitespace` label to those issues.
