### ISSUE TITLE
Could not install plugin

### ISSUE THREAD

**Issue by crimsonpython24** [google/google-java-format#620]
Hello,

When I tried to install the plugin, I get the following error:

![image](https://user-images.githubusercontent.com/76871022/122979050-ad0b0580-d3c9-11eb-836c-f3fd1963bf4e.png)

The first thing I noticed is that the exclamation mark at the end of the path looks weird, so I removed it. However, I still got

![image](https://user-images.githubusercontent.com/76871022/122979154-cd3ac480-d3c9-11eb-9a98-a3312da01f5b.png)

I'm not sure of what I have done wrong. I placed the plugin in the following two directories but neither worked (with the second one receiving the same error as the first one)

![image](https://user-images.githubusercontent.com/76871022/122979256-ec395680-d3c9-11eb-9a59-33daa9e516c3.png)
![image](https://user-images.githubusercontent.com/76871022/122979497-33274c00-d3ca-11eb-9d17-6a74893e1090.png)

What I did after copying the files to the drop-in directory is to go to "Help >> Install New Software" and clicked the "add" button:
![image](https://user-images.githubusercontent.com/76871022/122979793-8ef1d500-d3ca-11eb-8fc0-cfc6e900595a.png)

I directly followed the instructions from [the readme](https://github.com/google/google-java-format#eclipse) file. Can anyone please tell me where did I do incorrectly? 

Thanks in advance.

**Comment by cristatus** [comment]
See https://github.com/google/google-java-format/pull/635#issuecomment-889786207
