### ISSUE TITLE
Allow creation of other formats

### ISSUE THREAD

**Issue by xenoterracide** [google/google-java-format#626]
I know that this is explicitly for the use of google official styles. This is a request that you consider allowing people to create other styles using your API. I believe that would allow us to create our own solutions like prettier. Maybe spotless or checkstyle could then use this for more custom styling instead of reimplementing the wheel here. Currently I'm using prettier even in java projects because I don't feel I can really achieve what I want in the Java world. Maybe this is already possible and I just don't know it, if so I apologize.

**Comment by kevinb9n** [comment]
Thanks for this request.

We do however feel that is the sort of job for a forked project to do.

Any particular combination of options you can give it would necessarily be *extremely* less well-tested that the present behavior, and wherever you feel the quality level of the tool is now, we wouldn't be able to keep it there.
