### ISSUE TITLE
Release 1.11.0 doesn't have jar files in assets

### ISSUE THREAD

**Issue by fabasoad** [google/google-java-format#633]
We use script to download jar file (in case it's not present locally) from assets and run the formatter. But the latest release doesn't have any `*.jar` files in "Assets" section.

**Comment by cushon** [comment]
Done. They're also on maven central (https://repo1.maven.org/maven2/com/google/googlejavaformat/google-java-format/1.11.0/), but I uploaded them to the github release page: https://github.com/google/google-java-format/releases/tag/v1.11.0
