### ISSUE TITLE
Update IntelliJ Plugin to 1.11

### ISSUE THREAD

**Issue by mustaphazorgati** [google/google-java-format#634]
Hey there @cushon!

The [IntelliJ Plugin](https://plugins.jetbrains.com/plugin/8527-google-java-format/) currently uses version 1.9. Can you please update that plugin to use 1.11?

Thanks in advance!

**Comment by plumpy** [comment]
FYI, there is a 1.10 version but IntelliJ sorts 1.10 < 1.9, so it won't automatically update :cry: You can manually install it, though. I'm working on a fix.

**Comment by mustaphazorgati** [comment]
Thanks for the quick reply! :) If I can be of assistance let me know

**Comment by cushon** [comment]
> IntelliJ sorts 1.10 < 1.9

@plumpy let me know if there's a different version string scheme we could use that would work better with IntelliJ, I'm open to making changes there if that's the path of least resistance

**Comment by therealppa** [comment]
> > IntelliJ sorts 1.10 < 1.9
> 
> @plumpy let me know if there's a different version string scheme we could use that would work better with IntelliJ, I'm open to making changes there if that's the path of least resistance

I tried to do some research into how IntelliJ sorts the version, but did not find anything. Looking at https://plugins.jetbrains.com/plugin/8527-google-java-format/versions I have the suspicion that it's not so much ordered by version number but they rely more on published date to see which is the most current version. So if you release mutliple versions on the same day, it seems to fall back to alphanumerical sorting.

**Comment by lazystone** [comment]
In what version of Intellij you have that problem? I'm on `2021.2.2` and have google-java-format version  `1.10.0.0` - I think it updated itself long time ago without me noticing.

**Comment by ffdybuster** [comment]
@plumpy @cushon would it be possible to have versions 1.11.0.0 and 1.12.0.0 of the IntelliJ plugin released soon (considering the above points, i.e. the releases must not be made on the same day)? That would be really awesome, since 1.10.0.0 does not format Java 17 code when using some of the new constructs.

**Comment by ffdybuster** [comment]
Now that google-java-format 1.13.0 has been released, can we please have a new release of the IntelliJ plugin?

**Comment by plumpy** [comment]
Thanks for looking into this @ffdybuster. I published 1.11, 1.12, and 1.13. (In that order, to make sure 1.13 is counted as the latest 😁)

**Comment by ffdybuster** [comment]
@plumpy thanks for publishing the new versions! Just installed the updated plugin :rocket:

**Comment by therealppa** [comment]
Thanks for publishing the plugin versions.

Was anyone able to use the 1.13 version to successfully format a modern switch statement like this?

````
    String a = "b";
    String b = switch (a) {
    case "a"    -> "a";
      default -> 
          "default";
    };
````

I'm trying to find out if the problem is on my side or with the plugin

**Comment by lazystone** [comment]
It's most probably problem with JDK on which IDE is running(JDK 11 I assume)

**Comment by lazystone** [comment]
@therealppa check #533

**Comment by therealppa** [comment]
Thank you @lazystone, that is probably the reason for my problem.
