### ISSUE TITLE
Leave annotations on their own line for properties. 

### ISSUE THREAD

**Issue by charlesoconor** [google/google-java-format#648]
Code written
 
```
@Resource 
private OrgInfoRepository orgInfoRepository;
```
is changed to 
```
@Resource private OrgInfoRepository orgInfoRepository;
```
My assumption is that this happens since the line isn't long enough to be split but it would be easier to read if we kept the spring annotations on a separate line. 

I'm using version`1.11.0`

**Comment by dvogel** [comment]
This is a case where the formatter is being stricter than the [documented style rules](https://google.github.io/styleguide/javaguide.html#s4.8.5-annotations). Essentially changing _may_ to _must_ in this exception:

> Exception: A single parameterless annotation may instead appear together with the first line of the signature, for example:

Given that the style guide documents this as an _exception_ to the rule, I would agree with @charlesoconor that if there is going to be one and only one format supported by this project it should be the primary rule that annotations appear on their own line.

**Comment by Alice52** [comment]
+1, so how to fix this?

**Comment by kenchou** [comment]
+1, VERY annoying!

```
@someTag
private IsGood shouldNotChangeIt;  // Good and clearly.

@someTag private IsGood2 alsoAcceptable; // Just acceptable.
```

**Comment by charlesoconor** [comment]
@cushon or someone on the team I can take a crack at this but would like a rough code pointer or know if it's impossible.

**Comment by kevinb9n** [comment]
Sigh -- I'm sorry to say that the annotation-on-same-line policies were the most bitterly contended negotations and we're too scarred to go back into it.

At the bare minimum, we would need an absolutely textual heuristic for when to do it and when not to, and I don't think that's possible.

**Comment by aakash-fk** [comment]
> At the bare minimum, we would need an absolutely textual heuristic for when to do it and when not to, and I don't think that's possible.

In that case, wouldn't it be better go with the more lenient approach, given that it does enhance readability at the very least?

The style guide says in `4.8.5.4 Field annotations`:

> in this case, multiple annotations (possibly parameterized) may be listed on the same line

Should this not be interpreted as "we make an exception to allow multiple annotations on the same line if the developer so wishes"? IMO this implies the plugin should find it acceptable to have field annotations both on separate lines and on the same line.

**Comment by kevinb9n** [comment]
I think reading questions 3-5 here: https://github.com/google/google-java-format/wiki/FAQ would help frame the discussion a little better here, if you can.

**Comment by kevinb9n** [comment]
Because:

* I don't see an argument that this issue meets the three bullet-point criteria listed at that link
* We made the decision for how to format these cases as diligently as anyone could
* And no new information has emerged since then about why the other way is objectively better

... It means the formatter is working as intended. Remember that *every single* style choice the formatter makes is disliked by some fraction of users; I have my share of things I don't personally like too.
