### ISSUE TITLE
Intellij Java import Ordering Not works

### ISSUE THREAD

**Issue by yupwei68** [google/google-java-format#661]
I've enabled plugin `google-java-format` and imported and used https://raw.githubusercontent.com/google/styleguide/gh-pages/intellij-java-google-style.xml in code style in intellij.

But the import is still not ordering alphabetically and not removed unused imports when I click `ctrl+alt+L`.

java version "1.8.0_131"
Intellij 2021.2.1

**Comment by tbroyer** [comment]
From [the README](https://github.com/google/google-java-format#intellij-android-studio-and-other-jetbrains-ides)

> The import ordering is not handled by this plugin, unfortunately.

**Comment by mustaphazorgati** [comment]
As far as I know `google-java-format` does not touch the imports at all.

You have to configure import oder unter Settings > Editor > Code Style > Java > Imports manually. 
A checkstyle configuration file does not automatically update the import order.
Furthermore you either have to set `Optimize imports` in `Actions on Save` or use the `Optimize imports` command to optimize your imports. `ctrl+alt+L` only reformats the code and does not touch the imports.

**Comment by plumpy** [comment]
Dup of #94

**Comment by ssh352** [comment]
> 

same issue, enabling optimize imports in actions on save doesn't sort imports. How could Intellij sort imports with this plugin?
