### ISSUE TITLE
Eclipse plugin with Java 16+

### ISSUE THREAD

**Issue by sparty02** [google/google-java-format#665]
The README has [instructions](https://github.com/google/google-java-format#jdk-16) for using the formatter with Java 16+ when running from the command line and [instructions](https://github.com/google/google-java-format#eclipse) for using the Eclipse plugin.  However, it's not clear how to use the Eclipse plugin _with_ Java 16+ (which is the default JDK that ships with Eclipse at the moment...at least Spring Tool Suite 4.12).

Currently, when running Eclipse with Java 16+, this error pops up when attempting to format:

![image](https://user-images.githubusercontent.com/1483538/133843055-95b4206a-2503-4f40-996d-bfc16e0d4106.png)

I'd be happy to PR a documentation update, but I'm honestly not sure how to define --add-exports for an Eclipse plugin.

Some things considered:
- Does it go in eclipse.ini/SpringToolSuite4.ini under -vmargs, some context [here](https://wiki.eclipse.org/Eclipse.ini)?
- If it goes in eclipse.ini, does that become effective for the entirety of eclipse?  Would the google-java-formatter need to be modular in order to only apply it to that?

**Comment by christopher-cudennec** [comment]
This does not seem connected to Eclipse but to Java 16+ in general. I get the following error when formatting my project with Gradle 7.2 / Java 17:
```
Caused by: java.lang.IllegalAccessError: class com.google.googlejavaformat.java.JavaInput (in unnamed module @0xf69eaf7) cannot access class com.sun.tools.javac.parser.Tokens$TokenKind (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.parser to unnamed module @0xf69eaf7
```

**Comment by christopher-cudennec** [comment]
@cushon : Thanks for your link. I also add the Spotless issue for anyone who wants a workaround: https://github.com/diffplug/spotless/issues/834

**Comment by kukirsch** [comment]
@sparty02 try adding the required exports in your `eclipse.ini`. 
```    
-vmargs
--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED
--add-exports=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED
--add-exports=jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED
--add-exports=jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED
--add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED
```
The first equals sign (after add-exports) is optional on the command line, but necessary ([Oracle JDK 9 Migration Guide](https://docs.oracle.com/javase/9/migrate/toc.htm#JSMIG-GUID-D867DCCC-CEB5-4AFA-9D11-9C62B7A3FAB1) ) here because Eclipse uses the JNI Invocation API by default on most platforms.

With these changes the plugin works with Eclipse 4.22.0 and JDK 16/17.

**Comment by sparty02** [comment]
Thanks @kukirsch  that worked for me!
