### ISSUE TITLE
Is IntelliJ plugin deprecated?

### ISSUE THREAD

**Issue by dhalperi** [google/google-java-format#675]
Just wondering - version 1.12 was just released, and version 1.11 a few months back -- but AFAICT 1.11 was never released as an IntelliJ plugin. https://plugins.jetbrains.com/plugin/8527-google-java-format/versions

Is this an oversight? A policy change and we should source a plugin on our own?

**Comment by plumpy** [comment]
1.11. 1.12, and 1.13 are published now. Sorry about the delay.
