### ISSUE TITLE
Should not delete wildcard imports

### ISSUE THREAD

**Issue by mernst** [google/google-java-format#68]
The tool deletes wildcard imports without leaving anything in their place, thus leading to uncompilable code.

Consider this code:
```
import java.util.*;

class UseList {
  List l;
}
```

which is transformed to this:

```

class UseList {
  List l;
}
```

**Comment by cushon** [comment]
Thanks, that's a bad bug in the unused import pass.

(Note that the style guide [does not allow wildcard imports](https://google.github.io/styleguide/javaguide.html#s3.3.1-wildcard-imports), which is probably why it didn't get caught sooner.)
