### ISSUE TITLE
Formatting results don't fit the google style guide

### ISSUE THREAD

**Issue by zxeoc** [google/google-java-format#681]
I'm using intellij plugin for formatting code and using checkstyle plugin with [google style guide](https://github.com/google/styleguide/blob/gh-pages/intellij-java-google-style.xml) to check code style. But usually, they give different results.

For example, the code formatted by google-java-format plugin is:

```
    list.addAll(performanceTestCases.stream().map(
            c -> closure1.toItemList(env, pid, key, c.getDataSetCollections(),
                c.getBusinessModule(), c.getCaseId()))
        .flatMap(Collection::stream)
        .collect(Collectors.toList()));
```

But checkstyle with google style guide reports "'lambda arguments' has incorrect indentation level 12, expected level should be one of the following: 6, 8. (98:0) [Indentation]".

**Comment by cushon** [comment]
I don't think you have the plugin enabled, google-java-format would do something like:

```java
    list.addAll(
        performanceTestCases.stream()
            .map(
                c ->
                    closure1.toItemList(
                        env,
                        pid,
                        key,
                        c.getDataSetCollections(),
                        c.getBusinessModule(),
                        c.getCaseId()))
            .flatMap(Collection::stream)
            .collect(Collectors.toList()));
```

**Comment by zxeoc** [comment]
Sorry, my mistake. You are right, the plugin is not enabled. Enabling it solved the problem.
