### ISSUE TITLE
Maven plugin

### ISSUE THREAD

**Issue by nobeh** [google/google-java-format#69]
Support using Google Java Format as part a build in Maven thru a plugin.
Google coding styles helps a great deal to apply a common scheme to a code 
repository. Although, there are ways to share/automate workspace settings,
it essentially relies on developer to follow and apply the coding styles.
As a build plugin, the formatting of the source can be applied before
any commit, during builds on CI/CD servers and other applications.

**Comment by nobeh** [comment]
Maybe a check-list to further complete the PR:

- [ ] Add unit tests
- [ ] Support `excludes` and `includes` for the plugin

**Comment by GuiSim** [comment]
I've made https://github.com/coveo/fmt-maven-plugin.
It does not support excludes and includes but pull requests are welcome!

**Comment by javabeanz** [comment]
+1

**Comment by patflynn** [comment]
+1 the README should include instructions on how to configure the formatter through plugins for Gradle and Maven projects as I think that's how most people will want to use it.

**Comment by jbduncan** [comment]
@GuiSim May I kindly ask why you thumbed-down the last two comments? :)

**Comment by GuiSim** [comment]
@jbduncan The emoji reactions are an explicit mechanism to show support for an issue. It is a much better option than adding a `+1` comment.

As for the patflynn's comment, I do not think that the google-java-format README should discuss Maven plugins unless a Maven plugin is provided. Right now, no Maven plugin is provided. A link to repositories containing google-format Maven plugins would be a better option.

**Comment by jbduncan** [comment]
I see, thanks for clarifying things your viewpoint for me @GuiSim. :)

If a list of build plugins for using google-java-format is to be added to the README, then I'd encourage [Spotless](https://github.com/diffplug/spotless) to be added as a prime example for Gradle (as per PR https://github.com/google/google-java-format/pull/83).

**Comment by reda-alaoui** [comment]
I also created a maven plugin: https://github.com/Cosium/maven-git-code-format

This one automatically installs a git `pre-commit` hook. On `pre-commit`, the staged files are formated by `google-java-format`.

**Comment by talios** [comment]
@reda-alaoui heh, that's at least 3 maven plugins now ( mine, yours, and @GuiSim's ).

**Comment by reda-alaoui** [comment]
I know.
But IMO, the formatting or the check should occur at `pre-commit` only on staged files.

Are you interested in this use case for your plugin? If yes, perhaps I could merge mine into yours.

**Comment by cushon** [comment]
I added some links to existing plugins to the README: https://github.com/google/google-java-format#third-party-integrations. If I missed any, please let me know or send PRs to fix the docs.

Currently we're happy to let others with more maven/gradle experience build plugins, we don't feel there's much to add by providing our own in the main GJF repository.
