### ISSUE TITLE
IntelliJ : .stream is not in the new line even if set on intelliJ format settings

### ISSUE THREAD

**Issue by vpresecki** [google/google-java-format#692]
What steps will reproduce the issue?
1. google-java-plugin enabled
2. In settings-> Editor -> Code Style -> Java -> Chained method calls :
wrap always
wrap fist call
3. Format some code with .stream() : example -> list.stream()....
What is the expected result?

Every .stream() should be in new line (alone) -> example: list
.stream()

What happens instead?
.stream() is in the same line as list

If google-java-format is disabled, it will work as expected....

**Comment by Stephan202** [comment]
Google Java Format enforces a single style (well, two, with AOSP), which basically [cannot be configured](https://github.com/google/google-java-format/wiki/FAQ#i-just-need-to-configure-it-a-bit-differently-how). None of the configuration under _Settings-> Editor -> Code Style -> Java_ should have any effect. The plugin handles `.stream()` specially; see #341.

**Comment by vpresecki** [comment]
This makes absolutley no sense... this is enforced on IntelliJ but not on Eclipse?

**Comment by cushon** [comment]
Can you share an example of the Java code that is formatted differently? Are you sure that both sets of developers have enabled the same version of google-java-format?

**Comment by vpresecki** [comment]
Sure.
Google java format in Eclipse: 
    settingWrappers =
        settings
            .stream()
            .map(
                setting -> {
                  // wrap Campaign Extension Settings with related Extension Feed Items
                  CampaignExtensionSettingWrapper settingWrapper =
                      new CampaignExtensionSettingWrapper(setting);

Google java format in IntelliJ:
    settingWrappers =
        settings.stream()
            .map(
                setting -> {
                  // wrap Campaign Extension Settings with related Extension Feed Items
                  CampaignExtensionSettingWrapper settingWrapper =
                      new CampaignExtensionSettingWrapper(setting);


This happens everywhere with stream operation... in intelliJ .stream() will never be in new line, or in eclipse it will never be in one line.... Either way, seams like they are not formatting in the same way

**Comment by cushon** [comment]
The correct formatting with recent versions of the formatter is:

```
class T {
  {
    settingWrappers =
        settings.stream()
            .map(
                setting -> {
                  // wrap Campaign Extension Settings with related Extension Feed Items
                  CampaignExtensionSettingWrapper settingWrapper =
                      new CampaignExtensionSettingWrapper(setting);
                });
  }
}
```

There's some context about why `.stream()` isn't on a new line in the bug @Stephan202 linked to: https://github.com/google/google-java-format/issues/341

If you're seeing Eclipse produce a different formatting, either the google-java-format plugin isn't enabled, or it's using an old version of google-java-format that predates that change.
