### ISSUE TITLE
Option to pass in Google Style file?

### ISSUE THREAD

**Issue by tommy0831** [google/google-java-format#719]
We modified the Google Style file.  How can we tell google-java-format to use the new file when running from command line?

java -jar lib/google-java-format-1.7-all-deps.jar  .....

**Comment by lowasser** [comment]
I don't believe g-j-f uses a style file; that might be for another formatter.

**Comment by cushon** [comment]
There are Google Style configurations for other tools, e.g. [checkstyle](https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/google_checks.xml), [Eclipse](https://github.com/google/styleguide/blob/gh-pages/eclipse-java-google-style.xml), [IntelliJ](https://github.com/google/styleguide/blob/gh-pages/intellij-java-google-style.xml), maybe you encountered one of those?

As Louis said, g-j-f's style is not configurable, it follows Google Style out of the box.
