### ISSUE TITLE
Manifest files contain different properties between 1.13.0 and 1.14.0

### ISSUE THREAD

**Issue by davidburstromspotify** [google/google-java-format#747]
Maybe this is an intentional change, but for GJF 1.13.0 the `META-INF/MANIFEST.MF` file reads

```
Manifest-Version: 1.0
Created-By: Apache Maven 3.6.3
Built-By: cushon
Build-Jdk: 14.0.2
Implementation-Title: Google Java Format
Implementation-Version: 1.13.0
Implementation-Vendor-Id: com.google.googlejavaformat
Implementation-Vendor: Google Inc.
Implementation-URL: https://github.com/google/google-java-format/google-
 java-format
Main-Class: com.google.googlejavaformat.java.Main
Automatic-Module-Name: com.google.googlejavaformat
```

and for GJF 1.14.0 it reads

```
Manifest-Version: 1.0
Created-By: Maven JAR Plugin 3.2.2
Build-Jdk-Spec: 17
Implementation-Title: Google Java Format
Implementation-Version: 1.14.0
Implementation-Vendor: Google Inc.
Main-Class: com.google.googlejavaformat.java.Main
Automatic-Module-Name: com.google.googlejavaformat
```

In my case I'm missing the `Implementation-Vendor-Id` property that's been around since at least GJF 1.5.

**Comment by davidburstrom** [comment]
In my case I can switch to looking for `Main-Class` which has been constant 1.5 through 1.14.0.

**Comment by cushon** [comment]
We upgrade the versions of a bunch of maven plugins recently, I suspect we encountered

> Starting with version 2.1, Maven Archiver no longer creates the Implementation and Specification details in the manifest by default. If you want them in your manifest you have to say so explicitly in your configuration.

from https://maven.apache.org/shared/maven-archiver/examples/manifest.html

**Comment by cushon** [comment]
@davidburstromspotify is `Main-Class` sufficient for your use-case, or would there be advantages to adding `Implementation-Vendor-Id` back?

**Comment by davidburstromspotify** [comment]
I'm using the properties to locate the GJF library version on a classpath. Since 1.14.0 is a GA release, the most compatible solution for me is to switch to `Main-Class`. I raised this mostly as an FYI, but I don't expect any particular action.
