### ISSUE TITLE
IntelliJ plugin ignores @Formatter:off/on

### ISSUE THREAD

**Issue by SebHo0** [google/google-java-format#748]
### What happened?
The IntelliJ plugin ignores formatter guards (e.g. @Formatter:off/on) even though IntelliJ itself is setup to respect it.

### What did you want to happen?
Do not overwrite the formatter guard settings (or at least provide a settings option to respect those).

**Comment by SebHo0** [comment]
Thank you for the quick reply.

I really wonder why this seems to be such a rare issue for the users of the plugin.
Anyhow, the plugin without this feature does not seem to be the 100% perfect solution in our case.

FYI:  In our project, we would like to protect some concatenated strings which build up some kind of sql query from rearrangement to keep it more human readable.

**Comment by cushon** [comment]
https://github.com/google/google-java-format/issues/137
