### ISSUE TITLE
Formatting import order does not take effect after using intellij-java-google-style.xml

### ISSUE THREAD

**Issue by cedricai** [google/google-java-format#773]
https://raw.githubusercontent.com/google/styleguide/gh-pages/intellij-java-google-style.xml
My IDE is IntelliJ IDEA 2021.3.3 (Community Edition)

**Comment by ockl** [comment]
@cedricai 
Make sure you have the following setting activated:
File -> Settings -> Tools -> Actions on Save -> Optimize imports

**Comment by cushon** [comment]
The google-java-format IntelliJ plugin doesn't sort imports, that's configured separately from formatting, and this is a different project than google/styleguide.
