### ISSUE TITLE
Java: How can the plugin prohibit line breaks?

### ISSUE THREAD

**Issue by longtai-cn** [google/google-java-format#774]
Hi, I have a question. I want to use this plug-in, but I don't want it to perform line breaks. How to set it?

If the description is not clear, I can add.

Looking forward to your reply, thank you.

**Comment by lowasser** [comment]
I don't believe that's possible.  See e.g. https://github.com/google/google-java-format/wiki/FAQ#i-just-need-to-configure-it-a-bit-differently-how .
