### ISSUE TITLE
Project

### ISSUE THREAD

**Issue by Arashvscode** [google/google-java-format#778]
Hi, I'm building a code editor and I want to I use the format code but I do not know how Can you send me the Java code?

**Comment by jbduncan** [comment]
Hi @Arashvscode. The section of the README to read is ["as a library"](https://github.com/google/google-java-format#as-a-library).

I hope this helps.

**Comment by Arashvscode** [comment]
> 

I tested the code and it did not work for me

**Comment by cushon** [comment]
Can you provide context about what you tried, and what didn't work?

**Comment by Arashvscode** [comment]
> Can you provide context about what you tried, and what didn't work?

sourceString = editor.getText().toString();
try{
		
		String formattedSource = new Formatter().formatSource(sourceString);
}catch(Exception e){
		
		
}

Me used in code end my app error 
See in image 
![Screenshot_۲۰۲۲۰۴۲۲-۲۲۳۹۳۸_code format](https://user-images.githubusercontent.com/101287880/164770984-c17bf8e1-721e-4305-98e9-6375848e800f.jpg)

**Comment by cushon** [comment]
The `NoClassDefFoundError` suggests that you are missing a dependency on Guava

**Comment by Arashvscode** [comment]
> 

Fixed my bro tnks❤
