### ISSUE TITLE
1.1 reports 1.0 as version

### ISSUE THREAD

**Issue by sormuras** [google/google-java-format#78]
Nit: [GoogleJavaFormatVersion](https://github.com/google/google-java-format/blob/master/core/src/main/java/com/google/googlejavaformat/java/GoogleJavaFormatVersion.java) reports `1.0` -- and this effects `--version` information printed by 1.1 and 1.2-SNAPSHOT Main programs.

**Comment by cushon** [comment]
Thanks for pointing that out. Is it blocking anything? I can release a 1.1.1 or something if that'd be helpful.

**Comment by sormuras** [comment]
No, nothing's blocked. Just an eye candy.

**Comment by sormuras** [comment]
Your commit https://github.com/google/google-java-format/commit/23822436ae372c6b1a5758952a8b6641fb3adadf fixes the "bug" with 1.2-SNAPSHOT and newer. What is 1.1❓

**Comment by cushon** [comment]
1.1 is f6e39cdf0e33816e2219a09017ef731a76fedd95.

**Comment by sormuras** [comment]
True. Wanted to express: _Who cares for 1.1 if there's 1.2-SNAPSHOT_ :wink:
