### ISSUE TITLE
Release tags does not match with code base

### ISSUE THREAD

**Issue by firatkucuk** [google/google-java-format#793]
Release `v1.15.0` has a commit id `edf036c7fd07a719c5197e04f8da181e7cdb81ee` and it does not match any commit on master branch probably it's a fork,

**Comment by tbroyer** [comment]
Releases are made with the Maven release plugin, which creates commits to update the version in the POM files. Those commits aren't pushed to master as they're just _noise_. They're the only difference from the master branch.
