### ISSUE TITLE
Building the executable

### ISSUE THREAD

**Issue by tfarina** [google/google-java-format#8]
Hi,

How do I generate the google-java-format executable/binary? I'm not familiar with Maven. I did run `mvn compile` though.

**Comment by cushon** [comment]
I made some changes that should help in #9. With that patch, it's just:

```
$ mvn package
$ java -jar core/target/google-java-format-0.1-SNAPSHOT.jar
```

I don't actually know a good way to launch it at the moment. (I'm not that familiar with maven either.)
