### ISSUE TITLE
Publish IDEA plugin with GJF 1.1 release

### ISSUE THREAD

**Issue by sormuras** [google/google-java-format#80]
Current plugin https://plugins.jetbrains.com/plugin/8527 comes with an 1.1 SNAPSHOT, namely `google-java-format-1.1-20160728.050102-25-all-deps.jar`.

**Comment by cushon** [comment]
@brendandouglas might have volunteered to update the plugin.

**Comment by cushon** [comment]
@brendandouglas might have volunteered to update the plugin.

**Comment by Stephan202** [comment]
Question about the plugin: there used to be a `pom.xml` and an `install-idea-jars.sh` using which one could build the plugin from the command line. These are gone. Is there still a way (or will there once again be a way) to build the plugin from the command line? (I'm looking for something like 44ccfd95082cba77370ff4de96236a8072a70702. I'm not an IDEA plugin expert, so excuse my ignorance.)

**Comment by thenuge** [comment]
+1 any plans for another release? Thanks!

**Comment by cushon** [comment]
A 1.2.SNAPSHOT version was released.
