### ISSUE TITLE
line break for long string literal

### ISSUE THREAD

**Issue by ssh352** [google/google-java-format#800]
logger.info("a long string literal") 
the string literal doesn't get broken into two lines, is it expected? Thanks!

for c++, clang-format breaks up long string literals.

**Comment by cushon** [comment]
The CLI does this by default (although there's an option to turn it off, `--skip-reflowing-long-strings`):

```java
$ cat T.java
class T {
  {
    logger.info("a very very very very very very very very very very very very very very very long string literal");
  }
}
$ google-java-format T.java
class T {
  {
    logger.info(
        "a very very very very very very very very very very very very very very very long string"
            + " literal");
  }
}
```
