### ISSUE TITLE
Is there any plan to support `automatically add this to call private method`?

### ISSUE THREAD

**Issue by levy9527** [google/google-java-format#803]
## why
`this` keyword can make calling private methods more explicit, which would be a better experience for reading code. 

After all, it's common that at first we want to skim the code and find the key code quickly, then we start reading the code carefully. 

However, since many private methods are called without `this`, it's hard to recognize them at a glance, we have to read the code line by line all the time.

## with this
![image](https://user-images.githubusercontent.com/9384365/180352926-715aa9ef-249d-40a0-a422-c715c86094b7.png)

## without this
![image](https://user-images.githubusercontent.com/9384365/180352714-861c877f-e240-4831-bf58-ba3b6fe2e1b0.png)

**Comment by cushon** [comment]
There are no plans to do this. The formatter generally only makes whitespace changes, and the style guide doesn't require qualifying private methods with `this`.
