### ISSUE TITLE
Intellij and commandline reformat long strings differently

### ISSUE THREAD

**Issue by mdhirsch** [google/google-java-format#816]
I would like to use the intellij plugin to format my java so that it is correctly formatted according to the google-java-format jar when run from the commandline.

If I start with 
`  /**
   * This is the first para
   *
   * This is the second para just to prove that the formatter is working.
   *
   * @return a long string
   */
  public String reformatMe() {
    return "This is a very long string.  This is a very long string.  This is a very long string.  This is a very long string.";
  }`

Then reformatting it with the plugin adds "<p>" to the javadoc, but leaves the long string unchanged:
`  /**
   * This is the first para
   *
   * <p>This is the second para just to prove that the formatter is working.
   *
   * @return a long string
   */
  public String reformatMe() {
    return "This is a very long string.  This is a very long string.  This is a very long string.  This is a very long string.";
  }`

But it I reformat the original code with the jar running from commandline I get
`  /**
   * This is the first para
   *
   * <p>This is the second para just to prove that the formatter is working.
   *
   * @return a long string
   */
  public String reformatMe() {
    return "This is a very long string.  This is a very long string.  This is a very long string. "
               + " This is a very long string.";
  }`
So the commandline version modifies the long string.

Is there a parameter or option I am missing to make the plugin do the same thing as the commandline?

**Comment by cushon** [comment]
https://github.com/google/google-java-format/issues/566#issuecomment-908761913
