### ISSUE TITLE
Release eclipse 1.15 version

### ISSUE THREAD

**Issue by velo** [google/google-java-format#825]
Seems eclipse version is hardcoded to 1.13 version
https://github.com/google/google-java-format/blob/master/eclipse_plugin/pom.xml#L25

That lead to the last two releases of eclipse plugin to be stuck at 1.13
https://github.com/google/google-java-format/releases

I diff jars included under [v1.15.0](https://github.com/google/google-java-format/releases/tag/v1.15.0) and [v1.14.0](https://github.com/google/google-java-format/releases/tag/v1.14.0) and the contents is exactly the same as v1.13

I noticed a few minor differences when formatting on eclipse (v1.13) and on command line (v1.15), so a new eclipse release is necessary

**Comment by PhilippWendler** [comment]
Also at #744

**Comment by velo** [comment]
Hi @cushon  where can I find the v1.15.0 release of the plugin?

![Screen Shot 2022-09-07 at 09 14 43](https://user-images.githubusercontent.com/136590/188739549-55cd2d89-5dc5-41f3-af51-7e2b52b49d33.png)

Release page still only contains v1.13

**Comment by skarpushin** [comment]
Why is this closed? Issue is still there. There is a PR https://github.com/google/google-java-format/pull/826 that can fix this.

**Comment by tbroyer** [comment]
Because that's more or less a duplicate of #744
