### ISSUE TITLE
Keep braces on same line when using Double Brace Initialization?

### ISSUE THREAD

**Issue by ben-larson** [google/google-java-format#829]
Hello!  I recently learned about [Double Brace Initialization](http://wiki.c2.com/?DoubleBraceInitialization) and I've found it to be a nice way to clean up code in many instances.

```java
// Without Double Brace Initialization
Email email = new Email();
email.setFrom("from@example.com");
email.setTo("to@example.com");
email.setBody("Hello world!");
return email;

// With Double Brace Initialization
return new Email() {{
  setFrom("from@example.com");
  setTo("to@example.com");
  setBody("Hello world!");
}};
```

Currently when I format the example above, it outputs this:

```java
return new Email() {
  {
    setFrom("from@example.com");
    setTo("to@example.com");
    setBody("Hello world!");
  }
};
```

What are your thoughts on changing this behavior to leave the braces on one line?  That would be more readable to me, though I think I see why the braces are being broken up right now.  Technically they delineate two separate blocks if I'm not mistaken.  I'd love to hear what you think!

**Comment by lowasser** [comment]
Be warned that double brace initialization has [many major disadvantages](https://stackoverflow.com/a/27521360/869736).

**Comment by ben-larson** [comment]
Thanks @lowasser!  I was not aware of those problems, I appreciate the heads up.  If there is concern that this change would be harmful by encouraging bad or very dangerous practices, I am good with closing the issue.  I defer to folks more experienced with this syntax than I.

**Comment by cushon** [comment]
[The style guide](https://google.github.io/styleguide/javaguide.html#s4.1.2-blocks-k-r-style) also requires the newline after the opening `{`.
