### ISSUE TITLE
Intellij-Plugin is overwriting Reformat-Code

### ISSUE THREAD

**Issue by Fjolnir-Dvorak** [google/google-java-format#85]
The Plugin for IntelliJ-IDEA is overwriting the Reformat-Code given by IntelliJ Idea indead of only reformat the code with the plugin when selecting "Reformat with Google-Code Style". It is not possible to use the project own reformatters if this plugin is activated.

Plugin-Version: v1.0
IntelliJ-Version: 2016.2.4

**Comment by cushon** [comment]
I don't think IntelliJ provides better alternatives for integrating external formatters: https://intellij-support.jetbrains.com/hc/en-us/community/posts/206757245-Delegating-formatting-to-an-external-formatter

**Comment by plumpy** [comment]
You can now (as of 1.3.1, I believe, although perhaps earlier) enable/disable google-java-format on a per-project basis. Thanks for the request!
