### ISSUE TITLE
Inconsistent default behavior of CLI and API/IDE Plugins (reflowLongStrings)

### ISSUE THREAD

**Issue by cgoeller** [google/google-java-format#857]
**Describe the bug**
The CLI formatter reflows long strings by default (can be deactivated)
The IntelliJ Plugin does not reflow long strings by default (cannot be configured)
The maven plugin (https://github.com/spotify/fmt-maven-plugin) does not reflow long strings by default (cannot be configured)

**To Reproduce**
See example project: https://github.com/cgoeller/fmt-example

**Expected behavior**
The default behavior should be identical for CLI, IntelliJ Plugin and Maven Plugin

**Additional context**
Version of CLI 1.15.0
IntelliJ Plugin Version 1.15.0
Maven Plugin Verison 2.19 (uses 1.15.0)

See: https://github.com/spotify/fmt-maven-plugin/issues/159

**Comment by tbroyer** [comment]
See https://github.com/spotify/fmt-maven-plugin/issues/159#issuecomment-1310645973
This should be handled in the fmt-maven-plugin. See how Spotless does it for instance (https://github.com/diffplug/spotless/blob/main/lib/src/main/java/com/diffplug/spotless/java/GoogleJavaFormatStep.java)

The IntelliJ plugin should probably be modified though.

**Comment by cushon** [comment]
https://github.com/google/google-java-format/issues/566
