### ISSUE TITLE
google-java-format.xml configurable

### ISSUE THREAD

**Issue by Grauzone** [google/google-java-format#860]
Is it possible to import the google-java-format.xml file configurably from the filesystem?
The problem is that the google-java-format.xml does all the formatting. So you can't make any changes e.g. hard line wrap is way too short, we don't work on 17 inch screens anymore in the 21st century. Would be nice if you can change the google-java-format.xml.

Or is that possible and I just don't have a plan how to do that?

Thanks in advance!

**Comment by tbroyer** [comment]
See https://github.com/google/google-java-format/wiki/FAQ#i-just-need-to-configure-it-a-bit-differently-how and #425
