### ISSUE TITLE
how to use project android

### ISSUE THREAD

**Issue by Arashvscode** [google/google-java-format#884]
Hello, I am building a private IDE. I tested the codes in readme.md, but the codes are not formatted for me. Can you provide me with the correct codes?

**Comment by jbduncan** [comment]
@Arashvscode I'm a user of google-java-format, and it works for me, so it's not clear yet why it isn't working for you.

What have you tried? What did you expect, and what did you get instead?

**Comment by jbduncan** [comment]
@Arashvscode Do you have a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) to share? Sometimes I find that making one allows me to find the problem myself, but otherwise it helps the developers understand what's going on. :)

**Comment by Arashvscode** [comment]
> 
Well, I need such a code, but in Java, because I don't know Kotlin and I don't have time to learn it

``` kt 
class GoogleJavaFormatter( private val source: String) { fun format(): String {
 val options = JavaFormatterOptions.builder() .style(JavaFormatterOptions.Style.AOSP) // Use 4 spaces for tab .formatJavadoc(true)
 // Format Javadoc .build() 
val formatter = Formatter(options) 
try {
 return formatter.formatSourceAndFixImports(source)
 } catch (e: Exception) { 
e.printStackTrace()
 } return source 
}
}

 ```

**Comment by jbduncan** [comment]
I'm curious, where did you get that code from? I don't see it anywhere in the README examples.

Just to double-check, have you already tried the examples from the README?

> You can then use the formatter through the `formatSource` methods. E.g.
>
> ```java
> String formattedSource = new Formatter().formatSource(sourceString);
> ```
>
>or
>
>```java
>CharSource source = ...
>CharSink output = ...
>new Formatter().formatSource(source, output);
>```

(The second example assumes you're using `CharSource` and `CharSink` from [Guava](https://github.com/google/guava) already.)

If you have already tried them, then what problem or error message are you seeing? Are you at liberty to share these details with us?

Have you also considered reading the [Javadoc](https://www.javadoc.io/doc/com.google.googlejavaformat/google-java-format/latest/com.google.googlejavaformat/com/google/googlejavaformat/java/Formatter.html)?

**Comment by jbduncan** [comment]
You can pass [configuration options](https://www.javadoc.io/doc/com.google.googlejavaformat/google-java-format/latest/com.google.googlejavaformat/com/google/googlejavaformat/java/JavaFormatterOptions.html) to `Formatter`'s constructor to change the formatter's behaviour, similar to what the Kotlin code you presented does.

**Comment by Arashvscode** [comment]
> 

Well, I took this code from an IDE and yes, the codes that I tested in readme didn't work, unfortunately

**Comment by jbduncan** [comment]
What error message do you see?

**Comment by Arashvscode** [comment]
> 

com.sun.tools.javac.parser not found

**Comment by jbduncan** [comment]
Okay, that suggests you're using a recent version of Java, meaning you'll need to open up the `com.sun` internal classes to your program by passing the specific JVM flags below to your program.

> ### as a library
> 
> The formatter can be used in software which generates java to output more
> legible java code. Just include the library in your maven/gradle/etc.
> configuration.
> 
> `google-java-format` uses internal javac APIs for parsing Java source. The
> following JVM flags are required when running on JDK 16 and newer, due to
> [JEP 396: Strongly Encapsulate JDK Internals by Default](https://openjdk.java.net/jeps/396):
> 
> ```
> --add-exports jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED
> --add-exports jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED
> --add-exports jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED
> --add-exports jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED
> --add-exports jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED
> ```

If you use the terminal, I imagine the command is something like `java -jar <your-jar-file.jar> ...`, where the JVM flags go where the "..." is.

If you use an IDE or code editor, Google how to run your program with additional JVM flags for your IDE/editor.

These instructions can be found in the ["as a library"](https://github.com/google/google-java-format#as-a-library) section of the README.

**Comment by Arashvscode** [comment]
> 

Yes, I understand, I installed it, thank you, my problem is solved
