### ISSUE TITLE
the plugin in intelij doesnt work any more

### ISSUE THREAD

**Issue by vedhamurthyhk** [google/google-java-format#901]
When tried to format code its doesn't do anything and just says successful and same with Git commit hook.

IntelliJ IDEA 2022.3.1 (Community Edition)
Build #IC-223.8214.52, built on December 20, 2022
Runtime version: 17.0.5+1-b653.23 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

**Comment by plumpy** [comment]
This should be fixed in 1.16.0.0, which uses a newer officially-supported formatter API.
