### ISSUE TITLE
does nothing

### ISSUE THREAD

**Issue by wayneliu91** [google/google-java-format#910]
MacBook Air M1 2020
MacOS 13.2.1
IDA community edition 2022.3.2
Custom VM Options

-Xmx8048m
--add-exports jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED
--add-exports jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED
--add-exports jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED
--add-exports jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED
--add-exports jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED
--add-exports jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED

then it does nothing

**Comment by plumpy** [comment]
Hm, you're right. I'll update the README, sorry about that. (And thanks for figuring out the issue @zruzak.)
