### ISSUE TITLE
Unintentional changes in version 1.15.0 -> 1.16.0 for IntelliJ plugin?

### ISSUE THREAD

**Issue by EvilScott** [google/google-java-format#914]
Are there supposed to be changes to the formatting standard going from 1.15 to 1.16?

Our org uses this tool to standardize our code style but after the the google formatter IntelliJ plugin our linter started failing PRs due to style issues.

**Comment by EvilScott** [comment]
Myself and another colleague figured out the issue. For the IntelliJ 1.16 plugin, it states that its relying more on the IDE formatting API. This means there are breaking changes for our style settings. We can update things on our end.

![image](https://user-images.githubusercontent.com/489227/223873193-4a429dbf-e62b-4a2f-82e2-2083273b9f2f.png)

**Comment by facboy** [comment]
I'm finding that it seems to allowing Intellij's built-in formatter to run still - this results in it breaking the formatting so that eg a maven build with spotless and `google-java-format` 1.16.0 will subsequently fail with formatting errors.

**Comment by facboy** [comment]
my bad...it was just another case of #908. without having done any exhaustive analysis, the user experience (ie mine) seems to be that when it fails in this way it just acts like the plugin is not installed.

**Comment by plumpy** [comment]
Yeah, that was actually a last-minute change that I waffled about, and maybe made the wrong choice. You should have gotten a single warning when you opened the project, but we'll only show it once. I think there are kinda three options here (but happy to hear if you think of others):

1) Only show the error once, fall back to the built-in formatter (current behavior)
2) Only show the error once, but disable all formatting until it's fixed
3) Show the error on every formatting operation (users can disable the plugin if they want to use the built-in formatter in the meantime)

Originally I had 2, but I changed it to 1 at the last minute. But as I think about it more (spurred by your comment) I think maybe 3 is the right choice?

**Comment by facboy** [comment]
yeah...i think maybe 3 too.  in isolation the 'once only, don't nag me' approach sounds good, but intellij has so many dialogs that pop up (and sometimes not in the window you're using) that it's possible to miss it.

until you mentioned it i hadn't even registered that there was a warning, but i think i do recall seeing it now.  but i think i saw that i was referring to JVM flags, and interpreted it as a 'btw, info if you are installing for the first time'.  i had the flags set, but i think the JBR update has silently broken setting them a certain way (ie it just ignores them if you don't use the `x=y` format).  the warning was really a 'hey, this plugin isn't going to work', but i thought it was a, 'hey in case you didn't know, you need to set these flags.'

**Comment by plumpy** [comment]
Fixed in 1.16.0.1. Can you open a new issue about that other thing? Thanks...

**Comment by EvilScott** [comment]
Can confirm this is resolved for our use case as well. Thanks very much for the quick response! 🥇
