### ISSUE TITLE
Formatter fails when `complex case` is part of switch expression

### ISSUE THREAD

**Issue by wk-tw** [google/google-java-format#922]
**Environment :**

- Java 17 Preview
- Gradle 7.6
- SpotLess plugin version : `id("com.diffplug.spotless") version "6.15.0"`

**SpotLess configuration :**

```
   spotless {
        java {
            googleJavaFormat("1.15.0")
        }
    }
```

**Issue with complex case :**

` case ReachableByEmail c && (c instanceof ReachableByPhone)`

```java
public class PurchaseService {

  String postPurchaseOperation(Customer customer) {
    return switch (customer) {
      case ReachableByEmail c && (c instanceof ReachableByPhone) ->
          String.format("Send message on both email %s and phone number %s",
              c.getEmail(),
              ((ReachableByPhone) c).getPhoneNumber());
      case ReachableByEmail customerWithEmail -> "Send message to his address email : "
          + customerWithEmail.getEmail();
      case ReachableByPhone customerWithPhone -> "Send message to his phone number : "
          + customerWithPhone.getPhoneNumber();
      default -> "Not reachable";
    };
  }
}
```

**Thrown errors**  

`Caused by: com.google.googlejavaformat.java.FormatterException: 8:13: error: expected token: '&'; generated ( instead` and `java.lang.reflect.InvocationTargetException`

**Comment by duncanmak** [comment]
I'm using https://github.com/spotify/fmt-maven-plugin which imports `google-java-format` 1.17.0 and it's failing to format guard clauses in switch expressions.

The error:

> com.google.googlejavaformat.java.FormatterException: 69:13: error: expected token: 'when'; generated - instead

The code:

```java
KiwiNode readTail(boolean dotOK) throws IOException {
    var token = nextToken();

    return switch (token) {
      case String s when s.equals(EOF) -> throw new RuntimeException("EOF during read");
      case String s when s.equals(")") -> ListNode.of();
      case String s when s.equals(".") -> {
          var result = read();
          token = nextToken();
          if (token != ")") warn("Where's the ')'? Got " + token + " after .");
          yield result;
        }
      default -> {
        isPushedToken = true;
        pushedToken = token;
        yield ListNode.cons(read(), readTail(true));
      }
    };
  }
```

**Comment by benzen** [comment]
I'm using 1.18.1 via prettier, this issue is still not resolved.

**Comment by TheCK** [comment]
@benzen I have a fix for this in Java 21 but nobody seems to be looking at pull requests :man_shrugging: 

See: https://github.com/google/google-java-format/pull/988

**Comment by benzen** [comment]
I've seen afterward, but I have no competence for judging it.

I've noticed that your PR was not processed forward because of the CLA agreement that you didn't signed.

Have you signed it since ?

**Comment by TheCK** [comment]
@benzen yeah I did. The check is green now. I think it needs some manual intervention though.
