### ISSUE TITLE
Remove import lombok.var

### ISSUE THREAD

**Issue by tiennm99** [google/google-java-format#932]
Google java format plugin on Jetbrains IDEA auto remove `import lombok.var;` line

**Example**
```
import lombok.var;

public class Main {
    public static void main(String[] args) {
        var string = "string";
    }
}
```
become
```
public class Main {
  public static void main(String[] args) {
    var string = "string";
  }
}
```
And it leads to cannot find symbol var when compile

**Environment**
IntelliJ IDEA 2023.1 (Ultimate Edition)
google-java-format plugin 1.16.0.2
JDK v1.8.0_361

**Comment by cushon** [comment]
Note that isn't valid Java for versions of the language that support local variable type inference:

```
$ javac Main.java
Main.java:1: error: illegal reference to restricted type 'var'
import lombok.var;
             ^
1 error
```
