### ISSUE TITLE
why not public add and Token API?

### ISSUE THREAD

**Issue by jiqimaogou** [google/google-java-format#939]
https://github.com/google/google-java-format/blob/18f835849551f81d60d582300a0a3c585b5774b4/core/src/main/java/com/google/googlejavaformat/OpsBuilder.java#L329

hello, we may want to add some token when format, but I found that these api is not public.

**Comment by cushon** [comment]
It is public in the latest versions, see 4c1aeffc8b0ea3d4e18ffe21162b835f2c51cc3d

**Comment by jiqimaogou** [comment]
hello 

> It is public in the latest versions, see [4c1aeff](https://github.com/google/google-java-format/commit/4c1aeffc8b0ea3d4e18ffe21162b835f2c51cc3d)

hello can you also public Doc.Token constructor?
