### ISSUE TITLE
can't do FormatCode.

### ISSUE THREAD

**Issue by kametsun** [google/google-java-format#987]
https://github.com/google/google-java-format/releases Install google-java-format-1.18.1.jar from this page and then

.vimrc
`
call glaive#Install()
Glaive codefmt google_java_executable="java -jar C:\Users\User\google-java-format-1.18.1.jar"
`

Test.java
`
:FormatCode
Error formatting file: Vim(let):E282:
 Cannot read from "C:\Users\User\AppData\Local\Temp\VZ74C45.tmp"
`

What should I do?

**Comment by cushon** [comment]
This looks like https://github.com/google/vim-codefmt/issues/86
